// Smoke test registry — the suite's ONE plan and its runner.
//
// This file was 65,656 lines. The fixtures moved to smoke/_harness.js and the tests
// to smoke/<domain>.js; what is left is the registry and runSmokeTest(). Reads game
// state via window.G (legacy compat). Regenerated by tools/split-smoke-suite.mjs.
//
// NEVER SENT TO A PLAYER. A dynamic import owned by smoke-test-loader.js, which owns
// all three triggers too; read its header. Guard: tests/boot-budget.mjs.
//
// THE ORDER OF THE IMPORTS BELOW IS THE ORDER THE SUITE RUNS IN. These tests mutate
// one live G and several depend on what the previous one left behind, so the
// concatenation below is a CONTRACT, not a convenience. Add a domain module where its
// tests used to sit; never re-sort this list to tidy it.
import { errorLog, analyzeAssertionCoverage, stampBalanceLikeLoad, watchUiOverlaps, overlayResidue } from './smoke/_harness.js?v=552';
import boot from './smoke/boot.js?v=552';
import propertyAndUnlocks from './smoke/property-and-unlocks.js?v=552';
import companionsClaimsAndRenown from './smoke/companions-claims-and-renown.js?v=552';
import roomsItemsAndEconomy from './smoke/rooms-items-and-economy.js?v=552';
import huntRaidsAndScreens from './smoke/hunt-raids-and-screens.js?v=552';
import recoveryAndAutoEat from './smoke/recovery-and-auto-eat.js?v=552';
import farmAndProfile from './smoke/farm-and-profile.js?v=552';
import musterNavAndIdentity from './smoke/muster-nav-and-identity.js?v=552';
import clanSeatAndFrontDoor from './smoke/clan-seat-and-front-door.js?v=552';
import cookingCoreAndSave from './smoke/cooking-core-and-save.js?v=552';
import bountyAndArtisan from './smoke/bounty-and-artisan.js?v=552';
import questsChronicleAndBonus from './smoke/quests-chronicle-and-bonus.js?v=552';
import awayTimeAndOffline from './smoke/away-time-and-offline.js?v=552';
import recordSeamAndHydration from './smoke/record-seam-and-hydration.js?v=552';
import marketNightAndPrices from './smoke/market-night-and-prices.js?v=552';
import monstersInventoryAndBrand from './smoke/monsters-inventory-and-brand.js?v=552';

const TESTS = [].concat(
  boot, propertyAndUnlocks, companionsClaimsAndRenown,
  roomsItemsAndEconomy, huntRaidsAndScreens, recoveryAndAutoEat,
  farmAndProfile, musterNavAndIdentity, clanSeatAndFrontDoor,
  cookingCoreAndSave, bountyAndArtisan, questsChronicleAndBonus,
  awayTimeAndOffline, recordSeamAndHydration, marketNightAndPrices,
  monstersInventoryAndBrand,
);


export async function runSmokeTest(opts = {}) {
  const verbose = opts.verbose !== false;
  /* ── opts.only — RUN ONE SLICE (dev/focused runners only) ────────────────
     The default is unchanged: no `only`, every test, exactly as CI and the
     🧪 button have always called it. It exists because the assembled suite is
     a several-minute in-page run and the project's own rule is that parallel
     suites blow the budget and read as flakes — so an agent proving a
     single new battery had no way to do it without either running the whole
     thing or not running it at all, and "not running it at all" is how a test
     ships unproven.

     A SOURCE-TEXT match, deliberately: a registered test is
     `() => tryRun('NAME', …)` and the name lives inside the closure, so there
     is nothing to read without either running it or restructuring 1,100
     registrations. `String(fn).indexOf(name)` reads the literal. It is a dev
     affordance and it is loud — the summary carries `only` so a filtered run
     can never be mistaken for a full one in a log. */
  const only = (typeof opts.only === 'string' && opts.only) ? opts.only : null;
  const PLAN = only ? TESTS.filter((t) => String(t).indexOf(only) !== -1) : TESTS;
  const startTab = window.activeTab || 'profile';
  const preErrCount = errorLog.length;
  /* b337: sequential, never Promise.all. These tests mutate the live G and
     several depend on the state the previous one left; running them
     concurrently would be a different suite that happens to share the names. */
  /* ── PARK THE LIVE SETTLE LOOP FOR THE DURATION (Phase 1) ────────────────
     The 90 s settle timer is armed at boot on the authority path, and the suite
     takes minutes — so a real interval settle WILL land mid-run, against
     whatever `window.fetch` the test in flight has stubbed and whatever
     activity a player-action test left running. That is not a hypothetical: the
     b337/B338 batteries COUNT requests and swap the transport, so one stray
     settle is a flake with no obvious cause.

     Parked and restored around the whole run, exactly as `__saveParked` handles
     the 90 s autosave for the same reason. SETTLE-5/6 drive the loop themselves
     on an injected clock, so nothing here is left untested by parking it. */
  const _A = window.HearthriseAccrual;
  const _loopWasRunning = !!(_A && typeof _A.getSettleState === 'function' && _A.getSettleState().running);
  try { if (_loopWasRunning) _A.stopSettleLoop(); } catch (e) {}
  /* ── PARK THE AUTO-EAT SETTINGS SYNC, for the same reason (b499) ──────────
     Thirty-odd tests drive HearthriseAuto.setEat(), and applyLoadout's fixture
     kit carries `foodSlot: null` — so an unparked sync would push a TEST's food
     choice, including an explicit CLEAR, to the live server on the account
     running the suite. The player would come back to auto-eat pointing at
     nothing. AUTOEAT-SYNC-1..3 unpark inside their own bodies (like SETTLE-5/6
     drive the settle loop themselves), so nothing here is left untested. */
  const _Auto = window.HearthriseAuto;
  let _eatSyncWasParked = false;
  try { if (_Auto && typeof _Auto._parkEatSync === 'function') _eatSyncWasParked = _Auto._parkEatSync(true); } catch (e) {}
  /* ── AND THE AUTO-EAT SERVER MIRROR, same reason again ───────────────
     `eatThreshold()` returns the server's own `auto_eat_pct` rather than a local
     preference the client clamped for itself — the local reading WAS the bug.
     About ten fixtures seed a threshold and assert an eat/no-eat outcome or a
     printed percentage; on a signed-in page the REAL account's column would
     govern every one, so they would pass or fail on live data instead of on
     their own fixture. Identical shape to the property-record park above. */
  let _pctMirrorWasParked = false;
  try { if (_Auto && typeof _Auto._parkAutoEatMirror === 'function') _pctMirrorWasParked = _Auto._parkAutoEatMirror(true); } catch (e) {}
  /* ── AND THE COMPANION GRANT LADDER, for exactly the same reason (b499) ───
     `b202: pets` drives a FORCED skill/boss roll. Under the live capstone arm
     that dispatches a real hr_companion_grant; the suite is signed out,
     `not_signed_in` is retryable, and the ladder then sleeps 3/10/30/60 s —
     ~100 s of timers running THROUGH the rest of the suite, ending in a
     notify() toast and a possible G.companions write long after that test's
     `finally` restored everything. TWO ladders, from one test, measured. No
     amount of care inside the individual tests closes that: the leak IS the
     ladder outliving them. HATCH-REFUSE-1..3 unpark inside their own bodies. */
  const _Comp = window.HearthriseCompanions;
  let _grantsWereParked = false;
  try { if (_Comp && typeof _Comp.__parkGrants === 'function') _grantsWereParked = _Comp.__parkGrants(true); } catch (e) {}
  /* ── AND THE QUEST STRIP'S GESTURE-LESS hr_goal_state READ ──────────
     renderStrip() rides Events.on('*'); its session is Auth.getSession(), which
     tests stub to hand THEMSELVES one, so the read lands in their fetch stub —
     B349-R3 measured `hr_goal_state + hr_server_now` for a one-call subject,
     park off/on flips it 4-vs-1. Gesture reads untouched. */
  let _ambientGoalsWereParked = false;
  const _SG = window.__hrSyncServerGoals;
  try { if (_SG) { _ambientGoalsWereParked = !!_SG.parked; _SG.parked = true; } } catch (e) {}
  /* ── THE ONE hr_load THE HARNESS PERFORMS (gold-arm) ─────────────────────
     With gold/gems ARMED, `balanceOf` reads a number only when `G._record`
     vouches for it — the provenance stamp that in production `hr_load` writes
     before the first render. The suite has no live hr_load, so without this the
     live G's gold/gems read UNKNOWN and every ambient balance render/read is
     fail-closed. This is the SINGLE load event, mirroring boot — NOT a per-test
     or per-mutation auto-stamp (which would mask a forgotten re-stamp). Every
     dedicated fail-closed guard (B353-3/3b, B340-*, B347-*, B353-3c) re-creates
     the UNKNOWN state inside its own body, on a live-G delete or a private G, so
     this stamp cannot hide the regression they exist to catch. */
  try { stampBalanceLikeLoad(window.G); } catch (e) {}
  /* ── PARK THE PROPERTY RECORD FOR THE DURATION (b502) ─────────────────────
     ~34 tests seed a property tier by writing `G.homestead = {tier:N}` — the
     RESIDUE half — and then assert a tier-gated number (plot cap, crew cap, room
     gate, castle capstone). As of b502 the SERVER's rung is the tier in BOTH
     directions, so on a live signed-in page (which is exactly how the play gate
     runs the suite) a real envelope's rung would override every one of those
     seeds and ~34 tests would fail on a fixture, not on a defect.

     Parking the record to UNKNOWN for the run makes the residue seed mean what
     the seed says, deterministically, signed in or out. It also RETIRES the
     order-dependence the b495 QA note documented at `unlock_buy slice:
     upgradeProperty…` ("any earlier test that let a server envelope through
     leaves this one upgrading from tier N") — the ratchet is no longer a
     cross-test channel. The tests that are ABOUT the record (b492-*, PROP-*)
     state it explicitly inside their own bodies and restore it, exactly as
     before. Restored from the captured pair in the finally, so a live session
     never loses a rung a real envelope had already delivered. */
  /* ── AND THE RENOWN RANK-UP WATCHER, for the same reason (2026-09-07) ────
     `HearthriseRenown` polls every 4 s and, on a rank boundary, appends a
     FULL-SCREEN celebration scrim that closes only on a click. The suite hands
     `G` kills, gold and levels by the dozen, so a fixture crosses a rank the
     account never earned, the scrim goes up, and nothing in the suite ever
     clicks it — it then covers every later screen. MEASURED on b513: "b221: the
     shop renders the counter scene" failed on
     `something is covering the buy control COVER=<div>.hr-rn-cele`, ~340 tests
     after whichever battery moved the score, intermittently, because it depends
     on where the 4 s poll lands. Same class as the settle loop and the autosave
     above; same answer. RENOWN tests that are ABOUT the celebration call
     `celebrate()` directly, which the park does not touch. */
  const _Rn = window.HearthriseRenown;
  let _rnPollWasOn = true;
  try { if (_Rn && typeof _Rn.__setPollEnabled === 'function') _rnPollWasOn = _Rn.__setPollEnabled(false); } catch (e) {}
  const _Prop = window.HearthriseProperty;
  let _propParked = null;
  try {
    if (_Prop && typeof _Prop.__resetPropertyRecord === 'function') _propParked = _Prop.__resetPropertyRecord();
  } catch (e) {}
  const results = [];
  try {
    let residueBefore = overlayResidue();
    for (const t of PLAN) {
      const r = await t();
      /* ── THE TEARDOWN ASSERTION (2026-09-23) ──────────────────────────────
         A test that finishes with a modal still up, the body scroll still
         locked, or a full-viewport scrim painted does not fail. The NEXT test
         does — or a layout guard running on a different page entirely does,
         hundreds of tests later, with nothing in its output pointing back
         here. That bill has now been paid twice: the renown celebration scrim
         parked above (a shop test failing on a COVER= some 340 tests after
         whichever battery crossed the rank) and the 2026-09-23 reachability
         red. So the residue is measured after
         every test and ATTRIBUTED to the test that introduced it, which is the
         only way the name in the ✗ is the name of the offender; then the
         baseline is re-taken so one dirty test cannot redden every test after
         it. Closing it is the test's own job, in its finally — this only says
         whose job it was. */
      const residueAfter = overlayResidue();
      const introduced = residueAfter.filter((x) => residueBefore.indexOf(x) === -1);
      if (introduced.length) {
        try { if (typeof window.closeAllModals === 'function') window.closeAllModals(); } catch (e) {}
        if (r.status === 'PASS') {
          r.status = 'FAIL';
          r.why = 'left the page dirty for every test after it — ' + introduced.join('; ')
            + '. Close it in the test\'s finally; an overlay left up covers later screens '
            + 'and reads as an unrelated failure somewhere else.';
        }
      }
      residueBefore = overlayResidue();
      if (verbose) {
        const mark = r.status === 'PASS' ? '✓ ' : (r.status === 'SKIP' ? '⃠ SKIP ' : '✗ ');
        console.log(mark + r.name + (r.why ? ' — ' + r.why : ''));
      }
      results.push(r);
    }
  } finally {
    try {
      if (_loopWasRunning && _A) { _A.setSettleEnv(null); _A.startSettleLoop(); }
    } catch (e) {}
    try { if (_Auto && typeof _Auto._parkEatSync === 'function') _Auto._parkEatSync(_eatSyncWasParked); } catch (e) {}
    try { if (_Auto && typeof _Auto._parkAutoEatMirror === 'function') _Auto._parkAutoEatMirror(_pctMirrorWasParked); } catch (e) {}
    try { if (_Comp && typeof _Comp.__parkGrants === 'function') _Comp.__parkGrants(_grantsWereParked); } catch (e) {}
    try { if (_SG) _SG.parked = _ambientGoalsWereParked; } catch (e) {}
    try { if (_Comp && typeof _Comp.__clearGrantBlocks === 'function') _Comp.__clearGrantBlocks(); } catch (e) {}
    try { if (_Rn && typeof _Rn.__setPollEnabled === 'function') _Rn.__setPollEnabled(_rnPollWasOn); } catch (e) {}
    try {
      /* THE RECEIPT, not the pair: __resetPropertyRecord round-trips the
         exact/floor provenance too, so a live session whose record was only a
         FLOOR (a truncated projection) is not put back as an EXACT statement —
         which would let the restore lower a residue the server never measured. */
      if (_propParked && _Prop) _Prop.__resetPropertyRecord(_propParked);
    } catch (e) {}
  }
  try { window.showTab(startTab); } catch {}

  /* ── SA-013 ASSERTION-COVERAGE (increment 2 — STRICT is live) ─────────────
     The coverage diagnostic still prints every run, but it is no longer
     verdict-neutral: HR_ASSERT_STRICT defaults ON, so a PASS that executed zero
     assertions and is not a declared skip() now FAILS the run. Reading the flag
     from opts OR window lets run-smoke.mjs and a dev console opt OUT (to
     reproduce the old report-only behaviour) without another edit here. */
  /* SA-013 (increment 2): HR_ASSERT_STRICT now defaults ON. The backlog is
     cleared — the coverage diagnostic reports ZERO uncounted PASSes, so every
     registered test either executes ≥1 real assertion or is an explicit skip().
     From here a PASS that executed zero assertions and is not a declared SKIP is
     a coverage regression and the suite fails on it (see the strict block below).
     Opt OUT only to reproduce the old verdict-neutral diagnostic while
     investigating: pass { strictAsserts:false } or set window.HR_ASSERT_STRICT
     = false. */
  const HR_ASSERT_STRICT = opts.strictAsserts === false ? false
    : (typeof window !== 'undefined' && window.HR_ASSERT_STRICT === false) ? false
    : true;
  const assertDiag = analyzeAssertionCoverage(PLAN, results);
  if (HR_ASSERT_STRICT) {
    /* zeroAssertPasses only ever holds status==='PASS' entries (analyze skips
       SKIP/FAIL), so a declared skip is never failed here. Every one that
       remains ran ZERO assertions while claiming PASS — the exact silent-green
       this whole change exists to abolish — so fail it, throw-only included
       (increment 2 converted the real throw-only tests to counted asserts, so a
       throw-only PASS now is a NEW one that slipped the net). */
    for (const z of assertDiag.zeroAssertPasses) {
      const r = results[z.index];
      if (r && r.status === 'PASS') {
        r.status = 'FAIL';
        r.why = 'HR_ASSERT_STRICT: PASSED without executing a single assertion (asserts=0). '
          + 'Give it a real assertion; or, if the seam is genuinely not armed / the environment '
          + 'is not present in this run, declare it with skip(reason) so it reports as SKIPPED, not PASSED.';
      }
    }
  }

  const summary = {
    total: results.length,
    passed: results.filter((r) => r.status === 'PASS').length,
    failed: results.filter((r) => r.status === 'FAIL').length,
    // SA-013 (increment 2): a SKIP is neither passed nor failed — it is an
    // honest "not run". passed + failed + skipped === total.
    skipped: results.filter((r) => r.status === 'SKIP').length,
    runtimeErrors: errorLog.length - preErrCount,
    results,
    // Present ONLY on a filtered run, so a partial result can never be read as
    // a full one — in a log, in CI output, or by a future caller.
    only,
    registered: TESTS.length,
    // SA-013: machine-readable coverage diagnostic for increment 2 + CI.
    assertionDiagnostic: {
      strict: HR_ASSERT_STRICT,
      zeroAssertPasses: assertDiag.zeroAssertPasses.map((z) => z.name),
      assertsNothing: assertDiag.assertsNothing.map((z) => z.name),
      throwOnlyPasses: assertDiag.throwOnlyPasses.map((z) => z.name),
      earlyReturn: assertDiag.earlyReturn.map((z) => z.name),
      assertTrueSites: assertDiag.assertTrueSites,
      totalTrueSkips: assertDiag.totalTrueSkips,
    },
    timestamp: new Date().toISOString(),
  };
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  if (only) console.log(`⚠ FILTERED RUN — only tests matching "${only}" (${PLAN.length} of ${TESTS.length})`);
  console.log(`SMOKE TEST: ${summary.passed}/${summary.total} passed, ${summary.failed} failed, ${summary.skipped} skipped, ${summary.runtimeErrors} runtime errors`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  /* The diagnostic block. It is intentionally bounded: the full inventory lives
     in docs/reports/sa-013-assertion-inventory.md, but the zero-assert PASSes
     (the actionable list) are printed in full because that list must stay small
     and any growth is a regression to catch in review. */
  console.log('SA-013 ASSERTION COVERAGE (HR_ASSERT_STRICT default ON — a zero-assert non-skip PASS fails the run):');
  console.log(`  declared skips: ${summary.skipped}`);
  console.log(`  zero-assert PASSes: ${assertDiag.zeroAssertPasses.length}`
    + `  (asserts-nothing: ${assertDiag.assertsNothing.length}`
    + `, throw-only: ${assertDiag.throwOnlyPasses.length}`
    + `, early-return-before-assert: ${assertDiag.earlyReturn.length})`);
  console.log(`  assert(true) skip sites: ${assertDiag.assertTrueSites.length} tests / ${assertDiag.totalTrueSkips} literals`);
  if (assertDiag.zeroAssertPasses.length) {
    console.log('  Tests that PASSED without executing any assertion:');
    for (const z of assertDiag.zeroAssertPasses) {
      const tag = z.srcAsserts > 0 ? `early-return (source declares ${z.srcAsserts} assert)`
        : (z.throwsOnFail ? 'verifies via throw? (review)' : 'ASSERTS NOTHING');
      console.log(`    - [${tag}] ${z.name}`);
    }
  }
  console.log(`  HR_ASSERT_STRICT is ${HR_ASSERT_STRICT ? 'ON (a zero-assert non-skip PASS was failed)' : 'OFF (report-only; opted out via opts/window)'}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  return summary;
}

export function setupSmokeTest() {
  window.__smokeTest = runSmokeTest;
  /* b535 — the suite SIGNS its work: legacy.js block 29 publishes a rival
     ~40-test __smokeTest, so runners wait on this, not on the bare global. */
  window.__smokeTestSource = 'esm';
  // Live watcher — logs any new overlaps that appear during normal play
  // (debounced 250ms after every tab change / resize). Deduped by signature
  // so the same violation only logs once per session.
  setTimeout(() => watchUiOverlaps(), 1500);
  console.log('[Smoke Test ESM] loaded — UI overlap watcher armed');
}
