import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
const ROOT = normalize(process.cwd());
const MIME = { '.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon','.woff2':'font/woff2','.webmanifest':'application/manifest+json' };
const { port } = await new Promise((res) => { const s = createServer(async (req, r) => { try { const p = decodeURIComponent((req.url||'/').split('?')[0]); let f = normalize(join(ROOT, p === '/' ? '/index.html' : p)); if (!f.startsWith(ROOT)) { r.writeHead(403).end(); return; } const i = await stat(f).catch(()=>null); if (i?.isDirectory()) f = join(f,'index.html'); r.writeHead(200,{'Content-Type':MIME[extname(f).toLowerCase()]||'application/octet-stream','Cache-Control':'no-store'}).end(await readFile(f)); } catch { r.writeHead(404).end(); } }); s.listen(0,'127.0.0.1',()=>res({server:s,port:s.address().port})); });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', (e)=>console.log('PAGEERR', e.message));
await page.addInitScript(() => { window.__HR_TEST_HARNESS__ = true; });
await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: 'load', timeout: 60000 });
await page.waitForFunction(() => typeof window.__smokeTest === 'function', { timeout: 60000 });
await page.waitForTimeout(6000);
const code = await readFile(process.argv[2], 'utf8');
console.log(JSON.stringify(await page.evaluate(code), null, 1));
await browser.close(); process.exit(0);
