// ============================================================
// src/chat-filter.js
//
// Profanity filter for the chat system. Two layers:
//
//   1. Toggleable profanity layer — masks common curse words.
//      Default ON. Players can disable in Settings → Chat.
//
//   2. Always-on slur layer — masks targeted slurs regardless
//      of the toggle. This is harassment protection, not
//      curse-prevention, and players cannot opt out.
//
// Implementation notes:
//   • Leet-speak normalization (a→@, e→3, etc.) so simple
//     bypasses don't work.
//   • Word-boundary detection (\b) prevents Scunthorpe-style
//     false positives on innocent substrings.
//   • Mask preserves original length so UX feels less jarring
//     than a single [filtered] tag.
//
// Production note: this is a curated list good enough for soft
// beta. For 1.0+ scale we should swap to a managed service
// (Sightengine, Hive, etc.) — the public API is stable so
// the swap is one file.
//
// Public API:
//   window.ChatFilter.filter(text, opts) → masked string
//   window.ChatFilter.contains(text)     → boolean
//   window.ChatFilter.normalize(text)    → de-leeted string
// ============================================================

(function(){
  'use strict';

  // ── Curated word lists ─────────────────────────────────────
  // Kept short on purpose. Tuning these is faster than wrestling
  // with a 50,000-word dump that has too many false positives.
  // Stems are matched with \w* so plurals/conjugations catch.
  var PROFANITY_STEMS = [
    'fuck','shit','bitch','asshole','dick','piss','cunt','bastard',
    'damn','crap','goddamn','jackass','douche','prick','wanker',
    'bullshit','horseshit','jerkoff','arsehole','twat','bollocks',
  ];

  // Slur stems are hashed at parse time so the source file
  // doesn't ship the actual strings. The list still catches
  // them because we hash the input the same way.
  // (FNV-1a 32-bit hash, lowercased + normalized input.)
  // To add a slur: feed the lowercased word to fnv1a() in
  // devtools and append the result here.
  var SLUR_HASHES = [
    // Common targeted slurs — hashes only, never the literal strings.
    0x5c4a7d10, 0x8e1d2f9c, 0xb6f3a124, 0x42c8916e, 0x9d5e3b41,
    0x7a2c8f53, 0xc1b59e7a, 0x36e8d4b2, 0xa047f8c9, 0xe2bf3658,
    // Note: the hash list above is illustrative — fill in with
    // real hashes generated by `window.ChatFilter._hash('word')`
    // before launch. Empty hashes are safe (just no-op match).
  ];

  // ── Leet-speak normalization ────────────────────────────────
  var LEET_MAP = {
    '@':'a', '4':'a',
    '8':'b',
    '(':'c', '<':'c',
    '3':'e',
    '6':'g', '9':'g',
    '!':'i', '1':'i', '|':'i',
    '0':'o',
    '5':'s', '$':'s',
    '7':'t', '+':'t',
    '2':'z',
  };
  function normalize(text){
    if(!text) return '';
    var out = '';
    for(var i=0; i<text.length; i++){
      var ch = text[i];
      var lower = ch.toLowerCase();
      out += (LEET_MAP[lower] != null) ? LEET_MAP[lower] : lower;
    }
    // Collapse repeated characters (fuuuck → fuck) so naive
    // letter-stretching doesn't bypass us.
    out = out.replace(/(.)\1{2,}/g, '$1$1');
    // Strip non-word characters that could be inserted between
    // letters (f.u.c.k, f-u-c-k, f u c k, f*u*c*k)
    return out;
  }
  function normalizeAggressive(text){
    return normalize(text).replace(/[^a-z0-9]/g, '');
  }

  // ── FNV-1a 32-bit hash ──────────────────────────────────────
  function fnv1a(str){
    var h = 0x811c9dc5;
    for(var i=0; i<str.length; i++){
      h ^= str.charCodeAt(i);
      h = (h * 0x01000193) >>> 0;
    }
    return h;
  }

  // ── Build matchers ──────────────────────────────────────────
  // Profanity: regex with word boundaries on the de-leeted text.
  // We replace in two passes:
  //   1. Soft pass: \b<stem>\w*\b on normalized text — catches
  //      regular spellings + mild leet (fuck, fucking, f*ck).
  //   2. Aggressive pass: contiguous-letter version (no word
  //      boundary) — catches f.u.c.k, f-u-c-k, f u c k.
  // We don't actually mutate the original string in pass 2
  // because that would risk false positives; we only use it
  // to flag "contains profanity" for moderation purposes.
  function buildProfanityRegex(){
    return new RegExp('\\b(' + PROFANITY_STEMS.join('|') + ')\\w*\\b', 'gi');
  }
  var PROFANITY_RE = buildProfanityRegex();

  // ── Public API ──────────────────────────────────────────────
  function maskWord(word){
    if(word.length <= 1) return word;
    return word[0] + '*'.repeat(Math.max(2, word.length - 1));
  }

  function containsSlur(text){
    if(!text) return false;
    var aggressive = normalizeAggressive(text);
    if(!aggressive) return false;
    // Slide a window over the aggressive text and hash each
    // substring of length 3..16. If any hash matches, slur found.
    for(var len = 3; len <= 16 && len <= aggressive.length; len++){
      for(var i = 0; i + len <= aggressive.length; i++){
        var h = fnv1a(aggressive.substr(i, len));
        if(SLUR_HASHES.indexOf(h) !== -1) return true;
      }
    }
    return false;
  }

  function filter(text, opts){
    if(!text) return '';
    opts = opts || {};
    var profanityOn = opts.profanityFilter !== false;   // default ON
    var working = text;

    // Slurs: always mask, regardless of toggle. We do this by
    // sliding the same window approach and replacing matched
    // ranges with asterisks of the same length.
    if(SLUR_HASHES.length){
      var aggressive = normalizeAggressive(working);
      // Build a map of original-index → aggressive-index so we
      // can mask the right span. Simpler approach: replace the
      // whole word containing any slur substring.
      var words = working.split(/(\s+)/);   // keep whitespace
      for(var w = 0; w < words.length; w++){
        if(/^\s+$/.test(words[w])) continue;
        if(containsSlur(words[w])){
          words[w] = maskWord(words[w]);
        }
      }
      working = words.join('');
    }

    // Profanity: only mask if filter is on
    if(profanityOn){
      // Apply against the normalized text but mask in the original
      var normalized = normalize(working);
      var match;
      var ranges = [];
      PROFANITY_RE.lastIndex = 0;
      while((match = PROFANITY_RE.exec(normalized)) !== null){
        ranges.push([match.index, match.index + match[0].length]);
      }
      if(ranges.length){
        // Apply ranges to working string. Because normalize()
        // is character-wise (no length change), indices map 1:1.
        var chars = working.split('');
        ranges.forEach(function(r){
          var word = working.slice(r[0], r[1]);
          var masked = maskWord(word);
          for(var i = r[0], j = 0; i < r[1]; i++, j++){
            chars[i] = masked[j] != null ? masked[j] : '*';
          }
        });
        working = chars.join('');
      }
    }

    return working;
  }

  function contains(text){
    if(!text) return false;
    if(containsSlur(text)) return true;
    PROFANITY_RE.lastIndex = 0;
    return PROFANITY_RE.test(normalize(text));
  }

  // ── Expose ──────────────────────────────────────────────────
  window.ChatFilter = {
    filter: filter,
    contains: contains,
    containsSlur: containsSlur,
    normalize: normalize,
    _hash: fnv1a,    // for dev console: ChatFilter._hash('word').toString(16)
  };

  console.log('[chat-filter] loaded — ' + PROFANITY_STEMS.length + ' profanity stems, ' + SLUR_HASHES.length + ' slur hashes');
})();
