-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — THE SERVER HEARTHFIND CATALOGUE  (GENERATED — DO NOT EDIT)
--
-- ⚠⚠⚠ REVIEW ONLY — NOT AUTO-APPLIED. Applied by the Coordinator after the
--     Security GO, in apply order: THIS FILE, then 2026-09-08-hearthfind.sql
--     (which fails closed without these tables).
--
--   Generated by tools/gen-hearthfind.mjs from src/data/hearthfind.js +
--   src/data/items.js, with one_in and expected_hours DERIVED by
--   src/core/hearthfind.js deriveOneIn — the same function the engine rolls
--   from. Any hand edit is reverted by the next generation and FAILS
--   `node tools/gen-hearthfind.mjs --check`.
--
--   hearthfind digest: 85af9e8038b718b89cee818c02b1dcc2449018f70b34afaf570a793a16f33594
--   4 trophies · 12 sources · odds 1 in 14940 … 1 in 420000
--   band: EXPECTED HOURS 100–400 at the source
--
-- Read by hr_apply's hearthfind arm to re-derive the trophy, the source, the
-- odds and the cosmetic unlocks under the character lock. Numbers and ids only;
-- no client value crosses. Idempotent: delete+insert inside the transaction.
-- ════════════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.hr_items') is null then
    raise exception 'hr_items is absent — apply 2026-08-11-catalogue.generated.sql first';
  end if;
end $$;

-- ── hr_hearthfind_items: the trophy allowlist + the title each one unlocks ──
create table if not exists public.hr_hearthfind_items (
  item_id text primary key,
  name    text not null
);
-- Additive on a database that already holds the pre-ruling shape.
alter table public.hr_hearthfind_items add column if not exists title_code text;
alter table public.hr_hearthfind_items add column if not exists title_name text;

-- ── hr_hearthfind_meta: the set name, the set title, the plinth code ───────
-- Generated from HEARTHFIND_SET_NAME / HEARTHFIND_SET_TITLE / HEARTHFIND_PLINTH
-- so hr_apply reads the cosmetic codes from the catalogue instead of carrying
-- hand-typed string literals in its body (the data double-copy rule).
create table if not exists public.hr_hearthfind_meta (
  key   text primary key,
  value text not null
);

-- ── hr_hearthfind_sources: one row per source, carrying the odds ───────────
-- ⚠ THE CHECK IS THE LAST LINE OF DEFENCE ON THE BAND, and it is stated in the
--   unit the Designer ruled in: EXPECTED HOURS. The generator refuses an
--   out-of-band row and src/core/hearthfind.js throws on one, but both of those
--   are JavaScript. This constraint is Postgres refusing to STORE the number,
--   so even a hand-typed INSERT by an operator cannot make a find common —
--   nor, at the 1-in-420,000 end, make one unreachable.
create table if not exists public.hr_hearthfind_sources (
  source_kind text   not null check (source_kind in ('monster','node')),
  source_id   text   not null,
  item_id     text   not null references public.hr_hearthfind_items(item_id) on delete cascade,
  one_in      bigint not null check (one_in > 0),
  primary key (source_kind, source_id)
);
alter table public.hr_hearthfind_sources add column if not exists expected_hours numeric;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'hr_hearthfind_sources_hours_band') then
    alter table public.hr_hearthfind_sources
      add constraint hr_hearthfind_sources_hours_band
      check (expected_hours is not null
             and expected_hours >= 100 and expected_hours <= 400);
  end if;
end $$;

-- Engine-only reads, exactly like the dungeon catalogue. RLS on, and every
-- grant revoked — INCLUDING service_role, which bypasses RLS: a leaked service
-- key must not be able to retune the rarest odds in the game.
alter table public.hr_hearthfind_items   enable row level security;
alter table public.hr_hearthfind_sources enable row level security;
alter table public.hr_hearthfind_meta    enable row level security;
do $$
begin
  revoke all on public.hr_hearthfind_items   from public, anon, authenticated, service_role;
  revoke all on public.hr_hearthfind_sources from public, anon, authenticated, service_role;
  revoke all on public.hr_hearthfind_meta    from public, anon, authenticated, service_role;
end $$;

delete from public.hr_hearthfind_sources;
delete from public.hr_hearthfind_items;
delete from public.hr_hearthfind_meta;
insert into public.hr_hearthfind_items (item_id, name, title_code, title_name) values
  ('deepvein_lodestar', 'Deepvein Lodestar', 'deepdelver', 'Deepdelver'),
  ('emberheart', 'Emberheart', 'emberkeeper', 'Emberkeeper'),
  ('tidecallers_pearl', 'Tidecaller''s Pearl', 'tidelistener', 'Tidelistener'),
  ('worldroot_seed', 'Worldroot Seed', 'rootwarden', 'Rootwarden');
insert into public.hr_hearthfind_meta (key, value) values
  ('set_name', 'The Four Hearthfinds'),
  ('set_title_code', 'wonderkeeper'),
  ('set_title_name', 'Wonderkeeper'),
  ('plinth_code', 'hearth_plinth');
insert into public.hr_hearthfind_sources (source_kind, source_id, item_id, one_in, expected_hours) values
  ('monster', 'dragon', 'emberheart', 14940, 180),
  ('monster', 'elk_king', 'emberheart', 22750, 250),
  ('monster', 'grim_reaper', 'emberheart', 24860, 220),
  ('node', 'copper_rock', 'deepvein_lodestar', 420000, 350),
  ('node', 'dawnstone_rock', 'deepvein_lodestar', 54000, 180),
  ('node', 'duskwood_tree', 'worldroot_seed', 49846, 179.9994),
  ('node', 'mithril_rock', 'deepvein_lodestar', 112500, 250),
  ('node', 'moonfish_s', 'tidecallers_pearl', 46286, 180.0011),
  ('node', 'normal_tree', 'worldroot_seed', 420000, 350),
  ('node', 'shark_s', 'tidecallers_pearl', 69231, 250.0008),
  ('node', 'shrimp_s', 'tidecallers_pearl', 360000, 350),
  ('node', 'yew_tree', 'worldroot_seed', 90000, 250);

-- ── Self-verification ──────────────────────────────────────────────────────
do $$
declare v_i int; v_s int; v_bad int; v_lo numeric; v_hi numeric;
begin
  select count(*) into v_i from public.hr_hearthfind_items;
  if v_i <> 4 then raise exception 'hr_hearthfind_items has % rows, expected 4', v_i; end if;
  select count(*) into v_s from public.hr_hearthfind_sources;
  if v_s <> 12 then raise exception 'hr_hearthfind_sources has % rows, expected 12', v_s; end if;
  if (select count(*) from public.hr_hearthfind_meta) <> 4 then
    raise exception 'hr_hearthfind_meta has the wrong row count';
  end if;

  -- (a) THE BAND, IN HOURS, asserted against the stored rows and not merely
  --     constrained. This is the ruling's clamp: every source must sit between
  --     100 and 400 expected hours at
  --     its own action rate — never a per-roll number, which says nothing
  --     comparable across a 12x spread of roll rates.
  select min(expected_hours), max(expected_hours) into v_lo, v_hi from public.hr_hearthfind_sources;
  if v_lo < 100 or v_hi > 400 then
    raise exception 'hearthfind hours span % .. % - outside the 100-400 band', v_lo, v_hi;
  end if;
  select count(*) into v_bad from public.hr_hearthfind_sources where one_in <= 0 or expected_hours is null;
  if v_bad > 0 then raise exception '% hearthfind sources have no usable odds', v_bad; end if;

  -- (b) Every trophy is a real, untradeable, worthless-to-a-vendor item in the
  --     MAIN catalogue, and unlocks exactly one title.
  select count(*) into v_bad from public.hr_hearthfind_items h
   where not exists (select 1 from public.hr_items i where i.item_id = h.item_id);
  if v_bad > 0 then raise exception '% hearthfind trophies are not in hr_items', v_bad; end if;
  select count(*) into v_bad from public.hr_hearthfind_items h
    join public.hr_items i on i.item_id = h.item_id
   where i.tradeable or i.value <> 0;
  if v_bad > 0 then
    raise exception '% hearthfind trophies are tradeable or vendorable — a find would mint gold or reach the market', v_bad;
  end if;
  select count(*) into v_bad from public.hr_hearthfind_items
   where title_code is null or title_name is null;
  if v_bad > 0 then raise exception '% hearthfind trophies unlock no title', v_bad; end if;
  select count(*) into v_bad from (
    select title_code from public.hr_hearthfind_items group by title_code having count(*) > 1) x;
  if v_bad > 0 then raise exception 'two hearthfind trophies share a title code'; end if;

  -- (c) Every trophy is actually reachable, and every source pays a real one.
  select count(*) into v_bad from public.hr_hearthfind_items h
   where not exists (select 1 from public.hr_hearthfind_sources s where s.item_id = h.item_id);
  if v_bad > 0 then raise exception '% hearthfind trophies have no source — the allowlist would accept an unfindable item', v_bad; end if;

  -- (d) No client write policy, and no client grant of any kind — service_role
  --     INCLUDED (it bypasses RLS, so a leaked key is a retune of the odds).
  select count(*) into v_bad from pg_policies
   where schemaname = 'public'
     and tablename in ('hr_hearthfind_items','hr_hearthfind_sources','hr_hearthfind_meta');
  if v_bad > 0 then raise exception '% policies on the hearthfind catalogue — it is engine-only', v_bad; end if;
  select count(*) into v_bad from information_schema.role_table_grants
   where table_schema = 'public'
     and table_name in ('hr_hearthfind_items','hr_hearthfind_sources','hr_hearthfind_meta')
     and grantee in ('anon','authenticated','service_role','PUBLIC');
  if v_bad > 0 then raise exception '% client grants on the hearthfind catalogue', v_bad; end if;
end $$;
