-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — hr_gem_unlocks, THE GEM PRICE CATALOGUE  (GENERATED — DO NOT EDIT)
--
--   Generated by tools/gen-catalogues.mjs from src/data/shops.js SHOP_OFFERS.
--   Any hand edit is reverted by the next generation and FAILS
--   `node tools/gen-catalogues.mjs --check`, which is a preflight in
--   tests/run-sql-tests.mjs and tests/run-smoke.mjs.
--
--   catalogue digest: 9896459844110c709bcab5263d6974ed8cce0cd72dbb3381cb589db6c531aab2
--   rows: 10 (9 priced, 1 free) across 2 namespaces (cosmetic, theme)
--
-- WHAT THIS IS FOR. public.hr_buy_gem_unlock (2026-09-14-gem-unlock-buy.sql)
-- takes an unlock id and an idempotency key and NOTHING ELSE — no price, no
-- currency, no quantity. It reads what the thing costs HERE, under the character
-- lock, from a table no browser role may read or write. Today the only gem
-- purchase path in the shipped game is src/render/shop.js rendering
-- `buyCosmetic('<id>', <price>)` — THE PRICE IS AN ARGUMENT THE CLIENT PASSES
-- — and src/legacy.js refusing the gesture outright (refuseGemPurchase) because
-- the balance is server-of-record and there is no verb. This table is the half
-- that makes a real verb possible.
--
-- WHY A TABLE AND NOT A LITERAL. The same reason as every other catalogue in
-- this schema, plus one specific to a price: a hand-typed gem ladder in PL/pgSQL
-- is a SECOND copy of a money number, and the first reprice would leave the shop
-- card and the debit disagreeing with nobody able to see which is right.
--
-- THE FREE ROW, AND WHY IT IS A COLUMN RATHER THAN AN ABSENCE. `theme:default`
-- (Cozy Cottage) costs gold 0 — the free equip, designer slice 6: non-gem themes
-- are equipped free, never bought. It is carried here with `free = true` and
-- `cost_gems = 0`, pinned to each other by a CHECK, for two reasons that pull
-- in opposite directions and are both real:
--   · it must never be SELLABLE. A zero-priced offer in a purchase catalogue is
--     an infinite faucet, so hr_buy_gem_unlock refuses `free` rows outright
--     (`not_for_sale`) — there is no zero-gem code path at all.
--   · it must be OWNED. The moment the client reads ownership server-first
--     (src/legacy.js ownsGemUnlock prefers the projected set over the residue),
--     a default theme missing from that set makes the STARTING theme
--     unequippable — setTheme() gates on exactly that predicate. So the
--     projection unions the free rows in for every character.
-- Absence would have given the first property and silently broken the second.
--
-- APPLY ORDER: 2026-08-16-unlocks.generated.sql (hr_unlocks — the STORAGE
--              catalogue this one is joined against) → THIS FILE →
--              2026-09-14-gem-unlock-buy.sql (which FAILS CLOSED without it).
--
-- SAFE TO RE-RUN. Rows are replaced wholesale in one statement pair, so a
-- RETIRED cosmetic really disappears — an upsert-only generator leaves a ghost
-- row behind, and a ghost row here is something still for sale that the game no
-- longer renders.
-- ════════════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.hr_unlocks') is null then
    raise exception 'hr_unlocks is missing — apply 2026-08-16-unlocks.generated.sql first';
  end if;
end $$;

create table if not exists public.hr_gem_unlocks (
  -- The id as player_progress.key will spell it: '<namespace>:<id>'. Same string
  -- as hr_unlocks.unlock_id, and the parity check below refuses a row that is
  -- not there.
  unlock_id text primary key,
  namespace text   not null,
  -- The SHOP_OFFERS id ('theme.forest'), kept so a ledger row can be traced back
  -- to the offer the player actually tapped without re-deriving the spelling.
  offer_id  text   not null unique,
  name      text   not null,
  cost_gems bigint not null check (cost_gems >= 0),
  -- ⚠ `free` IS NOT A DISCOUNT. It marks a row that is OWNED BY EVERY CHARACTER
  --   FOR FREE and IS NOT FOR SALE — today exactly `theme:default`, the Cozy
  --   Cottage src/legacy.js hands every new character in its initial G
  --   (`ownedThemes:['default']`). It is in this table rather than absent from it
  --   because the projection has to be able to say "you own the default" the
  --   moment the client reads ownership SERVER-FIRST; a free row that is simply
  --   missing would make the starting theme unequippable
  --   (setTheme gates on ownsGemUnlock). hr_buy_gem_unlock refuses it
  --   `not_for_sale` — there is no zero-gem purchase path, which is the rule the
  --   invariant below pins from both directions.
  free      boolean not null default false,
  constraint hr_gem_unlocks_free_iff_zero check (free = (cost_gems = 0))
);

-- Wholesale replace. One transaction with the insert below it.
delete from public.hr_gem_unlocks;

insert into public.hr_gem_unlocks (unlock_id, namespace, offer_id, name, cost_gems, free) values
  ('cosmetic:avatar_dragon','cosmetic','cosmetic.avatar_dragon','Dragon Avatar',500,false),
  ('cosmetic:emote_pack','cosmetic','cosmetic.emote_pack','Emote Pack',300,false),
  ('cosmetic:name_gold','cosmetic','cosmetic.name_gold','Golden Name',200,false),
  ('cosmetic:pet_phoenix','cosmetic','cosmetic.pet_phoenix','Phoenix Pet',1200,false),
  ('theme:default','theme','theme.default','Cozy Cottage',0,true),
  ('theme:desert','theme','theme.desert','Desert Oasis',500,false),
  ('theme:fairy','theme','theme.fairy','Fairy Glen',750,false),
  ('theme:forest','theme','theme.forest','Forest Lodge',500,false),
  ('theme:volcanic','theme','theme.volcanic','Volcanic Keep',1000,false),
  ('theme:winter','theme','theme.winter','Winter Chalet',750,false);

-- ── RLS + grants. UNLIKE hr_items/hr_item_buffs this catalogue is NOT
--    world-readable, and the difference is deliberate: the client already
--    authored these prices (it renders them from its own literals), so a SELECT
--    grant would publish a second copy of a money number with no reader, and
--    every reader that matters is a SECURITY DEFINER function. "revoke all",
--    not a three-verb revoke — Supabase's default ACL on public also hands out
--    TRUNCATE, and TRUNCATE bypasses row-level security entirely.
do $$
begin
  alter table public.hr_gem_unlocks enable row level security;
  revoke all on public.hr_gem_unlocks from public, anon, authenticated, service_role;
end $$;

-- ── Self-verification ────────────────────────────────────────────────────
do $$
declare v_n int; v_bad text;
begin
  select count(*) into v_n from public.hr_gem_unlocks;
  if v_n <> 10 then
    raise exception 'hr_gem_unlocks has % rows, generator emitted 10', v_n;
  end if;

  -- CATALOGUE PARITY, THE LOAD-BEARING ONE. Every priced unlock must exist in
  -- hr_unlocks as a FLAG, because that is the storage shape
  -- player_progress_unlock_guard polices and the shape hr_gem_unlocks_of reads.
  -- A priced row with no storage row is a purchase that debits gems and grants a
  -- flag nothing can see.
  select string_agg(g.unlock_id, ', ' order by g.unlock_id) into v_bad
    from public.hr_gem_unlocks g
    left join public.hr_unlocks u on u.unlock_id = g.unlock_id
   where u.unlock_id is null or u.namespace is distinct from g.namespace
      or u.merge <> 'flag' or u.progress_kind is distinct from 'flag';
  if v_bad is not null then
    raise exception 'gem unlocks with no flag-shaped hr_unlocks row: %', v_bad;
  end if;

  -- THE FREE DEFAULT IS PRESENT, AND IT IS FREE. Both halves, because each one
  -- alone is a different live bug: missing → the starting theme cannot be
  -- equipped once ownership reads server-first; priced → a 0-gem purchase path
  -- exists. The CHECK constraint pins free ⇔ cost 0; this asserts the ROW.
  if not exists (select 1 from public.hr_gem_unlocks
                  where unlock_id = 'theme:default' and free and cost_gems = 0) then
    raise exception 'theme:default is missing or is not free — the starting theme must be owned '
                    'by every character and must never be for sale';
  end if;

  -- AND NOTHING ELSE IS FREE. A second free row would be a cosmetic handed to
  -- everybody by a data edit nobody reviewed as a grant.
  select coalesce(string_agg(unlock_id, ', ' order by unlock_id), '') into v_bad
    from public.hr_gem_unlocks where free and unlock_id <> 'theme:default';
  if v_bad <> '' then
    raise exception 'unexpected free gem unlocks (%) — a free row is granted to every character; '
                    'add it deliberately, not by repricing to 0', v_bad;
  end if;

  -- No client write policy, no client grant of ANY kind (this table is not even
  -- readable by a browser role).
  select count(*)::text into v_bad from pg_policies
   where schemaname = 'public' and tablename = 'hr_gem_unlocks';
  if v_bad <> '0' then raise exception '% policies on hr_gem_unlocks — it needs none', v_bad; end if;
  select coalesce(string_agg(distinct grantee || ':' || privilege_type, ', '), '') into v_bad
    from information_schema.role_table_grants
   where table_schema = 'public' and table_name = 'hr_gem_unlocks'
     and grantee in ('anon', 'authenticated', 'service_role', 'PUBLIC');
  if v_bad <> '' then
    raise exception 'hr_gem_unlocks is reachable by a browser role: %', v_bad;
  end if;

  raise notice 'hr_gem_unlocks OK — % rows, digest 9896459844110c709bcab5263d6974ed8cce0cd72dbb3381cb589db6c531aab2', v_n;
end $$;
