-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — GOLD-SPEND SLICES 2 & 3  (GENERATED — DO NOT EDIT BY HAND)
--   worker_hire (6) · plot:farm_land (12) · bank (30)  ·  digest e0c2760e4e9a54e6dd4707e2e082b2835c4c918b35fddb629ad5bfe7c122958f
--
--   Generated by tools/gen-gold-ladders.mjs from src/data/gold-ladders.js.
--   Any hand edit is reverted by the next generation and FAILS
--   `node tools/gen-gold-ladders.mjs --check` (a preflight in tests/run-smoke.mjs).
--
-- ── WHAT THIS FILE DOES ─────────────────────────────────────────────────
-- Arms three permanent gold-priced capabilities as MAX-MERGE unlock ladders so
-- that the EXISTING spend RPC public.hr_unlock_buy (2026-08-16-unlock-buy.sql)
-- sells them WITH NO NEW CODE PATH:
--   · the ladder / rung-order / already_owned / GREATEST-merge invariants,
--   · the per-day clamp, the advisory lock, the idempotency key,
--   · and the property-tier PREREQUISITE — which is how the designer's cap
--     ("workers <= tierDef.workers", "plots <= tierDef.plots") is enforced:
--     each rung carries req_property_tier = the first property tier whose crew /
--     land is large enough, checked in SQL against the character's OWN
--     server-side property tier. A client-sent tier never enters it.
--
-- ── WHY A LADDER, NOT A COUNT ───────────────────────────────────────────
-- Additive count is the wrong server model: concurrent buys double-increment
-- past the cap, a replay double-increments, and worker's ESCALATING price could
-- be dodged by re-buying the cheapest rung. A monotonic max ladder makes every
-- one of those structurally impossible — hr_unlock_buy already refuses a skipped
-- rung, an already-owned rung and an off-ladder value.
--
-- ⚠ APPLY-ORDER / RE-APPLY CONTRACT (READ THIS)
--   public.hr_unlocks and public.hr_unlock_offers are WHOLESALE-REFILLED by the
--   two 2026-08-16 generated catalogues (`delete from ...; insert ...`). Those
--   run EARLIER in migration order, so a full ordered replay is correct: they
--   fill room/property/etc, THEN this file adds the gold ladders. But
--   RE-APPLYING EITHER 2026-08-16 CATALOGUE ALONE WIPES THESE ROWS. They are a
--   SET: after re-applying a 2026-08-16 catalogue, re-apply THIS file. It is
--   fully idempotent (upsert + scoped delete), so re-applying it is always safe.
--
-- REVERSIBILITY
--   delete from public.hr_unlock_offers where offer_id in (48 ids below);
--   delete from public.hr_unlocks where unlock_id in ('worker_hire','plot:farm_land','bank');
--   Nothing else is touched: no function is replaced, no policy is written, no
--   grant is changed. hr_unlock_buy sells whatever these tables carry.
--
-- SAFE TO RE-RUN.
-- ════════════════════════════════════════════════════════════════════════

-- ── 0. PRECONDITIONS — FAIL CLOSED ───────────────────────────────────────
do $$
begin
  if to_regclass('public.hr_unlocks') is null or to_regclass('public.hr_unlock_offers') is null then
    raise exception 'the unlock catalogues are absent — apply the 2026-08-16 unlock migrations first';
  end if;
  if to_regprocedure('public.hr_unlock_buy(uuid,int,bigint,uuid,text)') is null then
    raise exception 'hr_unlock_buy is absent — apply 2026-08-16-unlock-buy.sql first. This file adds '
                    'ladders it SELLS; without the seller they are inert rows.';
  end if;
  if not exists (select 1 from pg_trigger where tgrelid = 'public.player_progress'::regclass
                  and tgname = 'player_progress_unlock_guard' and not tgisinternal) then
    raise exception 'player_progress_unlock_guard is absent — apply 2026-08-16-artisan-progress-model.sql '
                    'first. It is the INDEPENDENT storage guard that refuses an off-ladder rung whatever '
                    'hr_unlock_buy proposes; these ladders rely on it as their backstop.';
  end if;
end $$;

-- ── 1. THE CATALOGUE ROWS (hr_unlocks) — how the level MERGES ────────────
-- Upsert, because worker/plot may already carry a legacy count row from a
-- 2026-08-16 catalogue; these ids are the SERVER-AUTHORITATIVE max ladders.
insert into public.hr_unlocks (unlock_id, namespace, merge, progress_kind, max_value, rungs)
values
  ('worker_hire', 'worker', 'max', 'unlock', 6, array[1,2,3,4,5,6]::int[]),
  ('plot:farm_land', 'plot', 'max', 'unlock', 12, array[1,2,3,4,5,6,7,8,9,10,11,12]::int[]),
  ('bank', 'bank', 'max', 'unlock', 30, array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]::int[])
on conflict (unlock_id) do update
  set namespace = excluded.namespace, merge = excluded.merge,
      progress_kind = excluded.progress_kind, max_value = excluded.max_value, rungs = excluded.rungs;

-- ── 2. THE OFFER ROWS (hr_unlock_offers) — the PRICE and the GATE ────────
-- Scoped delete + insert: this file OWNS exactly these offer ids and touches no
-- other row, so it never fights the wholesale refill for the shop-derived rows.
delete from public.hr_unlock_offers where offer_id in ('worker_hire.1', 'worker_hire.2', 'worker_hire.3', 'worker_hire.4', 'worker_hire.5', 'worker_hire.6', 'farm_land.1', 'farm_land.2', 'farm_land.3', 'farm_land.4', 'farm_land.5', 'farm_land.6', 'farm_land.7', 'farm_land.8', 'farm_land.9', 'farm_land.10', 'farm_land.11', 'farm_land.12', 'bank.0', 'bank.1', 'bank.2', 'bank.3', 'bank.4', 'bank.5', 'bank.6', 'bank.7', 'bank.8', 'bank.9', 'bank.10', 'bank.11', 'bank.12', 'bank.13', 'bank.14', 'bank.15', 'bank.16', 'bank.17', 'bank.18', 'bank.19', 'bank.20', 'bank.21', 'bank.22', 'bank.23', 'bank.24', 'bank.25', 'bank.26', 'bank.27', 'bank.28', 'bank.29');
insert into public.hr_unlock_offers
  (offer_id, table_name, name, unlock_id, value, gold, items, req_property_tier, req_item, refusal)
values
  ('worker_hire.1', 'worker', 'Hire worker #1', 'worker_hire', 1, 500, '{}'::jsonb, 1, null, null),
  ('worker_hire.2', 'worker', 'Hire worker #2', 'worker_hire', 2, 3000, '{}'::jsonb, 2, null, null),
  ('worker_hire.3', 'worker', 'Hire worker #3', 'worker_hire', 3, 15000, '{}'::jsonb, 3, null, null),
  ('worker_hire.4', 'worker', 'Hire worker #4', 'worker_hire', 4, 75000, '{}'::jsonb, 4, null, null),
  ('worker_hire.5', 'worker', 'Hire worker #5', 'worker_hire', 5, 250000, '{}'::jsonb, 5, null, null),
  ('worker_hire.6', 'worker', 'Hire worker #6', 'worker_hire', 6, 750000, '{}'::jsonb, 5, null, null),
  ('farm_land.1', 'plot', 'Farm plot #1', 'plot:farm_land', 1, 100, '{"normal_log":5}'::jsonb, 0, null, null),
  ('farm_land.2', 'plot', 'Farm plot #2', 'plot:farm_land', 2, 100, '{"normal_log":5}'::jsonb, 0, null, null),
  ('farm_land.3', 'plot', 'Farm plot #3', 'plot:farm_land', 3, 100, '{"normal_log":5}'::jsonb, 1, null, null),
  ('farm_land.4', 'plot', 'Farm plot #4', 'plot:farm_land', 4, 100, '{"normal_log":5}'::jsonb, 1, null, null),
  ('farm_land.5', 'plot', 'Farm plot #5', 'plot:farm_land', 5, 100, '{"normal_log":5}'::jsonb, 2, null, null),
  ('farm_land.6', 'plot', 'Farm plot #6', 'plot:farm_land', 6, 100, '{"normal_log":5}'::jsonb, 2, null, null),
  ('farm_land.7', 'plot', 'Farm plot #7', 'plot:farm_land', 7, 100, '{"normal_log":5}'::jsonb, 3, null, null),
  ('farm_land.8', 'plot', 'Farm plot #8', 'plot:farm_land', 8, 100, '{"normal_log":5}'::jsonb, 3, null, null),
  ('farm_land.9', 'plot', 'Farm plot #9', 'plot:farm_land', 9, 100, '{"normal_log":5}'::jsonb, 4, null, null),
  ('farm_land.10', 'plot', 'Farm plot #10', 'plot:farm_land', 10, 100, '{"normal_log":5}'::jsonb, 4, null, null),
  ('farm_land.11', 'plot', 'Farm plot #11', 'plot:farm_land', 11, 100, '{"normal_log":5}'::jsonb, 5, null, null),
  ('farm_land.12', 'plot', 'Farm plot #12', 'plot:farm_land', 12, 100, '{"normal_log":5}'::jsonb, 5, null, null),
  ('bank.0', 'bank', 'Bank expansion (+20)', 'bank', 1, 3000, '{}'::jsonb, 0, null, null),
  ('bank.1', 'bank', 'Bank expansion (+20)', 'bank', 2, 3960, '{}'::jsonb, 0, null, null),
  ('bank.2', 'bank', 'Bank expansion (+20)', 'bank', 3, 5227, '{}'::jsonb, 0, null, null),
  ('bank.3', 'bank', 'Bank expansion (+20)', 'bank', 4, 6900, '{}'::jsonb, 0, null, null),
  ('bank.4', 'bank', 'Bank expansion (+20)', 'bank', 5, 9108, '{}'::jsonb, 0, null, null),
  ('bank.5', 'bank', 'Bank expansion (+20)', 'bank', 6, 12022, '{}'::jsonb, 0, null, null),
  ('bank.6', 'bank', 'Bank expansion (+20)', 'bank', 7, 15870, '{}'::jsonb, 0, null, null),
  ('bank.7', 'bank', 'Bank expansion (+20)', 'bank', 8, 20948, '{}'::jsonb, 0, null, null),
  ('bank.8', 'bank', 'Bank expansion (+20)', 'bank', 9, 27651, '{}'::jsonb, 0, null, null),
  ('bank.9', 'bank', 'Bank expansion (+20)', 'bank', 10, 36499, '{}'::jsonb, 0, null, null),
  ('bank.10', 'bank', 'Bank expansion (+20)', 'bank', 11, 48179, '{}'::jsonb, 0, null, null),
  ('bank.11', 'bank', 'Bank expansion (+20)', 'bank', 12, 63597, '{}'::jsonb, 0, null, null),
  ('bank.12', 'bank', 'Bank expansion (+20)', 'bank', 13, 83948, '{}'::jsonb, 0, null, null),
  ('bank.13', 'bank', 'Bank expansion (+20)', 'bank', 14, 110811, '{}'::jsonb, 0, null, null),
  ('bank.14', 'bank', 'Bank expansion (+20)', 'bank', 15, 146270, '{}'::jsonb, 0, null, null),
  ('bank.15', 'bank', 'Bank expansion (+20)', 'bank', 16, 193077, '{}'::jsonb, 0, null, null),
  ('bank.16', 'bank', 'Bank expansion (+20)', 'bank', 17, 254861, '{}'::jsonb, 0, null, null),
  ('bank.17', 'bank', 'Bank expansion (+20)', 'bank', 18, 336417, '{}'::jsonb, 0, null, null),
  ('bank.18', 'bank', 'Bank expansion (+20)', 'bank', 19, 444071, '{}'::jsonb, 0, null, null),
  ('bank.19', 'bank', 'Bank expansion (+20)', 'bank', 20, 586173, '{}'::jsonb, 0, null, null),
  ('bank.20', 'bank', 'Bank expansion (+20)', 'bank', 21, 773749, '{}'::jsonb, 0, null, null),
  ('bank.21', 'bank', 'Bank expansion (+20)', 'bank', 22, 1021348, '{}'::jsonb, 0, null, null),
  ('bank.22', 'bank', 'Bank expansion (+20)', 'bank', 23, 1348180, '{}'::jsonb, 0, null, null),
  ('bank.23', 'bank', 'Bank expansion (+20)', 'bank', 24, 1779597, '{}'::jsonb, 0, null, null),
  ('bank.24', 'bank', 'Bank expansion (+20)', 'bank', 25, 2349068, '{}'::jsonb, 0, null, null),
  ('bank.25', 'bank', 'Bank expansion (+20)', 'bank', 26, 3100770, '{}'::jsonb, 0, null, null),
  ('bank.26', 'bank', 'Bank expansion (+20)', 'bank', 27, 4093016, '{}'::jsonb, 0, null, null),
  ('bank.27', 'bank', 'Bank expansion (+20)', 'bank', 28, 5402781, '{}'::jsonb, 0, null, null),
  ('bank.28', 'bank', 'Bank expansion (+20)', 'bank', 29, 7131671, '{}'::jsonb, 0, null, null),
  ('bank.29', 'bank', 'Bank expansion (+20)', 'bank', 30, 9413806, '{}'::jsonb, 0, null, null);

-- ── 3. STRUCTURAL ASSERTIONS ─────────────────────────────────────────────
do $$
declare v_n int; v_bad text; v_p oid;
begin
  -- (a) Every ladder row present and SELLABLE.
  select count(*) into v_n from public.hr_unlock_offers
   where refusal is null and offer_id in ('worker_hire.1', 'worker_hire.2', 'worker_hire.3', 'worker_hire.4', 'worker_hire.5', 'worker_hire.6', 'farm_land.1', 'farm_land.2', 'farm_land.3', 'farm_land.4', 'farm_land.5', 'farm_land.6', 'farm_land.7', 'farm_land.8', 'farm_land.9', 'farm_land.10', 'farm_land.11', 'farm_land.12', 'bank.0', 'bank.1', 'bank.2', 'bank.3', 'bank.4', 'bank.5', 'bank.6', 'bank.7', 'bank.8', 'bank.9', 'bank.10', 'bank.11', 'bank.12', 'bank.13', 'bank.14', 'bank.15', 'bank.16', 'bank.17', 'bank.18', 'bank.19', 'bank.20', 'bank.21', 'bank.22', 'bank.23', 'bank.24', 'bank.25', 'bank.26', 'bank.27', 'bank.28', 'bank.29');
  if v_n <> 48 then
    raise exception 'expected 48 sellable gold-ladder offers, found %', v_n;
  end if;

  -- (b) CROSS-CATALOGUE PARITY. Every sellable rung must be a rung the merge
  --     catalogue knows AND inside its ceiling, or hr_unlock_buy would sell it
  --     and the storage guard would then refuse it — a player charged for a
  --     bad_delta. This is the join that makes the two tables agree.
  select string_agg(o.offer_id, ', ') into v_bad
    from public.hr_unlock_offers o
    join public.hr_unlocks u on u.unlock_id = o.unlock_id
   where o.offer_id in ('worker_hire.1', 'worker_hire.2', 'worker_hire.3', 'worker_hire.4', 'worker_hire.5', 'worker_hire.6', 'farm_land.1', 'farm_land.2', 'farm_land.3', 'farm_land.4', 'farm_land.5', 'farm_land.6', 'farm_land.7', 'farm_land.8', 'farm_land.9', 'farm_land.10', 'farm_land.11', 'farm_land.12', 'bank.0', 'bank.1', 'bank.2', 'bank.3', 'bank.4', 'bank.5', 'bank.6', 'bank.7', 'bank.8', 'bank.9', 'bank.10', 'bank.11', 'bank.12', 'bank.13', 'bank.14', 'bank.15', 'bank.16', 'bank.17', 'bank.18', 'bank.19', 'bank.20', 'bank.21', 'bank.22', 'bank.23', 'bank.24', 'bank.25', 'bank.26', 'bank.27', 'bank.28', 'bank.29')
     and (u.merge <> 'max' or u.progress_kind <> 'unlock'
          or not (o.value = any (coalesce(u.rungs, array[]::int[])))
          or (u.max_value is not null and o.value > u.max_value));
  if v_bad is not null then
    raise exception 'gold-ladder offers off their own ladder: %', v_bad;
  end if;

  -- (c) THE TIER GATE IS SANE. A rung whose gate exceeds the top property tier
  --     is a purchase NO player can ever make — an unreachable rung is a dead
  --     gold sink, and a NEGATIVE gate is a client-tier leak.
  select string_agg(offer_id, ', ') into v_bad from public.hr_unlock_offers
   where offer_id in ('worker_hire.1', 'worker_hire.2', 'worker_hire.3', 'worker_hire.4', 'worker_hire.5', 'worker_hire.6', 'farm_land.1', 'farm_land.2', 'farm_land.3', 'farm_land.4', 'farm_land.5', 'farm_land.6', 'farm_land.7', 'farm_land.8', 'farm_land.9', 'farm_land.10', 'farm_land.11', 'farm_land.12', 'bank.0', 'bank.1', 'bank.2', 'bank.3', 'bank.4', 'bank.5', 'bank.6', 'bank.7', 'bank.8', 'bank.9', 'bank.10', 'bank.11', 'bank.12', 'bank.13', 'bank.14', 'bank.15', 'bank.16', 'bank.17', 'bank.18', 'bank.19', 'bank.20', 'bank.21', 'bank.22', 'bank.23', 'bank.24', 'bank.25', 'bank.26', 'bank.27', 'bank.28', 'bank.29')
     and (req_property_tier is null or req_property_tier < 0 or req_property_tier > 5);
  if v_bad is not null then
    raise exception 'gold-ladder offers with an out-of-range property-tier gate: %', v_bad;
  end if;

  -- (d) THE SELLER IS STILL ENGINE-ONLY. This file grants nothing and replaces
  --     nothing, but it is the cheap place to re-assert that the verb these rows
  --     feed cannot be called by a browser — the whole point of the ladder.
  v_p := to_regprocedure('public.hr_unlock_buy(uuid,int,bigint,uuid,text)');
  foreach v_bad in array array['public','anon','authenticated','service_role'] loop
    if has_function_privilege(v_bad, v_p, 'execute') then
      raise exception 'hr_unlock_buy became executable by % — a client could buy the whole crew, all '
                      'the land and a maxed bank for itself with no Edge Function in the way', v_bad;
    end if;
  end loop;

  -- (e) NO CLIENT WRITE SURFACE ON THE OFFER TABLE. It is world-READABLE by
  --     design (the shop screen renders these prices); a client INSERT/UPDATE
  --     would be a client-authored price on a permanent capability.
  select count(*) into v_n from information_schema.role_table_grants
   where table_schema = 'public' and table_name = 'hr_unlock_offers'
     and grantee in ('anon','authenticated','service_role','PUBLIC')
     and privilege_type <> 'SELECT';
  if v_n > 0 then raise exception '% client write grants on hr_unlock_offers', v_n; end if;

  raise notice 'gold-ladders §3 PASSED: 48 sellable rungs across 3 ladders, all on-ladder '
               'and inside ceiling, tier gates in [0,5], the seller engine-only, the price table read-only.';
end $$;

-- ── 4. BEHAVIOUR — the gate BITES, and a legal buy LANDS ─────────────────
-- Every refusal paired with the nearest legal control, run through the REAL
-- hr_unlock_buy so this proves the ladder as the engine sells it, not as SQL
-- imagines it. Skipped (loudly) only if the character bootstrap is absent.
do $$
declare
  v_uid  uuid := '00000000-0000-4000-8000-00000000b192';
  v_r    jsonb; v_ver bigint; v_g0 bigint; v_g1 bigint; v_key uuid;
begin
  if to_regprocedure('public.hr_create_character(int)') is null then
    raise exception 'gold-ladders §4 CANNOT RUN: hr_create_character is missing — a skipped check is '
                    'not a passed one. Apply 2026-08-14-character-bootstrap.sql first.';
  end if;

  begin  -- ── subtransaction, rolled back ────────────────────────────────
    insert into auth.users (id) values (v_uid);
    perform set_config('request.jwt.claim.sub', v_uid::text, true);
    v_r := public.hr_create_character(0);
    if coalesce(v_r->>'ok', v_r->>'created', 'false') <> 'true' then
      raise exception 'gold-ladders §4: no probe character: %', v_r;
    end if;
    update public.player_state set gold = 10000000 where user_id = v_uid and slot = 0;
    insert into public.player_inventory (user_id, slot, item_id, qty)
      values (v_uid, 0, 'normal_log', 1000)
    on conflict (user_id, slot, item_id) do update set qty = 1000;

    -- (a) BANK rung 1 sells at property tier 0 (no gate) and charges 3000g.
    select version, gold into v_ver, v_g0 from public.player_state where user_id=v_uid and slot=0;
    v_key := gen_random_uuid();
    v_r := public.hr_unlock_buy(v_uid, 0, v_ver, v_key, 'bank.0');
    if coalesce(v_r->>'ok','false') <> 'true' then
      raise exception 'gold-ladders §4(a) CONTROL FAILED: bank.0 refused (%)', v_r;
    end if;
    select gold into v_g1 from public.player_state where user_id=v_uid and slot=0;
    if v_g1 <> v_g0 - 3000 then
      raise exception 'gold-ladders §4(a): bank.0 charged %g, expected 3000', v_g0 - v_g1;
    end if;
    -- (b) …and a replay under the same key pays EXACTLY ONCE.
    v_r := public.hr_unlock_buy(v_uid, 0, v_ver, v_key, 'bank.0');
    if coalesce(v_r->>'replayed','false') <> 'true' then
      raise exception 'gold-ladders §4(b): bank.0 replay not reported as one (%)', v_r;
    end if;
    if (select gold from public.player_state where user_id=v_uid and slot=0) <> v_g1 then
      raise exception 'gold-ladders §4(b): the bank replay CHARGED AGAIN';
    end if;

    -- (c) WORKER rung 2 before rung 1 is refused by NAME — the ladder is a ladder.
    select version into v_ver from public.player_state where user_id=v_uid and slot=0;
    v_r := public.hr_unlock_buy(v_uid, 0, v_ver, gen_random_uuid(), 'worker_hire.2');
    if v_r->>'error' is distinct from 'rung_skipped' then
      raise exception 'gold-ladders §4(c): worker_hire.2 before .1 answered % (expected rung_skipped)', v_r;
    end if;

    -- (d) WORKER rung 1 at property tier 0 is refused: a camp hires nobody, and
    --     the SERVER is the one that knows the tier.
    v_r := public.hr_unlock_buy(v_uid, 0, v_ver, gen_random_uuid(), 'worker_hire.1');
    if v_r->>'error' is distinct from 'prereq_property_tier' then
      raise exception 'gold-ladders §4(d): worker_hire.1 at tier 0 answered % (expected '
                      'prereq_property_tier) — the tier cap is the whole invariant', v_r;
    end if;

    -- Grant the homestead (tier 1) the way the property ladder would, then:
    insert into public.player_progress (user_id, slot, kind, key, period_key, value)
      values (v_uid, 0, 'unlock', 'property:homestead', '', 1);

    -- (e) CONTROL — worker_hire.1 now LANDS (tier 1 grants 1 worker).
    select version into v_ver from public.player_state where user_id=v_uid and slot=0;
    v_r := public.hr_unlock_buy(v_uid, 0, v_ver, gen_random_uuid(), 'worker_hire.1');
    if coalesce(v_r->>'ok','false') <> 'true' then
      raise exception 'gold-ladders §4(e) CONTROL FAILED: worker_hire.1 refused at tier 1 (%)', v_r;
    end if;
    -- (f) …but worker_hire.2 still needs tier 2. The cap RISES with the tier and
    --     not one rung faster.
    select version into v_ver from public.player_state where user_id=v_uid and slot=0;
    v_r := public.hr_unlock_buy(v_uid, 0, v_ver, gen_random_uuid(), 'worker_hire.2');
    if v_r->>'error' is distinct from 'prereq_property_tier' then
      raise exception 'gold-ladders §4(f): worker_hire.2 at tier 1 answered % (expected '
                      'prereq_property_tier) — the crew cap outran the property', v_r;
    end if;

    -- (g) FARM land: rungs 1-4 (gates 0,0,1,1) all land at tier 1, IN ORDER,
    --     then rung 5 (needs tier 2) is refused by the TIER GATE. Note rungs 1-4
    --     must be bought first or rung 5 would be refused as rung_skipped, not
    --     by the gate — hr_unlock_buy checks rung order BEFORE the tier prereq.
    for v_g0 in 1..4 loop
      select version into v_ver from public.player_state where user_id=v_uid and slot=0;
      v_r := public.hr_unlock_buy(v_uid, 0, v_ver, gen_random_uuid(), 'farm_land.' || v_g0::text);
      if coalesce(v_r->>'ok','false') <> 'true' then
        raise exception 'gold-ladders §4(g) CONTROL FAILED: farm_land.% refused at tier 1 (%)', v_g0, v_r;
      end if;
    end loop;
    select version into v_ver from public.player_state where user_id=v_uid and slot=0;
    v_r := public.hr_unlock_buy(v_uid, 0, v_ver, gen_random_uuid(), 'farm_land.5');
    if v_r->>'error' is distinct from 'prereq_property_tier' then
      raise exception 'gold-ladders §4(g): farm_land.5 at tier 1 (holding rung 4) answered % '
                      '(expected prereq_property_tier — the land cap tracks the property tier)', v_r;
    end if;

    raise exception using errcode = 'HRB19', message = 'gold-ladders §4 complete — rolling back';
  exception when sqlstate 'HRB19' then
    null;
  end;

  if exists (select 1 from public.player_state where user_id = v_uid)
     or exists (select 1 from auth.users where id = v_uid) then
    raise exception 'gold-ladders §4 LEAKED a probe row';
  end if;

  raise notice 'GOLD-LADDERS OK — bank sells at tier 0 and replays once; the worker crew cap and the '
               'farm-land cap both track the SERVER property tier and refuse a rung the tier does not '
               'reach; the ladder refuses a skipped rung. Every refusal paired with a control. Zero residue.';
end $$;

do $$
begin
  raise notice 'gold-spend slices 2 & 3 INSTALLED — worker_hire(6) + plot:farm_land(12) + bank(30) are '
               'sellable through hr_unlock_buy, each gated on the server-owned property tier.';
end $$;
