-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — hr_item_buffs, THE ITEM → BUFF CATALOGUE  (GENERATED — DO NOT EDIT)
--
--   Generated by tools/gen-catalogues.mjs from src/data/items.js + the
--   src/core/buffs.js BUFFS_DEF vocabulary. Any hand edit is reverted by the
--   next generation and FAILS `node tools/gen-catalogues.mjs --check`, which is
--   a preflight in tests/run-sql-tests.mjs and tests/run-smoke.mjs.
--
--   catalogue digest: 7aa3e258d542953cb49fdbdfe24dc00b7c499eb92330a9710b6fa7f44bc79600
--   rows: 30 buff foods across 9 types (all_xp, combat_xp, damage, damage_crit, defense, drop_rate, farm_yield, gather_speed, gold_find)
--
-- WHAT THIS IS FOR. hr_apply's `buff_apply` delta key carries ONE field — the
-- ITEM ID — and resolves the effect HERE, under the character lock, from the
-- server's own row. Nothing about a buff is representable in the delta: not the
-- type, not the magnitude, not the duration, and above all not the expiry, which
-- is stamped from now() + duration_ms. A client that names an item with no row
-- is refused `bad_buff_item`.
--
-- WHY A TABLE AND NOT A LITERAL. The same reason as every other catalogue in
-- this schema: a hand-typed item→buff list in PL/pgSQL is the data double-copy
-- this repo has already been burned by, and the first balance change would make
-- the tooltip and the engine disagree with nobody able to see it.
--
-- APPLY ORDER: 2026-08-11-catalogue.generated.sql (hr_items) → THIS FILE →
--              2026-09-13-consumable-buffs.sql (which FAILS CLOSED without it).
--
-- SAFE TO RE-RUN. Rows are replaced wholesale in one statement pair, so a
-- DELETED buff food really disappears — an upsert-only generator leaves a ghost
-- row behind, and a ghost is a hole in the allowlist this table exists to be.
-- ════════════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.hr_items') is null then
    raise exception 'hr_items is missing — apply 2026-08-11-catalogue.generated.sql first';
  end if;
end $$;

create table if not exists public.hr_item_buffs (
  item_id     text primary key,
  type        text    not null,
  -- numeric, not int: a magnitude is a PERCENT for most types and a FLAT count
  -- for farm_yield/defense (src/core/buffs.js BUFFS_DEF isFlat), and a designer
  -- authoring 2.5% must not be silently truncated to 2 by the catalogue.
  magnitude   numeric not null check (magnitude > 0),
  duration_ms bigint  not null check (duration_ms > 0)
);

-- Wholesale replace. One transaction with the insert below it.
delete from public.hr_item_buffs;

insert into public.hr_item_buffs (item_id, type, magnitude, duration_ms) values
  ('baked_potato','gather_speed',3,240000),
  ('bear_claw_pie','damage',3,600000),
  ('carrot_stew','farm_yield',1,360000),
  ('cooked_copper_crab','all_xp',2,180000),
  ('cooked_frostfin','defense',4,360000),
  ('cooked_goldgill','drop_rate',2,300000),
  ('cooked_herring','gather_speed',1,120000),
  ('cooked_lobster','drop_rate',3,300000),
  ('cooked_moonfish','all_xp',3,420000),
  ('cooked_pikeperch','gather_speed',2,180000),
  ('cooked_shark','damage',4,360000),
  ('cooked_shrimp','gather_speed',1,120000),
  ('cooked_silverfin','damage',2,240000),
  ('cooked_swordfish','damage',3,300000),
  ('cooked_trout','all_xp',2,180000),
  ('dragon_stew','combat_xp',4,1200000),
  ('ember_tart','combat_xp',4,360000),
  ('fishers_pie','damage',2,600000),
  ('goldenroot_roast','gather_speed',4,360000),
  ('hunters_feast','drop_rate',5,900000),
  ('lich_soul_soup','gold_find',5,300000),
  ('moonbloom_elixir','all_xp',5,480000),
  ('pumpkin_pie','all_xp',3,300000),
  ('river_chowder','defense',2,300000),
  ('roasted_carrot','gather_speed',1,180000),
  ('roasted_pumpkin','farm_yield',1,600000),
  ('tomato_soup','drop_rate',2,240000),
  ('vegetable_stew','all_xp',2,900000),
  ('void_banquet','damage_crit',5,900000),
  ('wheat_bread','drop_rate',1,180000);

-- ── RLS + grants. World-readable (the client renders the same data out of
--    src/data/items.js anyway), writable by NOBODY but the migration owner.
--    Revoke BEFORE grant, and revoke what Supabase's default ACL hands
--    anon/authenticated/service_role on a new table — TRUNCATE included.
do $$
begin
  alter table public.hr_item_buffs enable row level security;
  revoke all on public.hr_item_buffs from public, anon, authenticated, service_role;
  grant select on public.hr_item_buffs to anon, authenticated, service_role;
  drop policy if exists "hr_item_buffs readable" on public.hr_item_buffs;
  create policy "hr_item_buffs readable" on public.hr_item_buffs for select using (true);
end $$;

-- ── Self-verification ────────────────────────────────────────────────────
do $$
declare v_n int; v_bad int;
begin
  select count(*) into v_n from public.hr_item_buffs;
  if v_n <> 30 then
    raise exception 'hr_item_buffs has % rows, generator emitted 30', v_n;
  end if;

  -- CATALOGUE PARITY. Every buff food must be a real item, or hr_apply would
  -- hold a buff for an id the bag can never contain and the eat path could never
  -- reach — a control that reads as present in review and fires for nobody.
  select count(*) into v_bad from public.hr_item_buffs b
   where not exists (select 1 from public.hr_items i where i.item_id = b.item_id);
  if v_bad > 0 then raise exception '% buff foods are not in hr_items', v_bad; end if;

  -- THE VOCABULARY, asserted against the rows that actually landed. The
  -- generator already refused an unknown type in JS; this is the DATABASE's own
  -- check, and the two do not share an input (JS reads src/core/buffs.js, this
  -- reads the table), which is the only way a row that validated at generation
  -- time but did not INSERT is caught.
  select count(*) into v_bad from public.hr_item_buffs
   where type <> all (array['all_xp','combat_xp','damage','damage_crit','defense','drop_rate','farm_yield','gather_speed','gold_find']::text[]);
  if v_bad > 0 then
    raise exception '% buff rows carry a type the engine cannot pay', v_bad;
  end if;

  -- NO ROW MAY EXCEED THE SERVER'S EXPIRY CAP. hr_apply clamps `until` to
  -- now() + 3600000 ms; a longer duration could never be delivered in full and would
  -- make the tooltip a promise the server refuses to hold.
  select count(*) into v_bad from public.hr_item_buffs where duration_ms > 3600000;
  if v_bad > 0 then
    raise exception '% buff foods last longer than the server''s 3600000 ms expiry cap', v_bad;
  end if;

  -- No client write policy, and no client write grant.
  select count(*) into v_bad from pg_policies
   where schemaname = 'public' and tablename = 'hr_item_buffs'
     and cmd in ('INSERT','UPDATE','DELETE','ALL');
  if v_bad > 0 then raise exception '% write policies on hr_item_buffs', v_bad; end if;
  select count(*) into v_bad from information_schema.role_table_grants
   where table_schema = 'public' and table_name = 'hr_item_buffs'
     and grantee in ('anon','authenticated','service_role','PUBLIC')
     and privilege_type <> 'SELECT';
  if v_bad > 0 then raise exception '% client write grants on hr_item_buffs', v_bad; end if;

  raise notice 'hr_item_buffs OK — % rows, digest 7aa3e258d542953cb49fdbdfe24dc00b7c499eb92330a9710b6fa7f44bc79600', v_n;
end $$;
