-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — SERVER-AUTHORITATIVE PLAYER STATE  (foundation, file 1 of 4)
-- Companion design doc: docs/design/server-authority.md
--
-- APPLY ORDER
--   1. THIS FILE
--   2. 2026-08-11-catalogue.generated.sql   (generated by tools/gen-catalogues.mjs)
--   3. 2026-08-11-apply-engine.sql
--   4. 2026-08-11-market-v2.sql
--   Files 3 and 4 FAIL CLOSED if file 2 has not been applied.
--
-- ⚠ REVIEW ONLY — DO NOT APPLY TO PRODUCTION.
--
-- WHAT THIS IS
--   The real tables that replace `game_saves.snapshot`. Today every number a
--   player owns — gold, inventory, all fifteen skill XP totals, equipment,
--   farm plots — lives inside one client-authored jsonb blob that the browser
--   PATCHes. That is the whole exploit: `G.gold = 1e12` → autosave → the
--   market is yours. There is no clever policy that fixes a blob the client
--   writes. The blob has to stop being the source of truth.
--
-- ════════════════════════════════════════════════════════════════════════
-- REVISION 2 — what changed after the security review, and why
--
--   The SHAPE of revision 1 survived review (SELECT-only RLS, escrow by
--   DELETE, server-stamped timestamps, derived levels, no hearth_tokens key in
--   the delta). The EXECUTION did not. The defining change is this one:
--
--   ▸ `hr_engine` — a database role, not a convention.
--     Revision 1 said "Edge Functions never write tables" and then left the
--     Edge Function holding the service role, which by Supabase's default ACL
--     has ALL PRIVILEGES on every table in `public` and BYPASSRLS. The rule was
--     a promise in a comment. Now it is a grant table:
--
--       hr_engine  → EXECUTE on hr_apply. Nothing else. Zero table DML,
--                    anywhere in `public`, asserted by this migration.
--
--     The Edge Function authenticates as hr_engine (a short-lived JWT with
--     `role: hr_engine`, minted from SUPABASE_JWT_SECRET) instead of as the
--     service role. If that function is ever compromised, the attacker's entire
--     capability is "call hr_apply with a delta", which is precisely the
--     surface hr_apply re-validates. It cannot UPDATE player_state.gold,
--     because it has no UPDATE on player_state. (Review S1.)
--
--   ▸ Client roles lose more than INSERT/UPDATE/DELETE. Supabase's default ACL
--     hands anon and authenticated `arwdDxtm` on every new table in public —
--     which includes TRUNCATE, and TRUNCATE is not covered by the append-only
--     UPDATE/DELETE trigger. Verified live: 41 tables × TRUNCATE granted to
--     anon. Every player table here revokes ALL and re-grants only SELECT, and
--     player_ledger additionally grows a statement-level TRUNCATE trigger.
--     (Review S14.)
--
--   ▸ Idempotency is now a table (`player_intents`), not an intention. Every
--     state-changing intent carries a client-generated key; a replay returns
--     the first result instead of applying twice. (Review S8.)
--
--   ▸ The accrual PRNG seed mixes a server-only secret (`hr_server_secrets`),
--     so a player who can see their own `accrued_to` — which hr_load returns,
--     because the UI needs it — still cannot precompute a roll. (Review S20.)
--
--   ▸ Every player-callable RPC is rate-limited from an UNLOGGED counter
--     table. Unlogged because a rate counter is worth exactly zero WAL.
--
-- GREENFIELD — THE BETA IS WIPED AT CUTOVER (CLAUDE.md, "Server authority",
--   locked 2026-08-10). No migration from game_saves.snapshot, no amnesty, no
--   dual-write. `game_saves` is NOT dropped here — it is left inert so the old
--   client keeps working until cutover.
--
-- SAFE TO RE-RUN. Additive only. Nothing existing is dropped or altered.
--   ⚠ NEVER re-run supabase/schema.sql against production — its §1b
--     `drop table … cascade`s market/clan/raid data.
--
-- THE FIVE RULES EVERY TABLE HERE OBEYS (the clan-seat pattern, generalised
-- from supabase/migrations/2026-08-08-clan-seat.sql `clan_deposit` at :527):
--   1. SELECT-own only. No insert/update/delete policy on any player table,
--      and no client-role write GRANT either. A policy-less, grant-less table
--      is the enforcement; application logic drifts, an absent privilege
--      cannot.
--   2. The server clock is the only clock — now(), never a client timestamp.
--   3. Every value that can be spent is bounded by a CHECK, not by code.
--   4. Every mutation writes an append-only row to player_ledger.
--   5. Concurrency is decided by one optimistic `version` on player_state,
--      not by hope. See 2026-08-11-apply-engine.sql.
-- ════════════════════════════════════════════════════════════════════════

-- ── 0. Preconditions ─────────────────────────────────────────────────────
do $$
begin
  if to_regclass('public.profiles') is null then
    raise exception 'public.profiles is missing — run supabase/schema.sql on a FRESH project first';
  end if;
  -- pg_cron is a HARD dependency of this foundation, not a deploy step.
  -- Every append-only table created below ships its retention policy in the
  -- same file (reliability RL2/RL3), and a retention policy that is "scheduled
  -- separately, later, by hand" is a retention policy that does not exist. The
  -- receipt: game_events reached 1.6M rows / 229 MB from six players in 3.45
  -- days and had to be truncated by hand on 2026-08-11.
  -- Installed on this project as pg_cron 1.6.4 (verified).
  --
  -- ⚠ to_regprocEDURE, not to_regproc. to_regproc takes a bare NAME and returns
  --   NULL both for "missing" and for "ambiguous" — and cron.schedule has two
  --   overloads, so `to_regproc('cron.schedule')` is NULL on a database where
  --   pg_cron is perfectly healthy. Handing it an argument list does not help:
  --   to_regproc does not parse one, so `to_regproc('cron.schedule(text,text,
  --   text)')` is NULL ALWAYS. This precondition therefore aborted the whole
  --   foundation on EVERY database, including the correct one. Caught by the
  --   behavioural gate on 2026-08-11 — a self-verifying block is only worth
  --   what executing it is worth.
  if to_regprocedure('cron.schedule(text,text,text)') is null then
    raise exception 'pg_cron is required — enable the pg_cron extension before applying the server-authority foundation';
  end if;
end $$;

-- ── 0b. THE ENGINE ROLE ──────────────────────────────────────────────────
-- This is the load-bearing change of revision 2 and it deserves the space.
--
-- The identity seam in revision 1 could not execute: hr_apply read auth.uid()
-- but was revoked from `authenticated`. Called with the service role,
-- auth.uid() is null → 'not_signed_in'. Called with a forwarded user JWT, the
-- role is `authenticated` → permission denied. Mutually exclusive. (Review S1.)
--
-- The fix is a third identity that is NEITHER the player NOR the service role:
--
--   authenticator ──(set role)──▶ hr_engine
--                                   ├─ USAGE on schema public
--                                   ├─ EXECUTE on hr_apply  (and the seed fn)
--                                   └─ NOTHING ELSE. No SELECT, no INSERT,
--                                      no UPDATE, no DELETE, on any table.
--
-- The Edge Function verifies the player's JWT itself, then calls hr_apply over
-- PostgREST with a short-lived engine JWT and passes the verified user id as
-- p_user. hr_apply honours p_user ONLY when the request's role is hr_engine —
-- read from the `role` GUC, because inside a SECURITY DEFINER function
-- current_user is the function's OWNER, not the caller (verified, not assumed).
--
-- Two properties fall out, and they are the reason this is worth a role:
--   • "Edge Functions never write tables" stops being a code-review rule and
--     becomes a privilege check the database performs on every statement.
--   • The blast radius of a compromised Edge Function is bounded by hr_apply's
--     own validation, rather than by the honesty of the code inside it.
--
-- NOTE the role is NOLOGIN and NOINHERIT: it cannot connect directly, only be
-- switched into by `authenticator`, and it does not silently inherit anything
-- granted to a group it might later be added to.
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'hr_engine') then
    create role hr_engine nologin noinherit;
  end if;
  -- PostgREST switches into the role named by the JWT's `role` claim; it can
  -- only do that if `authenticator` is a member.
  if exists (select 1 from pg_roles where rolname = 'authenticator') then
    execute 'grant hr_engine to authenticator';
  end if;
  -- ...and the migration owner, so an admin session or the SQL test suite can
  -- SET ROLE hr_engine to exercise the engine path. In Postgres 16+ the creator
  -- of a role does NOT automatically get SET membership (verified on this
  -- database), so without this line the seam is untestable.
  if not pg_has_role(current_user, 'hr_engine', 'SET') then
    execute format('grant hr_engine to %I', current_user);
  end if;
  execute 'grant usage on schema public to hr_engine';
  -- Belt and braces: whatever else happens in this file, hr_engine ends it
  -- holding no table privilege in public. Re-asserted at the bottom.
  execute 'revoke all on all tables in schema public from hr_engine';
  execute 'revoke all on all sequences in schema public from hr_engine';
  execute 'revoke all on all functions in schema public from hr_engine';
end $$;

-- ── 1. The character row ─────────────────────────────────────────────────
-- One row per character. `slot` keeps the existing multi-character model
-- (src/multi-character.js) — the client already keys everything on
-- (user_id, slot) and the market rows already carry seller_slot.
--
-- Deliberately NARROW. Anything that is a COLLECTION (skills, items,
-- equipment, plots, quests) is its own table, because a jsonb bag on this row
-- is how we got here: a blob has no constraints, no per-key policy and no
-- index, and it invites the client to send the whole thing back.
create table if not exists public.player_state (
  user_id      uuid    not null references auth.users(id) on delete cascade,
  slot         int     not null default 0 check (slot between 0 and 5),

  -- Currencies. bigint because gold is a lifetime accumulator; CHECKed >= 0 so
  -- no code path can ever leave a negative balance behind, whatever it thinks
  -- it is doing.
  gold         bigint  not null default 0     check (gold  >= 0),
  gems         bigint  not null default 0     check (gems  >= 0),
  -- The IAP bond. Its own column, never touched by any PvE code path, so
  -- "no PvE minting of the Hearth Token" is auditable by grep rather than by
  -- reading every reward function.
  hearth_tokens bigint not null default 0     check (hearth_tokens >= 0),

  -- Vitals. Combat is resolved server-side, so HP is server state.
  hp           int     not null default 10    check (hp >= 0),
  max_hp       int     not null default 10    check (max_hp > 0),

  -- THE ACTIVITY POINTER — the whole idle game in four columns.
  -- `active_kind`  what loop is running
  -- `active_id`    which node/recipe/monster (validated against hr_activities)
  -- `active_since` SERVER timestamp the loop started
  -- `accrued_to`   SERVER timestamp accrual has already been PAID up to.
  --                Elapsed is ALWAYS now() - accrued_to, never a client delta,
  --                and `collect` advances it in the same transaction that pays
  --                — which is what makes double-collect impossible.
  active_kind  text    not null default 'idle'
               check (active_kind in ('idle','gather','artisan','combat')),
  active_id    text,
  active_since timestamptz,
  accrued_to   timestamptz not null default now(),

  bank_cap     int     not null default 100  check (bank_cap between 1 and 100000),

  -- Optimistic concurrency. Every write bumps it; every write is REQUIRED to
  -- name the version it read. See hr_apply() in the apply-engine migration —
  -- revision 1 treated a null version as "skip the check", which meant the
  -- concurrency control was opt-in for the caller (review S9).
  version      bigint  not null default 0,

  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  primary key (user_id, slot),

  -- An activity without a target (or a target without an activity) is a state
  -- the accrual engine cannot interpret. Refuse it at the schema.
  constraint player_state_activity_chk
    check ((active_kind = 'idle') = (active_id is null))
);

-- ── 2. Skills ────────────────────────────────────────────────────────────
-- XP only. LEVEL IS NEVER STORED — it is derived from XP by one function
-- (§8), because two representations of the same fact drift, and the one that
-- drifted last time is exactly the one the leaderboard read.
create table if not exists public.player_skills (
  user_id  uuid   not null,
  slot     int    not null,
  skill_id text   not null,
  xp       bigint not null default 0 check (xp >= 0),
  primary key (user_id, slot, skill_id),
  foreign key (user_id, slot) references public.player_state(user_id, slot) on delete cascade
);

-- ── 3. Inventory + equipment ─────────────────────────────────────────────
-- Per-item ROWS, not a jsonb bag. Same reasoning as clan_stores
-- (2026-08-08-clan-seat.sql :261): no hot-row contention, a natural per-item
-- constraint, and the bank cap becomes `count(*)` instead of a client honour
-- system.
create table if not exists public.player_inventory (
  user_id uuid   not null,
  slot    int    not null,
  item_id text   not null,
  qty     bigint not null check (qty > 0),   -- a zero row is deleted, never stored
  primary key (user_id, slot, item_id),
  foreign key (user_id, slot) references public.player_state(user_id, slot) on delete cascade
);
create index if not exists player_inventory_item_idx
  on public.player_inventory (item_id);

-- Equipment is a fixed set of named slots, so it is a row per occupied slot
-- with the slot name as key. `equip_slot` is validated against hr_equip_slots,
-- generated from src/data/gathering.js EQUIP_SLOTS — so adding a slot is a data
-- edit plus a regenerate, never a DDL change.
--
-- CONSERVATION, not exclusion: equipping DEBITS one unit from player_inventory
-- and unequipping CREDITS it back (see hr_apply's equip block, rewritten for
-- review S4). The reviewer asked for "equipped ⇒ not in inventory" as a DB
-- invariant; that is not expressible and not true — a player may legitimately
-- own two Rune Swords and wear one. What is true, and what hr_apply enforces,
-- is that the total count of an item is conserved across an equip/unequip pair.
create table if not exists public.player_equipment (
  user_id    uuid not null,
  slot       int  not null,
  equip_slot text not null,
  item_id    text not null,
  primary key (user_id, slot, equip_slot),
  foreign key (user_id, slot) references public.player_state(user_id, slot) on delete cascade
);

-- ── 4. Farm ──────────────────────────────────────────────────────────────
-- Farming is the one system whose progress is WALL-CLOCK rather than
-- action-count: a crop grows whether or not the player is doing anything.
--
-- No `ready` boolean and no `growth` number is stored. Readiness is DERIVED:
--   ready  ⇔  now() >= planted_at + growth_interval(crop, watered)
-- A stored flag would need a cron to flip it, and a cron is a second clock.
create table if not exists public.player_farm (
  user_id    uuid not null,
  slot       int  not null,
  plot_idx   int  not null check (plot_idx between 0 and 63),
  crop_id    text,
  planted_at timestamptz,
  watered_at timestamptz,
  primary key (user_id, slot, plot_idx),
  foreign key (user_id, slot) references public.player_state(user_id, slot) on delete cascade,
  -- An empty plot has no crop and no clock. A planted one has both.
  constraint player_farm_planted_chk
    check ((crop_id is null) = (planted_at is null))
);

-- ── 5. Quests / dailies / counters ───────────────────────────────────────
-- One generic progress table rather than a table per system. The kinds are a
-- CHECK so a typo is a constraint violation, not a silently separate universe
-- of rows that never satisfies its goal.
--
-- `state` is now CHECKed too. Revision 1 accepted any string from the delta,
-- including 'claimed' — which is the one transition that must never be
-- client-driven, because 'claimed' is what gates the payout (review S13).
-- hr_apply refuses to write 'claimed' from the generic progress block; the
-- dedicated `progress_claim` block is the only route, and it requires the row
-- to already be 'done'.
create table if not exists public.player_progress (
  user_id    uuid   not null,
  slot       int    not null,
  kind       text   not null check (kind in ('quest','daily','bounty','stat','collection','flag')),
  key        text   not null check (length(key) between 1 and 64),
  value      bigint not null default 0,
  period_key text   not null default '' check (length(period_key) <= 16),
  state      text   check (state in ('active','done','claimed')),
  updated_at timestamptz not null default now(),
  primary key (user_id, slot, kind, key, period_key),
  foreign key (user_id, slot) references public.player_state(user_id, slot) on delete cascade
);

-- RELIABILITY RL3/RL4 — THE TWO POPULATIONS IN THIS TABLE ARE NOT THE SAME.
--   period_key = ''   PERMANENT state: quest completion, lifetime stats,
--                     collection flags. Bounded by CONTENT (a few hundred rows
--                     per character at most), so it is kept forever and read
--                     in full.
--   period_key <> ''  PERIODIC state: one row per daily/weekly per period, per
--                     character, FOREVER. That is the unbounded population.
--                     600 players × 6 dailies × 365 days = 1.3M rows/year, and
--                     revision 2 read ALL of them on every hr_load.
-- So: a partial index that only covers the periodic rows (the permanent ones
-- are never scanned this way and should not pay for the index), a prune, and a
-- matching read filter in hr_state_of. The read filter and the prune window are
-- deliberately the SAME number — if they ever diverge, the client silently
-- stops seeing rows that still exist.
create index if not exists player_progress_period_idx
  on public.player_progress (updated_at)
  where period_key <> '';

create or replace function public.hr_progress_prune(p_older interval default interval '31 days')
returns int language plpgsql security definer set search_path = public as $$
declare v_n int;
begin
  delete from public.player_progress
   where period_key <> ''
     and updated_at < now() - greatest(interval '7 days', coalesce(p_older, interval '31 days'));
  get diagnostics v_n = row_count;
  return v_n;
end $$;
revoke execute on function public.hr_progress_prune(interval)
  from public, anon, authenticated, service_role;

-- ── 6. THE JOURNAL ───────────────────────────────────────────────────────
-- Every mutation of every table above writes here, in the same transaction.
-- ONE ROW PER APPLY, never one per tick. Live evidence for why: game_events
-- reached 1.6M rows / 229 MB from SIX players in four days by logging every
-- kill and every gather. The accrual model already collapses a session into a
-- single apply; the journal must not undo that.
-- ⚠ THE PRIMARY KEY IS (at, id), NOT (id). (Reliability RL2(d).)
--   `id bigserial primary key` looks harmless and is a one-way door: Postgres
--   requires the partition key to be part of every unique constraint, so a
--   PK on (id) alone makes "partition by range (at)" a full table REBUILD
--   later, on the largest table in the database, at exactly the moment volume
--   is the problem. Putting `at` in front of `id` costs nothing today (the
--   table is empty) and keeps the option open. It also gives the retention job
--   the index it needs for free — which is why player_ledger_kind_idx is gone:
--   two secondary indexes on the hottest insert path in the game is three
--   writes per apply, and the (at, id) PK already serves "recent rows by kind"
--   well enough for an admin query.
create table if not exists public.player_ledger (
  id       bigserial,
  user_id  uuid not null,
  slot     int  not null,
  kind     text not null check (kind in
             ('accrue','craft','gather','combat','farm','trade','shop',
              'quest','equip','admin','iap','clan','raid')),
  intent   text,                  -- the intent name that caused it
  item_id  text,
  qty      bigint,
  gold     bigint,
  skill_id text,
  xp       bigint,
  meta     jsonb not null default '{}'::jsonb,
  at       timestamptz not null default now(),
  primary key (at, id)
);
create index if not exists player_ledger_user_idx on public.player_ledger (user_id, slot, at desc);
-- Retired: see the PK comment above. Dropped explicitly so a database that ran
-- an earlier revision of this file converges on the same shape.
drop index if exists public.player_ledger_kind_idx;

-- If an earlier revision created the table with `id` as the sole PK, migrate it
-- — but ONLY while it is empty. A rebuild of a populated ledger is a decision
-- for a maintenance window, not a side effect of re-running a migration.
do $$
declare v_pk text; v_rows bigint;
begin
  select conname into v_pk from pg_constraint
   where conrelid = 'public.player_ledger'::regclass and contype = 'p';
  -- attname is `name`, not `text`; without the cast this comparison is
  -- `name[] = text[]`, which is not an operator that exists and which fails at
  -- RUNTIME, not at create time. Caught by executing the block, not reading it.
  if v_pk is not null and (
       select array_agg(a.attname::text order by k.ord)
         from pg_constraint c
         cross join lateral unnest(c.conkey) with ordinality as k(attnum, ord)
         join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum
        where c.conname = v_pk and c.conrelid = 'public.player_ledger'::regclass
     ) = array['id'] then
    execute 'select count(*) from public.player_ledger' into v_rows;
    if v_rows = 0 then
      execute format('alter table public.player_ledger drop constraint %I', v_pk);
      execute 'alter table public.player_ledger add primary key (at, id)';
      raise notice 'player_ledger PK migrated (id) -> (at, id) while empty';
    else
      raise warning 'player_ledger PK is (id) and the table holds % rows — '
                    'partitioning will require a rebuild. Not doing it implicitly.', v_rows;
    end if;
  end if;
end $$;

-- ── 6a. APPEND-ONLY, BUT PRUNABLE (Reliability RL2(a)) ───────────────────
-- Revision 2 raised on `before update OR DELETE` unconditionally, which made a
-- retention job IMPOSSIBLE: the only way to shrink the ledger was to drop the
-- trigger, and a control you have to disable to operate the system is a control
-- that will be left off. Meanwhile the projection is 600 MB/day at 600 players
-- — Pro's 8 GB disk in a fortnight — and this repo has already lived that once
-- (game_events: 1.6M rows / 229 MB from SIX players in 3.45 days, truncated
-- 2026-08-11, database 245 MB → 16 MB).
--
-- The property that actually matters is not "no row may ever be removed" — it
-- is "NOBODY CAN REWRITE OR ERASE RECENT HISTORY". So:
--   • UPDATE      — always refused. A ledger row is never edited, at any age.
--   • DELETE      — refused inside the retention window; permitted outside it,
--                   which is precisely what hr_ledger_prune() needs and nothing
--                   more. An attacker covering their tracks is interested in
--                   the last hour, not in rows from a quarter ago.
--   • TRUNCATE    — always refused. It is indiscriminate and it bypasses RLS.
-- No client role holds UPDATE/DELETE/TRUNCATE on this table anyway (§7); the
-- trigger is the second, independent lock.
create table if not exists public.hr_ledger_config (
  only_row      boolean primary key default true check (only_row),
  retain_days   int not null default 90 check (retain_days between 7 and 3650)
);
insert into public.hr_ledger_config (only_row) values (true) on conflict do nothing;
alter table public.hr_ledger_config enable row level security;

create or replace function public.hr_ledger_immutable()
returns trigger language plpgsql set search_path = public as $$
declare v_keep int;
begin
  if tg_op = 'DELETE' then
    select retain_days into v_keep from public.hr_ledger_config;
    if old.at >= now() - make_interval(days => coalesce(v_keep, 90)) then
      raise exception 'player_ledger row is inside the % day retention window and cannot be deleted',
        coalesce(v_keep, 90) using errcode = 'check_violation';
    end if;
    return old;
  end if;
  raise exception 'player_ledger is append-only (attempted %)', tg_op
    using errcode = 'check_violation';
end $$;
revoke execute on function public.hr_ledger_immutable() from public, anon, authenticated, service_role;

drop trigger if exists hr_ledger_immutable on public.player_ledger;
create trigger hr_ledger_immutable
  before update or delete on public.player_ledger
  for each row execute function public.hr_ledger_immutable();

-- TRUNCATE is not UPDATE and it is not DELETE. A row-level trigger never sees
-- it, and Supabase's default ACL grants it to anon on every new table. An
-- append-only ledger that can be emptied in one statement is a decoration.
-- (Review S14.) The grant is revoked below AND the statement is refused here.
drop trigger if exists hr_ledger_no_truncate on public.player_ledger;
create trigger hr_ledger_no_truncate
  before truncate on public.player_ledger
  for each statement execute function public.hr_ledger_immutable();

-- ── 6a-ii. THE ROLLUP — what survives the prune ──────────────────────────
-- Deleting the ledger outright would destroy the only long-term record of value
-- movement, which is the thing the ledger exists for. So the prune ROLLS UP
-- before it deletes: one row per (character, month, kind) carrying the totals.
-- 600 players × 12 months × 13 kinds = ~94k rows PER YEAR, permanently — three
-- orders of magnitude below the raw rows it replaces, and it still answers
-- "where did this player's gold come from" a year later.
create table if not exists public.player_ledger_rollup (
  user_id   uuid not null,
  slot      int  not null,
  month     date not null,
  kind      text not null,
  n         bigint not null default 0,
  gold_in   bigint not null default 0,
  gold_out  bigint not null default 0,
  primary key (user_id, slot, month, kind)
);

-- Batched on purpose: an unbounded `delete from … where at < …` on a table that
-- has been left alone for a month is a multi-minute exclusive-ish operation
-- competing with live traffic. p_limit rows per call, called hourly.
create or replace function public.hr_ledger_prune(p_limit int default 20000)
returns int language plpgsql security definer set search_path = public as $$
declare v_keep int; v_cut timestamptz; v_n int;
begin
  select retain_days into v_keep from public.hr_ledger_config;
  -- One second of slack so the prune never argues with the trigger's own
  -- boundary check about which side of `now()` a row is on.
  v_cut := now() - make_interval(days => coalesce(v_keep, 90)) - interval '1 second';

  with doomed as (
    select id, at from public.player_ledger
     where at < v_cut
     order by at, id
     limit greatest(1, least(100000, coalesce(p_limit, 20000)))
     for update skip locked
  ),
  rolled as (
    insert into public.player_ledger_rollup as r (user_id, slot, month, kind, n, gold_in, gold_out)
      select l.user_id, l.slot, date_trunc('month', l.at)::date, l.kind,
             count(*), sum(greatest(coalesce(l.gold,0), 0)), sum(greatest(-coalesce(l.gold,0), 0))
        from public.player_ledger l join doomed d on d.id = l.id and d.at = l.at
       group by 1,2,3,4
    on conflict (user_id, slot, month, kind) do update
      set n = r.n + excluded.n,
          gold_in = r.gold_in + excluded.gold_in,
          gold_out = r.gold_out + excluded.gold_out
    returning 1
  )
  delete from public.player_ledger l
   using doomed d where l.id = d.id and l.at = d.at;
  get diagnostics v_n = row_count;
  return v_n;
end $$;
revoke execute on function public.hr_ledger_prune(int)
  from public, anon, authenticated, service_role;

-- ── 6b. Idempotency ──────────────────────────────────────────────────────
-- Every state-changing intent carries a client-generated uuid. A replay — a
-- retried fetch, a double-fired button, an Edge Function that timed out after
-- committing — returns the FIRST result instead of applying a second time.
--
-- The row is written inside the same transaction as the effect, so "recorded"
-- and "applied" cannot disagree: if the apply rolls back, so does the record,
-- and the retry is free to try again. (Review S8.)
--
-- Retention: rows older than a day are pruned by hr_intents_prune(). A dedupe
-- window only has to outlive a client's retry budget.
create table if not exists public.player_intents (
  user_id   uuid not null,
  intent_id uuid not null,
  slot      int  not null,
  intent    text,
  result    jsonb,
  at        timestamptz not null default now(),
  primary key (user_id, intent_id)
);
create index if not exists player_intents_at_idx on public.player_intents (at);

create or replace function public.hr_intents_prune(p_older interval default interval '24 hours')
returns int language plpgsql security definer set search_path = public as $$
declare v_n int;
begin
  delete from public.player_intents
   where at < now() - greatest(interval '1 hour', coalesce(p_older, interval '24 hours'));
  get diagnostics v_n = row_count;
  return v_n;
end $$;
revoke execute on function public.hr_intents_prune(interval) from public, anon, authenticated, service_role;

-- ── 6b-ii. THE REJECTION RECORD (review R4) ──────────────────────────────
-- hr_apply's blast-radius clamps (gold_clamp, gem_clamp, item_clamp, xp_clamp,
-- progress_clamp) are documented as "treat any rejection as an incident, not a
-- tuning problem". Revision 2 then wrote the only trace of them INSIDE the
-- block that a rejection rolls back, so the trace rolled back with it: the sole
-- surviving evidence was player_intents.result, which hr_intents_prune deletes
-- after 24 hours. A control nobody can observe firing is not a control.
--
-- WHY THIS IS AN AGGREGATE AND NOT A ROW PER REJECTION.
--   Journal rule 6 in this codebase exists because game_events reached 1.6M
--   rows from six players. `version_conflict` is a NORMAL outcome of optimistic
--   concurrency — two tabs, a retry, a slow network — and at 240 applies/min/
--   player a row per rejection rebuilds game_events in the security table.
--   So: one row per (character, code, DAY), counter incremented in place.
--   Bounded by players × codes × days: 600 players × ~8 codes × 365 = 1.75M
--   rows/YEAR worst case if every player trips every code every day, and
--   realistically three orders of magnitude less. Pruned at 180 days.
--
--   `severity` is derived from the code by the recorder, not supplied, so
--   "show me every incident this week" is one indexed query and cannot be
--   mislabelled by a caller.
create table if not exists public.hr_rejections (
  id        bigserial,
  user_id   uuid not null,
  slot      int  not null,
  day       date not null,
  code      text not null,
  severity  text not null check (severity in ('incident','normal')),
  intent    text,
  n         bigint not null default 0,
  first_at  timestamptz not null default now(),
  last_at   timestamptz not null default now(),
  last_detail jsonb not null default '{}'::jsonb,
  primary key (user_id, slot, day, code)
);
create index if not exists hr_rejections_incident_idx
  on public.hr_rejections (last_at desc) where severity = 'incident';

create or replace function public.hr_record_rejection(
  p_user uuid, p_slot int, p_intent text, p_code text, p_detail jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare
  -- A rejection is an INCIDENT when it means a caller proposed something an
  -- honest game loop cannot propose. Everything else is ordinary contention or
  -- an ordinary "you cannot afford that".
  c_incident constant text[] := array[
    'gold_clamp','gem_clamp','item_clamp','xp_clamp','progress_clamp',
    'too_many_item_kinds','too_many_equip_ops','too_many_farm_ops',
    'too_many_progress_ops','unknown_item','unknown_skill','unknown_activity',
    'unknown_crop','unknown_equip_slot','unknown_delta_key','wrong_slot',
    'requirement_not_met','activity_locked','bad_progress_state','overflow',
    'seller_unavailable','forbidden_impersonation'];
  -- ESCALATING CODES (security review C2). `rate_limited` is deliberately NOT
  -- an incident on its own: one player behind a flaky connection retrying a
  -- burst will trip 240 applies/min honestly, and marking that an incident
  -- would flood hr_rejections_incident_idx — the index exists so that "show me
  -- every incident this week" is answerable, and an alert that fires for normal
  -- play is an alert nobody reads. But SUSTAINED rate limiting is the loudest
  -- automation signal the server produces, so it escalates on the DAILY
  -- counter this table already keeps: past the threshold the same row is
  -- promoted to 'incident' in place. One row per player per day either way.
  c_escalating constant text[] := array['rate_limited'];
  c_escalate_at constant bigint := 50;
begin
  if p_user is null or p_code is null then return; end if;
  insert into public.hr_rejections as r
    (user_id, slot, day, code, severity, intent, n, last_detail)
  values (p_user, coalesce(p_slot, 0), current_date, p_code,
          case when p_code = any (c_incident) then 'incident' else 'normal' end,
          left(coalesce(p_intent, ''), 64), 1,
          coalesce(p_detail, '{}'::jsonb))
  on conflict (user_id, slot, day, code) do update
    set n = r.n + 1, last_at = now(), last_detail = excluded.last_detail,
        intent = excluded.intent,
        -- Severity only ever ratchets UP, and only for a code that is on the
        -- escalating list. It is never downgraded by a later hit.
        severity = case
          when r.severity = 'incident' then 'incident'
          when p_code = any (c_escalating) and r.n + 1 >= c_escalate_at then 'incident'
          else r.severity end;
exception when others then
  -- Recording a rejection must NEVER turn a clean rejection into a 500. If the
  -- bookkeeping fails we lose one observation, not the player's request.
  null;
end $$;
revoke execute on function public.hr_record_rejection(uuid, int, text, text, jsonb)
  from public, anon, authenticated, service_role;

create or replace function public.hr_rejections_prune(p_older interval default interval '180 days')
returns int language plpgsql security definer set search_path = public as $$
declare v_n int;
begin
  delete from public.hr_rejections
   where last_at < now() - greatest(interval '30 days', coalesce(p_older, interval '180 days'));
  get diagnostics v_n = row_count;
  return v_n;
end $$;
revoke execute on function public.hr_rejections_prune(interval)
  from public, anon, authenticated, service_role;

-- ── 6c. Rate limiting ────────────────────────────────────────────────────
-- UNLOGGED on purpose: a rate counter is worth exactly zero bytes of WAL and
-- zero bytes of PITR, and losing it on a crash costs one extra allowed call.
-- One row per (user, bucket), updated in place — this does NOT grow with
-- traffic, which is the property that made it acceptable to put on hot paths.
create unlogged table if not exists public.hr_rate_counters (
  user_id      uuid not null,
  bucket       text not null,
  window_start timestamptz not null default now(),
  n            int not null default 0,
  primary key (user_id, bucket)
);

-- Returns true when the call is ALLOWED. Fixed-window, which over-permits by
-- at most 2× at a window boundary; a sliding window costs a row per call and
-- this is a spam brake, not a billing meter.
create or replace function public.hr_rate_ok(
  p_user uuid, p_bucket text, p_limit int, p_window interval)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_n int;
begin
  if p_user is null then return false; end if;
  insert into public.hr_rate_counters as rc (user_id, bucket, window_start, n)
    values (p_user, p_bucket, now(), 1)
  on conflict (user_id, bucket) do update
    set n = case when rc.window_start + p_window <= now() then 1 else rc.n + 1 end,
        window_start = case when rc.window_start + p_window <= now() then now() else rc.window_start end
  returning rc.n into v_n;
  return v_n <= greatest(1, p_limit);
end $$;
revoke execute on function public.hr_rate_ok(uuid, text, int, interval)
  from public, anon, authenticated, service_role;

-- ── 6d. The server-only PRNG secret ──────────────────────────────────────
-- Accrual rolls must be deterministic (replayable for dispute resolution) and
-- UNPREDICTABLE (a player must not be able to time a collect to land a rare
-- drop). Revision 1 seeded from hash(user_id, slot, accrued_to) — every input
-- of which hr_load hands the client, so the next roll was computable in the
-- browser. (Review S20.)
--
-- Mixing a 256-bit server secret keeps determinism and deletes predictability.
-- The secret lives in a table with RLS on, no policy, and no grant to any
-- client role — it is unreadable except through hr_seed(), which returns a
-- hash and never the secret.
--
-- sha256() and gen_random_uuid() are both core Postgres; no extension needed.
create table if not exists public.hr_server_secrets (
  name   text primary key,
  secret bytea not null,
  at     timestamptz not null default now()
);
insert into public.hr_server_secrets (name, secret)
  select 'prng', sha256(convert_to(gen_random_uuid()::text || gen_random_uuid()::text
                                   || clock_timestamp()::text, 'utf8'))
  on conflict (name) do nothing;

create or replace function public.hr_seed(p_user uuid, p_slot int, p_label text)
returns bigint language sql stable security definer set search_path = public as $$
  select (('x' || encode(substring(
            sha256((select secret from public.hr_server_secrets where name = 'prng')
                   || convert_to(coalesce(p_user::text,'') || ':' || coalesce(p_slot,0)::text
                                 || ':' || coalesce(p_label,''), 'utf8'))
            from 1 for 8), 'hex'))::bit(64))::bigint
$$;
revoke execute on function public.hr_seed(uuid, int, text)
  from public, anon, authenticated, service_role;
grant execute on function public.hr_seed(uuid, int, text) to hr_engine;

-- ── 7. RLS + GRANTS: read your own, write nothing ────────────────────────
-- Two independent locks, because one of them will eventually be edited by
-- someone who does not know about the other:
--   • RLS  — exactly one SELECT-own policy per table, nothing else.
--   • GRANT — revoke ALL from every client role, re-grant only SELECT.
--
-- Revision 1 revoked only INSERT/UPDATE/DELETE, which left TRUNCATE,
-- REFERENCES and TRIGGER in place from Supabase's default ACL (review S14),
-- and left service_role — which BYPASSES RLS — holding everything. service_role
-- keeps SELECT (dashboards, support) and loses every write: after this file the
-- ONLY writer of a player table is a SECURITY DEFINER function owned by
-- postgres.
do $$
declare t text;
begin
  foreach t in array array['player_state','player_skills','player_inventory',
                           'player_equipment','player_farm','player_progress',
                           'player_ledger','player_ledger_rollup'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || ' own read', t);
    execute format(
      'create policy %I on public.%I for select using (auth.uid() = user_id)',
      t || ' own read', t);
    execute format('revoke all on public.%I from public, anon, authenticated, service_role, hr_engine', t);
    execute format('grant select on public.%I to authenticated, service_role', t);
  end loop;

  -- player_intents and the rate counters are SERVER BOOKKEEPING. The client
  -- has no business reading either: player_intents would leak the result
  -- envelope of every recent call, and hr_rate_counters would tell an attacker
  -- exactly how much budget is left. RLS on, zero policies, zero grants.
  foreach t in array array['player_intents','hr_rate_counters','hr_server_secrets',
                           'hr_ledger_config','hr_rejections'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from public, anon, authenticated, service_role, hr_engine', t);
  end loop;

  -- The ledger's bigserial sequence is granted rwU to anon by the same default
  -- ACL. Harmless on its own; removed because "harmless on its own" is how a
  -- gap survives three reviews.
  execute 'revoke all on sequence public.player_ledger_id_seq from public, anon, authenticated, service_role, hr_engine';
  execute 'revoke all on sequence public.hr_rejections_id_seq from public, anon, authenticated, service_role, hr_engine';
end $$;

-- ── 8. Derived values, defined ONCE, server-side ─────────────────────────
-- These MUST agree with the client. The client's copies are in src/legacy.js
-- (levelFromXp at :39, xpForLevel at :50). The client keeps its copy for
-- RENDERING ONLY; this one is the authority, and the anchors below are the
-- guard.
--
-- The curve is MATERIALISED into a 99-row table rather than recomputed:
-- hr_load derives a level for all 15 skills on every read, and a recursive sum
-- per skill per read is 1,485 pointless summations. The table is DERIVED from
-- the formula in the same statement that creates it, so nobody types 99
-- numbers.
create table if not exists public.hr_xp_table (
  level int primary key check (level between 1 and 99),
  xp    bigint not null
);
insert into public.hr_xp_table (level, xp)
  select lv,
         coalesce((select floor(sum(floor(i + 300 * power(2, i / 7.0))) / 4)::bigint
                     from generate_series(1, lv - 1) i), 0)
    from generate_series(1, 99) lv
on conflict (level) do update set xp = excluded.xp;
create index if not exists hr_xp_table_xp_idx on public.hr_xp_table (xp);
alter table public.hr_xp_table enable row level security;
drop policy if exists "xp table readable" on public.hr_xp_table;
create policy "xp table readable" on public.hr_xp_table for select using (true);
revoke all on public.hr_xp_table from public, anon, authenticated, service_role, hr_engine;
grant select on public.hr_xp_table to anon, authenticated, service_role;

create or replace function public.hr_xp_for_level(p_level int)
returns bigint language sql stable set search_path = public as $$
  select coalesce((select xp from public.hr_xp_table
                    where level = greatest(1, least(99, coalesce(p_level, 1)))), 0)
$$;
revoke execute on function public.hr_xp_for_level(int) from public, anon, service_role;
grant execute on function public.hr_xp_for_level(int) to authenticated, hr_engine;

create or replace function public.hr_level_from_xp(p_xp bigint)
returns int language sql stable set search_path = public as $$
  select coalesce((select max(level) from public.hr_xp_table
                    where xp <= greatest(0, coalesce(p_xp, 0))), 1)
$$;
revoke execute on function public.hr_level_from_xp(bigint) from public, anon, service_role;
grant execute on function public.hr_level_from_xp(bigint) to authenticated, hr_engine;

-- Total level, derived. The leaderboard reads THIS, so a forged client number
-- can no longer appear on a ranking — which was the documented limitation in
-- CLAUDE.md save-invariant #6 and is now closed.
--
-- Not anon-executable: it takes an arbitrary uuid, so leaving it on PUBLIC (as
-- revision 1 did for every function it did not explicitly revoke) makes it a
-- free cross-player enumeration endpoint. (Review S7.)
create or replace function public.hr_total_level(p_user uuid, p_slot int)
returns int language sql stable security definer set search_path = public as $$
  select coalesce(sum(public.hr_level_from_xp(xp)), 0)::int
    from public.player_skills where user_id = p_user and slot = p_slot
$$;
revoke execute on function public.hr_total_level(uuid, int)
  from public, anon, authenticated, service_role;
grant execute on function public.hr_total_level(uuid, int) to hr_engine;

-- ── 9. Bootstrap: a character is created by the SERVER ───────────────────
-- The client cannot INSERT a player_state row (no policy AND no grant), so
-- character creation is an RPC. Starting kit is server-side data, not a client
-- payload. Rate-limited: creating and deleting characters in a loop is a cheap
-- way to make the database do 20 inserts per request.
create or replace function public.hr_create_character(p_slot int default 0)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_uid uuid := auth.uid();
  v_sk  text;
  c_start_skills constant text[] := array[
    'attack','strength','defense','hitpoints','prayer','magic','ranged',
    'woodcutting','mining','fishing','farming','cooking','crafting','smithing',
    'bountyHunter'];
begin
  if v_uid is null then return jsonb_build_object('ok', false, 'error', 'not_signed_in'); end if;
  if not public.hr_rate_ok(v_uid, 'create_character', 6, interval '1 hour') then
    return jsonb_build_object('ok', false, 'error', 'rate_limited');
  end if;
  if p_slot is null or p_slot < 0 or p_slot > 5 then
    return jsonb_build_object('ok', false, 'error', 'bad_slot');
  end if;
  if exists (select 1 from public.player_state where user_id = v_uid and slot = p_slot) then
    return jsonb_build_object('ok', false, 'error', 'slot_taken');
  end if;

  insert into public.player_state (user_id, slot, hp, max_hp)
    values (v_uid, p_slot, 10, 10);

  -- Hitpoints starts at level 10 like every OSRS-lineage game; everything else
  -- at 1. The number comes from the server, not from the client.
  foreach v_sk in array c_start_skills loop
    insert into public.player_skills (user_id, slot, skill_id, xp)
      values (v_uid, p_slot, v_sk,
              case when v_sk = 'hitpoints' then public.hr_xp_for_level(10) else 0 end);
  end loop;

  -- Four starting plots, empty.
  insert into public.player_farm (user_id, slot, plot_idx)
    select v_uid, p_slot, g from generate_series(0, 3) g;

  insert into public.player_ledger (user_id, slot, kind, intent, meta)
    values (v_uid, p_slot, 'admin', 'create_character',
            jsonb_build_object('slot', p_slot));

  return jsonb_build_object('ok', true, 'slot', p_slot);
end $$;
revoke execute on function public.hr_create_character(int)
  from public, anon, service_role;
grant execute on function public.hr_create_character(int) to authenticated;

-- ── 9b. SCHEDULED MAINTENANCE — the retention policy, wired ──────────────
-- THE RULE THIS ENFORCES: an append-only table's retention policy ships in the
-- migration that creates the table. Not in a runbook, not in a deploy step, not
-- in a comment saying "schedule this with…". Every unbounded table in this file
-- gets its job here; market-v2.sql does the same for its own.
--
-- The two helpers below exist so that "schedule this" is idempotent and
-- re-runnable. cron.schedule() already upserts by job name (pg_cron >= 1.4),
-- but cron.unschedule() RAISES on a name that is not there, which would make a
-- second run of any migration that removes a job fail.
create or replace function public.hr_cron_ensure(p_name text, p_schedule text, p_command text)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  select cron.schedule(p_name, p_schedule, p_command) into v_id;
  return v_id;
end $$;
revoke execute on function public.hr_cron_ensure(text, text, text)
  from public, anon, authenticated, service_role;

create or replace function public.hr_cron_drop(p_name text)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from cron.job where jobname = p_name) then return false; end if;
  perform cron.unschedule(p_name);
  return true;
end $$;
revoke execute on function public.hr_cron_drop(text)
  from public, anon, authenticated, service_role;

do $$
begin
  -- The ledger. Hourly, batched, rolls up before it deletes. Offset off the
  -- hour so it never lands on top of the leaderboard refresh.
  perform public.hr_cron_ensure('hr-ledger-prune', '7 * * * *',
    'select public.hr_ledger_prune(20000)');
  -- Idempotency keys. The dedupe window only has to outlive a client's retry
  -- budget; 24 hours is already generous. Hourly, because at 240 applies/min/
  -- player this is the fastest-growing table in the foundation.
  perform public.hr_cron_ensure('hr-intents-prune', '17 * * * *',
    'select public.hr_intents_prune()');
  -- Periodic quest/daily rows. Daily is plenty — the population only turns over
  -- once a day by construction.
  perform public.hr_cron_ensure('hr-progress-prune', '25 4 * * *',
    'select public.hr_progress_prune()');
  -- The rejection record. 180 days of security history is more than anyone will
  -- ever look back, and it is an aggregate, so it is small either way.
  perform public.hr_cron_ensure('hr-rejections-prune', '35 4 * * *',
    'select public.hr_rejections_prune()');
  raise notice 'retention jobs scheduled: ledger, intents, progress, rejections';
end $$;

-- ── 10. Self-verification ────────────────────────────────────────────────
-- Everything below is a property this file is responsible for. If a later edit
-- breaks one, the migration fails on its next run and the reviewer finds out
-- immediately rather than the players finding out first.
do $$
declare v_bad int; v_xp bigint; v_t text;
begin
  if to_regclass('public.player_state')     is null then raise exception 'player_state missing'; end if;
  if to_regclass('public.player_skills')    is null then raise exception 'player_skills missing'; end if;
  if to_regclass('public.player_inventory') is null then raise exception 'player_inventory missing'; end if;
  if to_regclass('public.player_ledger')    is null then raise exception 'player_ledger missing'; end if;
  if to_regclass('public.player_intents')   is null then raise exception 'player_intents missing'; end if;
  if (select count(*) from public.hr_xp_table) <> 99 then
    raise exception 'hr_xp_table should hold 99 rows, found %', (select count(*) from public.hr_xp_table);
  end if;

  -- (a) No client write POLICY on any player table.
  select count(*) into v_bad from pg_policies
   where schemaname = 'public'
     and tablename in ('player_state','player_skills','player_inventory',
                       'player_equipment','player_farm','player_progress','player_ledger')
     and cmd in ('INSERT','UPDATE','DELETE','ALL');
  if v_bad > 0 then
    raise exception '% client write policies on player tables — the RPCs must be the only writers', v_bad;
  end if;

  -- (b) No client write GRANT either — including TRUNCATE, which the row-level
  --     append-only trigger cannot see. (Review S14.)
  select count(*) into v_bad from information_schema.role_table_grants
   where table_schema = 'public'
     and table_name in ('player_state','player_skills','player_inventory',
                        'player_equipment','player_farm','player_progress',
                        'player_ledger','player_ledger_rollup','player_intents',
                        'hr_rate_counters','hr_server_secrets','hr_ledger_config',
                        'hr_rejections')
     and grantee in ('anon','authenticated','service_role','PUBLIC','hr_engine')
     and privilege_type <> 'SELECT';
  if v_bad > 0 then
    raise exception '% client write grants remain on player tables', v_bad;
  end if;

  -- (c) THE hr_engine ASSERTION. This is what converts "Edge Functions never
  --     write tables" from a convention into a control. If it ever fails, the
  --     architectural guarantee of the whole program has been lost. (Review S1.)
  if not exists (select 1 from pg_roles where rolname = 'hr_engine') then
    raise exception 'hr_engine role missing';
  end if;
  select count(*) into v_bad from information_schema.role_table_grants
   where table_schema = 'public' and grantee = 'hr_engine';
  if v_bad > 0 then
    raise exception 'hr_engine holds % table privileges in public — it must hold ZERO', v_bad;
  end if;
  -- ...and it must not be able to reach a player table through PUBLIC either.
  select count(*) into v_bad from information_schema.role_table_grants
   where table_schema = 'public' and grantee = 'PUBLIC';
  if v_bad > 0 then
    raise exception '% table privileges are granted to PUBLIC in schema public — hr_engine inherits them', v_bad;
  end if;
  -- (c-ii) WIDENED (review R8). role_table_grants only sees TABLE-level grants.
  --   A COLUMN-level grant — `grant update (gold) on player_state to hr_engine`
  --   — does not appear there at all, so the assertion above would have passed
  --   with the single most dangerous privilege in the database handed to the
  --   engine role. Check the column catalogue too.
  select count(*) into v_bad from information_schema.role_column_grants
   where table_schema = 'public' and grantee in ('hr_engine','PUBLIC');
  if v_bad > 0 then
    raise exception 'hr_engine (or PUBLIC) holds % COLUMN privileges in public — it must hold ZERO', v_bad;
  end if;

  -- (d) The append-only ledger really is append-only, TRUNCATE included.
  foreach v_t in array array['hr_ledger_immutable','hr_ledger_no_truncate'] loop
    if not exists (select 1 from pg_trigger
                    where tgrelid = 'public.player_ledger'::regclass
                      and tgname = v_t and not tgisinternal) then
      raise exception 'player_ledger trigger % is not attached', v_t;
    end if;
  end loop;

  -- (e) No MAINTENANCE function this file defines may be client-executable.
  --     (Review S6/S7.)
  --
  -- ⚠ hr_create_character is deliberately NOT in this list. It is the ONE
  --   function here a client may call — the bootstrap that creates the row every
  --   later intent needs — and it takes no user argument, reading auth.uid()
  --   itself, so `authenticated` is exactly the right grantee. Revision 3 listed
  --   it here anyway while granting it to `authenticated` 140 lines earlier, so
  --   this block raised on every apply and the whole foundation refused to
  --   install. It is asserted positively below instead, which says what we mean
  --   rather than the opposite of it. Found by EXECUTING the file on a branch —
  --   reading it had not caught it in three reviews.
  select count(*) into v_bad
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public'
     and p.proname in ('hr_total_level','hr_seed','hr_rate_ok',
                       'hr_intents_prune','hr_ledger_immutable','hr_ledger_prune',
                       'hr_progress_prune','hr_rejections_prune','hr_record_rejection',
                       'hr_cron_ensure','hr_cron_drop')
     and (has_function_privilege('anon', p.oid, 'execute')
       or has_function_privilege('authenticated', p.oid, 'execute'));
  if v_bad > 0 then
    raise exception '% maintenance functions in this file are client-executable', v_bad;
  end if;
  -- The bootstrap, stated positively: signed-in yes, anonymous no.
  if not has_function_privilege('authenticated', 'public.hr_create_character(int)', 'execute') then
    raise exception 'hr_create_character must be executable by authenticated — it is the bootstrap '
                    'every other intent depends on';
  end if;
  if has_function_privilege('anon', 'public.hr_create_character(int)', 'execute') then
    raise exception 'hr_create_character is reachable by anon — a signed-out caller can mint characters';
  end if;
  -- hr_cron_ensure in particular: it is `execute arbitrary SQL on a schedule,
  -- as the owner`. If a client role can ever reach it, the database is theirs.
  if has_function_privilege('authenticated', 'public.hr_cron_ensure(text,text,text)', 'execute')
  or has_function_privilege('anon', 'public.hr_cron_ensure(text,text,text)', 'execute') then
    raise exception 'hr_cron_ensure is client-callable — that is arbitrary scheduled code execution';
  end if;
  -- hr_seed must not be reachable by a player: it is the accrual PRNG.
  if has_function_privilege('authenticated', 'public.hr_seed(uuid,int,text)', 'execute') then
    raise exception 'hr_seed is player-executable — the PRNG seed would be probeable';
  end if;

  -- (f) The XP curve must match the client's XP_TABLE (src/legacy.js :39).
  v_xp := public.hr_xp_for_level(2);  if v_xp <> 83       then raise exception 'xp L2 drifted: %',  v_xp; end if;
  v_xp := public.hr_xp_for_level(10); if v_xp <> 1154     then raise exception 'xp L10 drifted: %', v_xp; end if;
  v_xp := public.hr_xp_for_level(99); if v_xp <> 13034431 then raise exception 'xp L99 drifted: %', v_xp; end if;
  if public.hr_level_from_xp(82)   <> 1  then raise exception 'level_from_xp(82) should be 1';  end if;
  if public.hr_level_from_xp(83)   <> 2  then raise exception 'level_from_xp(83) should be 2';  end if;
  if public.hr_level_from_xp(1e12::bigint) <> 99 then raise exception 'level must cap at 99';   end if;

  -- (g) The PRNG secret exists and hr_seed is deterministic but not derivable
  --     from public inputs.
  if not exists (select 1 from public.hr_server_secrets where name = 'prng') then
    raise exception 'PRNG secret missing';
  end if;
  if public.hr_seed('00000000-0000-0000-0000-000000000001'::uuid, 0, 'a')
     = public.hr_seed('00000000-0000-0000-0000-000000000001'::uuid, 0, 'b') then
    raise exception 'hr_seed does not vary with its label';
  end if;

  -- (h) RETENTION IS WIRED, not merely available. (Reliability RL2/RL3.)
  --     The failure mode this catches is the one that already happened with
  --     game_events: a prune function exists, everybody assumes it runs, and
  --     nobody notices for four days that nothing is deleting anything.
  foreach v_t in array array['hr-ledger-prune','hr-intents-prune',
                             'hr-progress-prune','hr-rejections-prune'] loop
    if not exists (select 1 from cron.job where jobname = v_t and active) then
      raise exception 'retention job % is not scheduled — this file creates an unbounded table and must wire its own prune', v_t;
    end if;
  end loop;

  -- (i) The ledger is append-only WHERE IT MATTERS and prunable where it does
  --     not. Both halves are asserted, because a change to either one silently
  --     breaks the other's justification.
  --     The whole probe runs inside a sub-block that deliberately raises at the
  --     end, so PL/pgSQL's subtransaction rollback removes every synthetic row
  --     it wrote. A self-test that leaves data behind is a data source.
  declare
    v_id bigint; v_denied boolean; v_deleted boolean;
    c_probe constant uuid := '00000000-0000-0000-0000-000000000000';
  begin
    insert into public.player_ledger (user_id, slot, kind, intent, at)
      values (c_probe, 0, 'admin', 'selftest', now() - interval '3650 days')
      returning id into v_id;

    v_denied := false;
    begin
      update public.player_ledger set gold = 1 where id = v_id;
    exception when check_violation then v_denied := true;
    end;
    if not v_denied then
      raise exception 'player_ledger accepted an UPDATE — it must never be editable';
    end if;

    -- Old enough to be outside the window: the prune MUST be able to remove it.
    delete from public.player_ledger where id = v_id;
    v_deleted := not exists (select 1 from public.player_ledger where id = v_id);
    if not v_deleted then
      raise exception 'a 10-year-old ledger row could not be deleted — retention is impossible';
    end if;

    -- ...and a fresh row must NOT be removable, or "append-only" means nothing.
    insert into public.player_ledger (user_id, slot, kind, intent)
      values (c_probe, 0, 'admin', 'selftest') returning id into v_id;
    v_denied := false;
    begin
      delete from public.player_ledger where id = v_id;
    exception when check_violation then v_denied := true;
    end;
    if not v_denied then
      raise exception 'a fresh ledger row was deletable — recent history must be untouchable';
    end if;

    raise exception using errcode = 'HR001', message = 'ledger-probe-rollback';
  exception
    when sqlstate 'HR001' then null;   -- every probe row is now undone
  end;

  raise notice 'PLAYER STATE foundation OK — tables, RLS, grants, hr_engine, XP curve, PRNG seed, retention jobs and ledger immutability verified.';
end $$;
