-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — THE SERVER DUNGEON CATALOGUE  (GENERATED — DO NOT EDIT)
--
-- ⚠⚠⚠ REVIEW ONLY — NOT AUTO-APPLIED. Applied by the Coordinator after the
--     security review, in apply order (before 2026-09-10-dungeon-settle.sql,
--     which fails closed without these tables).
--
--   Generated by tools/gen-dungeon-catalogue.mjs from src/data/dungeons.js.
--   Any hand edit is reverted by the next generation and FAILS
--   `node tools/gen-dungeon-catalogue.mjs --check` (a preflight in
--   tests/run-smoke.mjs).
--
--   dungeon-catalogue digest: 91cb2e1e18a3213717f0c769326ee10f9c96f8d239aade9c8c611fb683fd8e68
--   6 dungeons · 38 loot rows · 19 Quartermaster offers
--   loot ord = src/data/dungeons.js loot index (the settle RPC salts each roll's
--   PRNG with the ordinal -> replayable).
--
-- Read by hr_dungeon_settle (2026-09-10-dungeon-settle.sql) to credit scrip +
-- run loot, and by quartermaster_buy (2026-09-11-quartermaster-buy.sql) to price
-- + grant a Quartermaster purchase. Numbers/ids only; no client value crosses.
-- Idempotent: delete+insert inside the migration transaction.
-- ════════════════════════════════════════════════════════════════════════

-- ── hr_dungeons: per-dungeon gate + scrip base ─────────────────────────────
do $$
begin
  if to_regclass('public.hr_dungeons') is null then
    create table public.hr_dungeons (
      dungeon_id text primary key,
      kind       text   not null,
      req_lv     int    not null check (req_lv >= 1),
      cooldown_s int    not null check (cooldown_s >= 0),
      cost_key   text   not null,
      scrip_base int    not null check (scrip_base >= 1)
    );
    alter table public.hr_dungeons enable row level security;
  end if;
  if to_regclass('public.hr_dungeon_loot') is null then
    create table public.hr_dungeon_loot (
      dungeon_id text    not null references public.hr_dungeons(dungeon_id) on delete cascade,
      ord        int     not null,
      item_id    text    not null,
      qty_min    int     not null check (qty_min >= 1),
      qty_max    int     not null check (qty_max >= qty_min),
      chance     numeric not null check (chance > 0 and chance <= 1),
      bop        boolean not null,
      primary key (dungeon_id, item_id)
    );
    alter table public.hr_dungeon_loot enable row level security;
  end if;
  if to_regclass('public.hr_qm_offers') is null then
    create table public.hr_qm_offers (
      offer_id   text primary key,
      item_id    text   not null,
      scrip_cost bigint not null check (scrip_cost >= 1)
    );
    alter table public.hr_qm_offers enable row level security;
  end if;
end $$;

-- Read-only catalogues: RLS on, NO client write grant. Kept UNREADABLE by
-- clients (SELECT revoked too): the client already has these numbers (it authored
-- them — src/data/dungeons.js is what the card renders), so exposing the table is
-- a second copy of a rate with no reader. Only SECURITY DEFINER functions read it.
do $$
begin
  revoke all on public.hr_dungeons     from public, anon, authenticated, service_role;
  revoke all on public.hr_dungeon_loot from public, anon, authenticated, service_role;
  revoke all on public.hr_qm_offers    from public, anon, authenticated, service_role;
end $$;

delete from public.hr_dungeon_loot;
delete from public.hr_dungeons;
delete from public.hr_qm_offers;
insert into public.hr_dungeons (dungeon_id, kind, req_lv, cooldown_s, cost_key, scrip_base) values
  ('crypt_of_bones', 'dungeon', 25, 14400, 'bone_key', 15),
  ('goblin_warcamp', 'dungeon', 35, 21600, 'goblin_seal', 21),
  ('haunted_archive', 'dungeon', 45, 28800, 'arcane_tome', 27),
  ('obsidian_keep', 'raid', 65, 86400, 'obsidian_sigil', 39),
  ('voidbringer', 'raid', 80, 86400, 'void_fragment', 48),
  ('ancient_wyrm', 'worldboss', 95, 259200, 'dragonsbane_key', 57);
insert into public.hr_dungeon_loot (dungeon_id, ord, item_id, qty_min, qty_max, chance, bop) values
  ('crypt_of_bones', 0, 'big_bones', 10, 30, 1, false),
  ('crypt_of_bones', 1, 'grave_dust', 1, 3, 0.85, false),
  ('crypt_of_bones', 2, 'kitchen_blueprint_t2', 1, 1, 0.12, false),
  ('crypt_of_bones', 3, 'farm_deed', 1, 1, 0.2, false),
  ('goblin_warcamp', 0, 'goblin_totem', 3, 8, 1, false),
  ('goblin_warcamp', 1, 'warlord_badge', 1, 2, 0.35, false),
  ('goblin_warcamp', 2, 'forge_blueprint_t2', 1, 1, 0.15, false),
  ('goblin_warcamp', 3, 'warboss_standard', 1, 1, 0.18, false),
  ('goblin_warcamp', 4, 'wartusk_cleaver', 1, 1, 0.06, true),
  ('goblin_warcamp', 5, 'farm_deed', 1, 1, 0.22, false),
  ('haunted_archive', 0, 'magic_essence', 5, 12, 1, false),
  ('haunted_archive', 1, 'cracked_spellstone', 1, 3, 0.6, false),
  ('haunted_archive', 2, 'library_blueprint_t2', 1, 1, 0.15, false),
  ('haunted_archive', 3, 'lexarch_seal', 1, 1, 0.16, false),
  ('haunted_archive', 4, 'whispering_codex', 1, 1, 0.06, true),
  ('haunted_archive', 5, 'farm_deed', 1, 1, 0.25, false),
  ('obsidian_keep', 0, 'death_steel', 1, 3, 1, false),
  ('obsidian_keep', 1, 'kitchen_blueprint_t3', 1, 1, 0.1, false),
  ('obsidian_keep', 2, 'forge_blueprint_t3', 1, 1, 0.1, false),
  ('obsidian_keep', 3, 'trophy_blueprint_t2', 1, 1, 0.25, false),
  ('obsidian_keep', 4, 'ashcrown_greatsword', 1, 1, 0.05, true),
  ('obsidian_keep', 5, 'farm_deed', 1, 2, 0.3, false),
  ('voidbringer', 0, 'void_chitin', 1, 4, 1, false),
  ('voidbringer', 1, 'void_core', 1, 2, 0.35, false),
  ('voidbringer', 2, 'void_essence', 1, 1, 0.25, true),
  ('voidbringer', 3, 'library_blueprint_t3', 1, 1, 0.1, false),
  ('voidbringer', 4, 'riftmaw_husk', 1, 2, 0.3, false),
  ('voidbringer', 5, 'voidwoven_sigil', 1, 1, 0.14, false),
  ('voidbringer', 6, 'voidmaw_scepter', 1, 1, 0.04, true),
  ('voidbringer', 7, 'farm_deed', 1, 2, 0.32, false),
  ('ancient_wyrm', 0, 'dragon_scale', 3, 8, 1, false),
  ('ancient_wyrm', 1, 'dragon_bones', 2, 5, 1, false),
  ('ancient_wyrm', 2, 'dragon_gem', 1, 1, 0.3, false),
  ('ancient_wyrm', 3, 'dragon_relic', 1, 1, 0.15, true),
  ('ancient_wyrm', 4, 'trophy_blueprint_t3', 1, 1, 0.1, false),
  ('ancient_wyrm', 5, 'elderscale_heart', 1, 1, 0.25, false),
  ('ancient_wyrm', 6, 'dragonfang_pike', 1, 1, 0.03, true),
  ('ancient_wyrm', 7, 'farm_deed', 2, 3, 0.35, false);
insert into public.hr_qm_offers (offer_id, item_id, scrip_cost) values
  ('qm.bone_key', 'bone_key', 18),
  ('qm.goblin_seal', 'goblin_seal', 24),
  ('qm.arcane_tome', 'arcane_tome', 30),
  ('qm.obsidian_sigil', 'obsidian_sigil', 45),
  ('qm.void_fragment', 'void_fragment', 60),
  ('qm.dragonsbane_key', 'dragonsbane_key', 85),
  ('qm.kitchen_blueprint_t2', 'kitchen_blueprint_t2', 55),
  ('qm.forge_blueprint_t2', 'forge_blueprint_t2', 55),
  ('qm.library_blueprint_t2', 'library_blueprint_t2', 55),
  ('qm.trophy_blueprint_t2', 'trophy_blueprint_t2', 55),
  ('qm.kitchen_blueprint_t3', 'kitchen_blueprint_t3', 160),
  ('qm.forge_blueprint_t3', 'forge_blueprint_t3', 160),
  ('qm.library_blueprint_t3', 'library_blueprint_t3', 160),
  ('qm.trophy_blueprint_t3', 'trophy_blueprint_t3', 160),
  ('qm.wartusk_cleaver', 'wartusk_cleaver', 150),
  ('qm.whispering_codex', 'whispering_codex', 180),
  ('qm.ashcrown_greatsword', 'ashcrown_greatsword', 340),
  ('qm.voidmaw_scepter', 'voidmaw_scepter', 500),
  ('qm.dragonfang_pike', 'dragonfang_pike', 800);

-- ── Self-verification ──────────────────────────────────────────────────────
do $$
declare v_d int; v_l int; v_q int; v_bad int;
begin
  select count(*) into v_d from public.hr_dungeons;
  if v_d <> 6 then raise exception 'hr_dungeons has % rows, expected 6', v_d; end if;
  select count(*) into v_l from public.hr_dungeon_loot;
  if v_l <> 38 then raise exception 'hr_dungeon_loot has % rows, expected 38', v_l; end if;
  select count(*) into v_q from public.hr_qm_offers;
  if v_q <> 19 then raise exception 'hr_qm_offers has % rows, expected 19', v_q; end if;

  -- Every dungeon has at least one loot row and a positive scrip base.
  select count(*) into v_bad from public.hr_dungeons d
    where not exists (select 1 from public.hr_dungeon_loot l where l.dungeon_id = d.dungeon_id);
  if v_bad > 0 then raise exception '% dungeons have no loot rows', v_bad; end if;

  -- No client write policy may exist on any catalogue.
  select count(*) into v_bad from pg_policies
    where schemaname = 'public' and tablename in ('hr_dungeons','hr_dungeon_loot','hr_qm_offers')
      and cmd in ('INSERT','UPDATE','DELETE','ALL');
  if v_bad > 0 then raise exception '% write policies on the dungeon catalogue', v_bad; end if;

  -- No client grant beyond nothing (catalogues are engine-only reads).
  select count(*) into v_bad from information_schema.role_table_grants
    where table_schema = 'public' and table_name in ('hr_dungeons','hr_dungeon_loot','hr_qm_offers')
      and grantee in ('anon','authenticated','service_role','PUBLIC');
  if v_bad > 0 then raise exception '% client grants on the dungeon catalogue', v_bad; end if;
end $$;
