-- ════════════════════════════════════════════════════════════════════════
-- 2026-09-14-gem-unlock-buy.sql — hr_buy_gem_unlock: THE SERVER VERB FOR A
--                                 GEM COSMETIC, AND THE PROJECTION THAT MAKES
--                                 OWNERSHIP SOMETHING THE SERVER SAYS.
--
-- ⚠⚠⚠ REVIEW ONLY — STAGED, NOT APPLIED. The Coordinator applies this by hand
--     (node tools/apply-migration.mjs, one file). It is a MONEY SURFACE: it
--     debits the server-owned GEM balance, the game's premium currency, and it
--     grants an entitlement. Security review required before authority moves.
--
--   Companion guard:  tests/gem-unlock-buy.mjs (PGlite replay + mutation arms)
--   Companion catalogue: supabase/migrations/
--                        2026-09-14-gem-unlocks-catalogue.generated.sql
--   Client half (NOT in this file, systems-engineer's lane):
--     src/legacy.js gemUnlockServerSet() already prefers a projected set over
--     the residue; it reads `G._gemUnlocks.owned`. The reconcile that lands
--     this envelope key into that scratch field, and the rewire of
--     buyTheme()/buyCosmetic() onto this verb, ship separately.
--
-- RESTATEMENT-DEBT-ACK: hr_state_of and hr_rpc_gate are PATCHED at anchors, not
-- restated. hr_state_of is 21 anchored edits deep and 27 KB; its live body
-- exists in no file (tests/patch-chain-guard.mjs says so by name) and an agent
-- cannot read production, so a restatement authored from the repo replay would
-- blind-overwrite every other lane's edit to the envelope the whole game boots
-- from — the b484–b487 class. Both patches assert their anchor matched EXACTLY
-- ONCE, both are re-entrant (a second apply is a notice and a return), and the
-- paydown — restate each body ONCE from pg_get_functiondef of the LIVE body,
-- then re-pin live-hash-drift — stays the Coordinator's scheduled work, not
-- something this file discovers.
--
-- ⚠ AFTER APPLYING: hr_state_of AND hr_rpc_gate are LIVE-HASH-TRACKED BODIES
--   (tests/live-hash-drift.baseline.json). This file patches both, so the
--   Coordinator must re-seed with `node tests/live-hash-drift.mjs --live --write`
--   after the apply and write the whys from `--codediff`, or the next drift run
--   reports two false divergences. Agents never edit that baseline.
--
-- ── THE DEFECT THIS CLOSES (three sites, one shape, still live today) ───────
-- `ownedThemes` / `ownedCosmetics` are RESIDUE — an allowlisted bag the client
-- writes and hr_put_client_state stores verbatim (src/net/client-state.js). The
-- server has never held a theme or a cosmetic for anybody. That is the half of
-- the b371 gem dupe that made a free purchase STICK: gems are SERVER_OF_RECORD
-- and ARMED, so `G.gems -= price` is a PREDICTION the next envelope retires,
-- while the thing bought stayed in a store a cloud restore can rewind and a
-- console can forge.
--
-- src/legacy.js closed the exploit the only way a client can — it REFUSES the
-- gesture (`refuseGemPurchase`, "The realm can't record that theme yet — nothing
-- was spent"), and its own header names the missing half:
--
--     "The server half is a MIGRATION (REVIEW-ONLY, a money surface,
--      Security's call) and this file must not invent one."
--
-- This is that migration. So today a player who wants Forest Lodge is told no,
-- forever, and nine gem sinks the shop still renders are dead buttons. That is
-- also CLAUDE.md §6's 2026-09-14 rule in its purest form: the browser draws a
-- price and a Buy button, and the server has no idea the offer exists.
--
-- ── WHY NOT hr_unlock_buy (asked and answered before, so it is written down) ─
-- supabase/functions/hr-accrue/unlock-catalogue.js SELLABLE_NAMESPACES is
-- ['room','property'] and refuses `theme`/`cosmetic` BY NAME; the generated
-- 2026-08-16-unlock-offers.generated.sql agrees, carrying every theme.*/cosmetic.*
-- row with `gold = null` and `refusal = 'namespace_unsupported:<ns>'`; and
-- public.hr_unlock_offers has a GOLD column and no other. `buyUnlock('theme.forest')`
-- would answer 409 offer_unsupported forever. A gem price needs a gem verb — the
-- same conclusion 2026-09-08-hero-slot-buy.sql reached for character_slot, and
-- this file is deliberately its twin so there is one shape to review, not two.
--
-- ── WHERE THE PRICE COMES FROM (generated, not typed) ───────────────────────
-- public.hr_gem_unlocks, generated by tools/gen-catalogues.mjs from
-- src/data/shops.js SHOP_OFFERS, which tools/gen-shops.mjs derives from the
-- authored literals (`const HOUSE_THEMES=[` in src/legacy.js, `const cosmetics=[`
-- in src/render/shop.js). Three links, ONE chain, two `--check` preflights. Not
-- one number in this file is a price.
--
-- ── THE SCOPE: OWNERSHIP IS PER ACCOUNT (game-designer ruling, 2026-09-14) ──
-- An earlier draft of this file filed AND read the flag at the calling character
-- and flagged the question. The ruling settled it: OWNERSHIP IS PER ACCOUNT;
-- the EQUIPPED/active selection (houseTheme and friends) stays per character and
-- is deliberately not in this lane. "Golden Name — gold-tinted player name in
-- chat & leaderboards" was the case that decided it: a premium cosmetic bought
-- once must not have to be bought again by the same person on Hero 2.
--
-- The implementation is a READ/WRITE SPLIT, and the asymmetry is the design:
--   READ  — hr_gem_unlocks_of UNIONS the user's rows across every slot. There is
--           no slot predicate on the player_progress join, so the owned set is
--           the same answer for every character of the account.
--   WRITE — the flag is still filed at the PURCHASING slot, and so is the ledger
--           row. That keeps the journal honest about WHICH WALLET PAID (gems
--           live on player_state per (user_id, slot); a purchase filed on slot 0
--           that was paid for from slot 2 would make the ledger lie about a
--           premium-currency movement), and the union read makes it
--           account-visible with NO BACKFILL and no migration of existing rows.
--   REFUSE— `already_owned` at (6) reads the WIDENED set, which is the whole
--           point: without that, Hero 2 pays 1,200 gems for a Phoenix Pet the
--           account already owns. The guard's account-scope arm fails without
--           the widening, by construction.
--   CLAMP — the per-day ceiling at (7) was ALREADY account-wide (no slot filter
--           on the ledger read) and is unchanged.
--
-- ⚠ p_slot STAYS IN hr_gem_unlocks_of's SIGNATURE and is deliberately unused by
--   the owned-set query. It is the LEDGER/REJECTION CONTEXT — which character
--   asked — and keeping it means the projection, the verdict and the refusal all
--   call one function with one shape. Dropping the argument would be a signature
--   change to a function three callers share, for no read that wants it.
--
-- ── WHAT A FORGED CALL CAN DO: NOTHING ─────────────────────────────────────
-- The caller sends ONE TEXT, ONE INT AND A UUID: which unlock, which of its OWN
-- characters pays, and an idempotency key. There is no price, no currency, no
-- quantity, no "free" flag and no timestamp on the wire. A forged p_unlock_id
--   · not in the catalogue → `unknown_unlock`, before any lock or row read;
--   · a `free` row         → `not_for_sale` (there is NO zero-gem code path);
--   · already owned        → `already_owned`, nothing debited;
--   · priced above balance → `insufficient_gems`, quoting the server's number.
-- p_slot is clamped to 0..5 for shape and is ALWAYS the caller's own row: every
-- read and write is keyed on auth.uid(), so no value crosses a player boundary.
--
-- ── JOURNALLING: ONE ROW PER PURCHASE, NEVER PER TICK ───────────────────────
-- player_ledger gains kind='gem_unlock' (inserted at an anchor, removing
-- nothing). One row per accepted purchase — nine rows in the LIFETIME of a
-- character at the top, not a row per render. The signed gem movement rides
-- meta.gems, the same place hr_buy_hero_slot and hr_trait_buy put theirs, so the
-- three cannot be summed differently.
--
-- REVERSIBILITY
--   drop function public.hr_buy_gem_unlock(text, int, uuid);
--   drop function public.hr_buy_gem_unlock__ungated(text, int, uuid);
--   drop function public.hr_gem_unlocks_of(uuid, int);
--   -- then patch `'gem_unlocks', public.hr_gem_unlocks_of(...)` back out of
--   -- hr_state_of, and the hr_rpc_gate bucket back out. No player row is
--   -- altered by this file, no grant is widened beyond the one EXECUTE, and any
--   -- purchase already made stays owned and stays journalled.
--
-- APPLY ORDER: LAST, after 2026-09-14-gem-unlocks-catalogue.generated.sql
--   (it FAILS CLOSED without it) and after 2026-09-13-self-supply-ladder.sql.
--
-- SAFE TO RE-RUN. Every step is guarded and the §7 probes roll themselves back.
-- ════════════════════════════════════════════════════════════════════════

-- ── 0. PRECONDITIONS — FAIL CLOSED ─────────────────────────────────────────
-- Named one by one. A missing dependency must stop the apply here, where the
-- message says which file to run, rather than three sections down inside a
-- function body where it reads as a bug.
do $$
begin
  if to_regclass('public.hr_gem_unlocks') is null then
    raise exception 'hr_gem_unlocks is missing — apply '
                    '2026-09-14-gem-unlocks-catalogue.generated.sql first'; end if;
  if (select count(*) from public.hr_gem_unlocks) = 0 then
    raise exception 'hr_gem_unlocks is EMPTY — every purchase would answer unknown_unlock and the '
                    'feature would deploy green and dead'; end if;
  if to_regclass('public.hr_unlocks') is null then
    raise exception 'hr_unlocks is missing — apply 2026-08-16-unlocks.generated.sql first'; end if;
  if to_regclass('public.player_progress') is null then
    raise exception 'player_progress is missing — apply the player-state chain first'; end if;
  if to_regclass('public.player_ledger') is null then
    raise exception 'player_ledger is missing — a purchase with no journal is not a purchase'; end if;
  if to_regclass('public.player_intents') is null then
    raise exception 'player_intents is missing — there would be no idempotency store'; end if;
  if to_regprocedure('public.hr_state_of(uuid,int)') is null then
    raise exception 'hr_state_of is missing — apply the player-state chain first'; end if;
  if to_regprocedure('public.hr_rpc_gate(text)') is null then
    raise exception 'hr_rpc_gate is missing — an ungated client verb is not shippable'; end if;
  if to_regprocedure('public.hr_intent_replay(uuid,int,uuid,text)') is null then
    raise exception 'hr_intent_replay is missing — replays would double-charge'; end if;
  if to_regprocedure('public.hr_note_rejection(text,int,jsonb)') is null then
    raise exception 'hr_note_rejection is missing — a refusal nothing records is a refusal nobody '
                    'can see (tests/rejections-journal.mjs P6)'; end if;
  if to_regprocedure('public.hr_record_rejection(uuid,int,text,text,jsonb,bigint)') is null then
    raise exception 'hr_record_rejection is missing'; end if;
  -- The storage shape this file writes must be the one the catalogue polices.
  if exists (select 1 from public.hr_gem_unlocks g
              left join public.hr_unlocks u on u.unlock_id = g.unlock_id
             where u.unlock_id is null or u.progress_kind is distinct from 'flag') then
    raise exception 'a priced gem unlock has no flag-shaped hr_unlocks row — the grant would be '
                    'refused by player_progress_unlock_guard AFTER the gems were taken';
  end if;
end $$;

-- ── 1. player_ledger.kind must admit 'gem_unlock' — PROGRAMMATIC, ADDITIVE ─
-- Inserted at an anchor rather than restated (the 2026-08-23-trait-buy /
-- 2026-09-08-hero-slot-buy precedent), so it removes nothing by construction and
-- cannot silently delete a kind a later file added if it is re-applied out of
-- order.
do $$
declare v_def text; v_new text;
begin
  select pg_get_constraintdef(oid) into v_def from pg_constraint
   where conrelid = 'public.player_ledger'::regclass and conname = 'player_ledger_kind_check';
  if v_def is null then
    raise exception 'player_ledger_kind_check is absent — this verb''s journal row would be '
                    'unconstrained, and every other writer assumes the constraint exists';
  end if;
  if position('''gem_unlock''' in v_def) > 0 then
    raise notice 'player_ledger.kind already admits ''gem_unlock'' — widen skipped';
    return;
  end if;
  if position('''accrue''::text' in v_def) = 0 then
    raise exception 'player_ledger_kind_check has no ''accrue''::text anchor (%) — refusing to '
                    'rewrite a constraint whose shape this file cannot account for', v_def;
  end if;
  v_new := replace(v_def, '''accrue''::text', '''gem_unlock''::text, ''accrue''::text');
  execute 'alter table public.player_ledger drop constraint player_ledger_kind_check';
  execute 'alter table public.player_ledger add constraint player_ledger_kind_check ' || v_new;
  raise notice 'player_ledger.kind widened to admit ''gem_unlock'' (insertion, nothing removed)';
end $$;

-- ── 2. THE OWNERSHIP PREDICATE — ONE FUNCTION, THREE READERS ───────────────
-- The purchase gate, the envelope projection and the §7 probes all ask this, so
-- "do I own it" has exactly one answer in the database. Returns a SORTED array
-- of '<namespace>:<id>' strings — byte-for-byte the shape src/legacy.js
-- `ownsGemUnlock(kind, id)` already tests with `srv.indexOf(kind+':'+id) >= 0`,
-- so the client needs no translation layer and cannot drift into one.
--
-- TWO UNIONED SOURCES, and the first one is why this is not just a select:
--   FREE rows are owned by EVERYBODY. `theme:default` is the Cozy Cottage every
--     character starts with (src/legacy.js `ownedThemes:['default']`), and
--     setTheme() gates on ownsGemUnlock — so the day the client reads this set
--     server-first, a default missing from it makes the STARTING theme
--     unequippable. That is a projection causing the exact bug class it exists
--     to kill, and it would look like a bug in the client.
--   BOUGHT rows are kind='flag' player_progress rows belonging to the ACCOUNT —
--     ACROSS EVERY SLOT (game-designer ruling 2026-09-14; see the header) —
--     joined through the CATALOGUE so a mis-filed or uncatalogued row is
--     invisible as well as unbuyable.
--
-- ⚠ THE MISSING PREDICATE IS THE FEATURE. There is no `pp.slot = p_slot` here,
--   and its absence is what makes ownership account-wide. It is NOT an oversight
--   and it is NOT a widened read of somebody else's data: `pp.user_id = p_user`
--   still binds every row to the caller's own account, and p_user is derived
--   from auth.uid() by every caller. A future edit that "tightens" this by
--   adding the slot filter re-opens the double-charge the ruling exists to
--   prevent — tests/gem-unlock-buy.mjs carries that exact mutation as an arm.
--
-- `security invoker` + `stable`: it reads only tables its callers already hold
-- open, and every caller passes a uuid it has itself derived from auth.uid().
create or replace function public.hr_gem_unlocks_of(p_user uuid, p_slot int)
returns jsonb language sql stable security invoker set search_path = public as $fn$
  select coalesce(jsonb_agg(q.id order by q.id), '[]'::jsonb) from (
    select g.unlock_id as id
      from public.hr_gem_unlocks g
     where g.free
    union
    select g.unlock_id
      from public.hr_gem_unlocks g
      join public.player_progress pp
        on  pp.user_id = p_user
        and pp.kind = 'flag' and pp.period_key = ''
        and pp.key = g.unlock_id
        and pp.value > 0
  ) q
  -- p_slot is context, not a filter (see the ⚠ above). Referenced here so the
  -- argument cannot be dropped by accident and so a reader who greps for it
  -- lands on the explanation rather than concluding it was forgotten.
  where p_user is not null and coalesce(p_slot, 0) >= 0;
$fn$;
-- Takes an ARBITRARY uuid. No browser role may call it; the client receives its
-- answer through the envelope, for its own character, and never asks directly.
revoke execute on function public.hr_gem_unlocks_of(uuid, int) from public;
revoke execute on function public.hr_gem_unlocks_of(uuid, int)
  from anon, authenticated, service_role;

-- ── 3. hr_buy_gem_unlock__ungated — verify, debit, grant, journal ──────────
create or replace function public.hr_buy_gem_unlock__ungated(
  p_unlock_id text, p_slot int, p_idem uuid)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  -- BLAST RADIUS, not balance. The catalogue holds nine priced rows and each is
  -- once-per-character forever, so a character buying twelve in a day is not
  -- play whatever the catalogue grows to. Read from the APPEND-ONLY LEDGER, not
  -- from a counter this function maintains — a counter is a second source of
  -- truth that can be reset (the clan_deposit pattern).
  c_max_per_day constant int := 12;
  -- Shape bound on the wire argument, checked BEFORE any table is touched, so a
  -- client looping on a megabyte string cannot make the database hash it.
  c_max_id_len  constant int := 64;

  v_uid    uuid := auth.uid();
  v_slot   int  := coalesce(p_slot, 0);
  v_cat    public.hr_gem_unlocks%rowtype;
  v_st     public.player_state%rowtype;
  v_owned  jsonb;
  v_cached jsonb;
  v_have   bigint;
  v_today  int;
  v_intent text;
  v_result jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'error', 'not_signed_in');
  end if;
  if p_slot is null or p_slot < 0 or p_slot > 5 then
    return jsonb_build_object('ok', false, 'error', 'bad_slot', 'slot', p_slot);
  end if;
  if p_unlock_id is null or length(p_unlock_id) = 0 or length(p_unlock_id) > c_max_id_len then
    return jsonb_build_object('ok', false, 'error', 'bad_unlock_id');
  end if;

  -- ── (1) THE CATALOGUE, BEFORE ANY LOCK. A refusal that is a fact about the
  --        CATALOGUE needs no character, no lock and no row, so a client looping
  --        on a bad id cannot contend on a real player's state row.
  select * into v_cat from public.hr_gem_unlocks where unlock_id = p_unlock_id;
  if v_cat.unlock_id is null then
    perform public.hr_record_rejection(v_uid, v_slot, 'gem_unlock_buy', 'unknown_unlock',
      jsonb_build_object('unlock_id', p_unlock_id), 1);
    return jsonb_build_object('ok', false, 'error', 'unknown_unlock', 'unlock_id', p_unlock_id);
  end if;

  -- ── (2) A FREE ROW IS NOT FOR SALE. There is no zero-gem purchase path in
  --        this function AT ALL — the refusal is here, above the lock, rather
  --        than as a `if cost > 0 then debit` branch further down, because a
  --        branch that skips a debit is one edit away from being a faucet.
  if v_cat.free then
    perform public.hr_record_rejection(v_uid, v_slot, 'gem_unlock_buy', 'not_for_sale',
      jsonb_build_object('unlock_id', v_cat.unlock_id), 1);
    return jsonb_build_object('ok', false, 'error', 'not_for_sale',
      'unlock_id', v_cat.unlock_id, 'gem_unlocks', public.hr_gem_unlocks_of(v_uid, v_slot));
  end if;
  v_intent := 'gem_unlock_buy:' || v_cat.unlock_id;

  -- ── (3) SERIALISE. ONE lock, the calling character's, because BOTH the money
  --        and the entitlement live on that row (see the scope decision in the
  --        header). The key is byte-identical to the one hr_apply takes, so this
  --        also serialises against an accrual settling the same character.
  --        Transaction-scoped (safe under the transaction pooler), re-entrant.
  perform pg_advisory_xact_lock(hashtextextended(v_uid::text || ':' || v_slot::text, 0));

  -- ── (4) IDEMPOTENCY IS PER (KEY, INTENT, SLOT), NOT PER KEY. player_intents is
  --        ONE namespace for every verb in this database, so a key claimed by
  --        another intent must be REFUSED rather than answered with that
  --        intent's decision. Read INSIDE the lock so two simultaneous retries of
  --        one gesture cannot both miss the cache. ONLY SUCCESSES ARE CACHED
  --        (see (9)), so "you are 40 gems short" stays retryable.
  select public.hr_intent_replay(v_uid, v_slot, p_idem, v_intent) into v_cached;
  if v_cached ->> 'error' = 'intent_mismatch' then return v_cached; end if;
  if v_cached is not null then
    return v_cached || jsonb_build_object('replayed', true);
  end if;

  -- ── (5) THE CHARGED ROW, LOCKED. This is the wallet the topbar is showing.
  select * into v_st from public.player_state
    where user_id = v_uid and slot = v_slot for update;
  if v_st.user_id is null then
    return jsonb_build_object('ok', false, 'error', 'no_character', 'slot', v_slot);
  end if;

  -- ── (6) OWNERSHIP, FROM THE ONE PREDICATE, ACCOUNT-WIDE. Refused BEFORE the
  --        debit, which is the bug src/legacy.js buyTheme found on its own client
  --        side: the debit used to run unconditionally, so buying a theme you
  --        already owned charged you again and the only thing between the player
  --        and a second 1,000-gem Volcanic Keep was a button label.
  --        ⚠ THIS READ IS ACCOUNT-SCOPED BY THE 2026-09-14 RULING, and that is
  --          what stops Hero 2 paying 1,200 gems for a Phoenix Pet the account
  --          owns. A slot-scoped read here would be a silent double charge on
  --          the premium currency for every multi-character player.
  v_owned := public.hr_gem_unlocks_of(v_uid, v_slot);
  if v_owned @> to_jsonb(v_cat.unlock_id) then
    return jsonb_build_object('ok', false, 'error', 'already_owned',
      'unlock_id', v_cat.unlock_id, 'gem_unlocks', v_owned);
  end if;

  -- ── (7) THE PER-DAY CLAMP, from the append-only ledger, on the SERVER clock.
  select count(*) into v_today from public.player_ledger
   where user_id = v_uid and kind = 'gem_unlock'
     and at >= ((date_trunc('day', (now() at time zone 'utc'))) at time zone 'utc');
  if v_today >= c_max_per_day then
    perform public.hr_record_rejection(v_uid, v_slot, 'gem_unlock_buy', 'gem_unlock_daily_cap',
      jsonb_build_object('used', v_today, 'limit', c_max_per_day), 1);
    return jsonb_build_object('ok', false, 'error', 'gem_unlock_daily_cap',
      'used', v_today, 'limit', c_max_per_day);
  end if;

  -- ── (8) THE DEBIT AND THE GRANT, one transaction, under the lock. Every
  --        number here is read from the server's own catalogue or the server's
  --        own row; nothing on the wire priced anything. The balance cannot go
  --        negative — the check and the update are one statement apart inside a
  --        transaction holding the row lock.
  v_have := coalesce(v_st.gems, 0);
  if v_have < v_cat.cost_gems then
    perform public.hr_record_rejection(v_uid, v_slot, 'gem_unlock_buy', 'insufficient_gems',
      jsonb_build_object('unlock_id', v_cat.unlock_id, 'cost', v_cat.cost_gems, 'have', v_have), 1);
    return jsonb_build_object('ok', false, 'error', 'insufficient_gems',
      'unlock_id', v_cat.unlock_id, 'cost', v_cat.cost_gems, 'have', v_have,
      'short_by', v_cat.cost_gems - v_have);
  end if;
  update public.player_state
     set gems = gems - v_cat.cost_gems, version = version + 1, updated_at = now()
   where user_id = v_uid and slot = v_slot;
  -- ⚠ accrued_to IS NOT TOUCHED. A purchase is not an activity change, so the
  --   unpaid accrual window survives it; stamping it here would confiscate every
  --   buyer's elapsed time, silently.

  -- kind='flag', period_key='' — the shape hr_unlocks catalogues and
  -- player_progress_unlock_guard independently polices. `greatest` is written out
  -- even though (6) already refuses a re-buy: (6) is the PURCHASE decision, this
  -- is the STORAGE rule, and the two must not depend on each other.
  insert into public.player_progress as pp
    (user_id, slot, kind, key, value, period_key, state, updated_at)
  values (v_uid, v_slot, 'flag', v_cat.unlock_id, 1, '', null, now())
  on conflict (user_id, slot, kind, key, period_key)
    do update set value = greatest(pp.value, excluded.value), updated_at = now();

  -- ── (9) THE JOURNAL. ONE row per purchase. gold/gold_in/xp_in/qty_in/gems_in
  --        are ZERO and written explicitly: this transaction MINTED nothing,
  --        which is a different fact from "unstamped". player_ledger has no
  --        SIGNED gems column, so the signed movement rides meta.gems — where
  --        hr_buy_hero_slot and hr_trait_buy put theirs.
  insert into public.player_ledger
    (user_id, slot, kind, intent, gold, gold_in, xp_in, qty_in, gems_in, meta)
  values
    (v_uid, v_slot, 'gem_unlock', v_intent,
     0, 0, 0, 0, 0,
     jsonb_build_object('unlock_id', v_cat.unlock_id, 'offer_id', v_cat.offer_id,
                        'name', v_cat.name, 'currency', 'gems', 'cost', v_cat.cost_gems,
                        'gems', -v_cat.cost_gems, 'idem', p_idem));

  -- ── (10) THE ENVELOPE. The balance is RE-READ from the row rather than
  --         arithmetic on a pre-update snapshot, and `gem_unlocks` is the
  --         character's WHOLE owned set so one answer hydrates the client rather
  --         than one delta it has to merge upward (CLAUDE.md §6, 2026-09-14).
  select * into v_st from public.player_state where user_id = v_uid and slot = v_slot;
  v_result := jsonb_build_object(
    'ok', true, 'unlock_id', v_cat.unlock_id, 'offer_id', v_cat.offer_id,
    'name', v_cat.name, 'currency', 'gems', 'cost', v_cat.cost_gems,
    'gems', v_st.gems, 'version', v_st.version, 'slot', v_slot,
    'gem_unlocks', public.hr_gem_unlocks_of(v_uid, v_slot));

  -- ⚠ SUCCESSES ONLY. A cached refusal would make "not enough gems" permanent for
  --   that key; the client generates a fresh key per gesture, so a genuine retry
  --   of the SAME gesture replays this envelope and debits nothing.
  if p_idem is not null then
    insert into public.player_intents (user_id, intent_id, slot, intent, result, at)
      values (v_uid, p_idem, v_slot, v_intent, v_result, now())
      on conflict (user_id, intent_id) do nothing;
  end if;

  return v_result;
end $$;

-- ── 4. The gated wrapper ───────────────────────────────────────────────────
-- ⚠ p_slot AND p_idem CARRY DEFAULTS, AND THAT IS LOAD-BEARING. PostgREST
--   resolves an RPC by the NAMED ARGUMENTS in the POST body: a client that posts
--   {p_unlock_id} against a three-argument function with no defaults gets
--   PGRST202 "could not find the function" — a 404 indistinguishable from "the
--   migration was never applied". §7(c) asserts the defaults rather than
--   trusting this comment.
--
-- ⚠ THE hr_note_rejection SEAM IS WRITTEN HERE, NOT INHERITED.
--   2026-09-12-hr-rejections-journal.sql decorates every `<name>` /
--   `<name>__ungated` pair that existed WHEN IT RAN — it is a sweep at a point
--   in the chain, not a trigger — so a wrapper created afterwards has no seam
--   unless it carries its own, and tests/rejections-journal.mjs P6 sweeps the
--   CHAIN END and fails on a wrapper with anything other than exactly one call.
--   Exactly one, in the same shape the sweep produces.
create or replace function public.hr_buy_gem_unlock(
  p_unlock_id text, p_slot int default 0, p_idem uuid default null)
returns jsonb language plpgsql volatile security definer
set search_path = public, pg_catalog as $w$
begin
  if not public.hr_rpc_gate('hr_buy_gem_unlock') then
    return jsonb_build_object('ok', false, 'error', 'rate_limited')::jsonb;
  end if;
  return public.hr_note_rejection('hr_buy_gem_unlock', p_slot,
           public.hr_buy_gem_unlock__ungated($1, $2, $3));
end $w$;

revoke execute on function public.hr_buy_gem_unlock__ungated(text, int, uuid) from public;
revoke execute on function public.hr_buy_gem_unlock__ungated(text, int, uuid)
  from anon, authenticated, service_role;
revoke execute on function public.hr_buy_gem_unlock(text, int, uuid) from public;
revoke execute on function public.hr_buy_gem_unlock(text, int, uuid)
  from anon, authenticated, service_role;
grant  execute on function public.hr_buy_gem_unlock(text, int, uuid) to authenticated;

-- ── 5. hr_rpc_gate — PROGRAMMATIC additive patch (one bucket) ──────────────
-- The 2026-08-28-client-state.sql idiom: pg_get_functiondef + a guarded string
-- replace, so this file never restates a body it did not author and can never
-- silently delete another file's bucket. An UNKNOWN bucket fails CLOSED
-- (`else return false`), so without this the RPC would answer rate_limited
-- forever and the feature would deploy green and dead.
-- 12/min: the whole catalogue is nine rows and each is once per character.
do $$
declare v_src text; v_new text;
begin
  select pg_get_functiondef('public.hr_rpc_gate(text)'::regprocedure) into v_src;
  v_src := replace(v_src, chr(13), '');   -- CR-tolerant (CRLF working copies)
  if position('''hr_buy_gem_unlock''' in v_src) > 0 then
    raise notice 'hr_rpc_gate already admits hr_buy_gem_unlock — patch skipped'; return;
  end if;
  if (length(v_src) - length(replace(v_src, 'else return false;' || chr(10) || '  end case;', '')))
     <> length('else return false;' || chr(10) || '  end case;') then
    raise exception 'hr_rpc_gate case terminator anchor did not match exactly once — refusing to '
                    'patch blind';
  end if;
  v_new := replace(v_src,
    'else return false;' || chr(10) || '  end case;',
    'when ''hr_buy_gem_unlock'' then v_limit := 12;' || chr(10) ||
    '    else return false;' || chr(10) || '  end case;');
  execute v_new;
  raise notice 'hr_rpc_gate patched: hr_buy_gem_unlock admitted at 12/min';
end $$;
revoke execute on function public.hr_rpc_gate(text) from public;
revoke execute on function public.hr_rpc_gate(text) from anon, authenticated, service_role;

-- ── 6. hr_state_of — PROJECT the owned set (programmatic, additive) ────────
-- WHY THE ENVELOPE AND NOT A SECOND RPC: ownership must survive a device change
-- and a cloud restore, and the client's only load path for it today is the
-- RESIDUE — the store a restore can rewind while the entitlement it paid for
-- stays granted, which is the b371 dupe. One additive top-level `gem_unlocks`
-- array means the boot envelope already carries it, with no extra round trip and
-- nothing second to keep in step.
--
-- ⚠ ACCOUNT-SCOPED, like `hero_slots` beside it (game-designer ruling
--   2026-09-14). `v_st.slot` is passed as CONTEXT only — hr_gem_unlocks_of does
--   not filter on it — so every character of an account projects the same owned
--   set, which is what makes a theme bought on Hero 1 appear on Hero 2 with no
--   backfill. The EQUIPPED selection stays per character and is not in this
--   lane.
--
-- ⚠ READ UNFILTERED, exactly as `traits` and `hero_slots` are, and for the same
--   stated reason: the generic `progress` array is LIMIT 1000, and a projection
--   that truncates is a projection that can silently answer "you own nothing"
--   about something a player paid gems for.
--
-- Patched at the `total_level` anchor — the anchor
-- 2026-08-22-companion-record.sql, 2026-08-23-trait-buy.sql,
-- 2026-09-08-hero-slot-buy.sql and 2026-09-12-renown-high-projection.sql all
-- use, which survives insertion because each appends AFTER the anchor text.
-- NO-OP on re-apply.
do $$
declare
  v_def text;
  c_anchor constant text := $anc$'total_level', public.hr_total_level(p_user, v_st.slot),$anc$;
begin
  v_def := replace(pg_get_functiondef('public.hr_state_of(uuid,int)'::regprocedure), chr(13), '');
  if strpos(v_def, $q$'gem_unlocks', public.hr_gem_unlocks_of$q$) > 0 then
    raise notice 'hr_state_of already projects gem_unlocks — patch skipped'; return; end if;
  if (length(v_def) - length(replace(v_def, c_anchor, ''))) <> length(c_anchor) then
    raise exception 'the LIVE hr_state_of total_level anchor did not match exactly once — its shape '
                    'is not the one this file was derived against. Do NOT patch a body you cannot '
                    'account for.';
  end if;
  v_def := replace(v_def, c_anchor, c_anchor || $new$
    -- gem-unlock-buy (2026-09-14): the themes and cosmetics this ACCOUNT owns,
    -- as a flat array of '<namespace>:<id>'. Written only by hr_buy_gem_unlock
    -- (there is no client write policy and no client write grant on
    -- player_progress), read by src/legacy.js ownsGemUnlock so ownership stops
    -- living in the residue a cloud restore can rewind — the half of the b371
    -- gem dupe that made a free theme STICK. Always contains the FREE rows
    -- (theme:default), so the starting theme stays equippable the moment the
    -- client reads this set server-first. Never truncated: an entitlement must
    -- not be able to read as "you own nothing".
    'gem_unlocks', public.hr_gem_unlocks_of(p_user, v_st.slot),$new$);
  execute v_def;
  raise notice 'hr_state_of patched: the envelope projects the character''s owned gem unlocks';
end $$;
-- create-or-replace preserves an ACL; be explicit anyway. hr_state_of takes an
-- ARBITRARY uuid — no client may call it.
revoke execute on function public.hr_state_of(uuid, int)
  from public, anon, authenticated, service_role;
grant  execute on function public.hr_state_of(uuid, int) to hr_engine;

-- ── 6b. Grant-hygiene baseline (if present) ────────────────────────────────
do $$
begin
  if to_regclass('public.hr_client_rpc_baseline') is null then
    raise notice 'hr_client_rpc_baseline absent — grant-hygiene not applied; nothing to update';
    return;
  end if;
  delete from public.hr_client_rpc_baseline
   where proname = 'hr_buy_gem_unlock' and grantee = 'authenticated';
  insert into public.hr_client_rpc_baseline (proname, identity_args, grantee, note) values
    ('hr_buy_gem_unlock', 'p_unlock_id text, p_slot integer, p_idem uuid', 'authenticated',
     'added 2026-09-14: server-authoritative theme/cosmetic purchase (gem debit on the calling '
     'character + a kind=''flag'' <namespace>:<id> grant on the same row). The price comes from '
     'public.hr_gem_unlocks, generated from src/data/shops.js; the caller sends an id, one of its '
     'own slots and an idempotency key and nothing else. Free rows are refused not_for_sale.');
end $$;

-- ── 7. SELF-VERIFYING COMMIT GATE (§4) ─────────────────────────────────────
-- Proves the load-bearing properties by EXECUTING them, not by matching markers.
-- The apply is atomic, so a raise here reverts every section above it. The
-- row-writing probes live in a subtransaction discarded by a sentinel raise
-- (HR842), so this block is NET-ZERO on production — asserted, not asserted
-- about, by the leak check at the end.
do $$
declare
  v_uid   constant uuid := '00000000-0000-4000-8000-0000b5460001';
  v_n     int;
  v_bad   text;
  v_r     jsonb;
  v_env   jsonb;
  v_gems0 bigint;
  v_cost  bigint;
  v_id    text;
  v_free  text;
begin
  -- (a) THE CATALOGUE IS THE ONLY PRICE. No literal gem number may appear in the
  --     verb's own EXECUTABLE body: that is what makes "the price is generated" a
  --     property rather than a habit. The body may hold small integers (slot
  --     bounds, the daily clamp, the id length) — the assertion is specifically
  --     that nothing reads like a PRICE, i.e. no three-or-more-digit literal.
  --     ⚠ COMMENTS ARE STRIPPED FIRST, and that is not a softening: the prose in
  --       this verb cites "the 1,000-gem Volcanic Keep" and the b371 incident, and
  --       an assertion that a comment cannot mention a number would be paid for by
  --       deleting the explanation instead of the defect. `--` to end of line;
  --       no string literal in this body contains a double hyphen.
  select regexp_replace(p.prosrc, '--[^' || chr(10) || ']*', '', 'g') into v_bad
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'hr_buy_gem_unlock__ungated';
  if v_bad is null then raise exception 'GATE(a): hr_buy_gem_unlock__ungated is missing'; end if;
  if v_bad ~ '[^0-9a-zA-Z_]\d{3,}' then
    raise exception 'GATE(a): hr_buy_gem_unlock__ungated contains a 3+ digit literal outside a '
                    'comment — a price typed into the verb is a second copy of a money number';
  end if;
  if position('hr_gem_unlocks' in v_bad) = 0 then
    raise exception 'GATE(a): the verb does not read public.hr_gem_unlocks at all';
  end if;

  -- (b) THE PROJECTION IS TOP-LEVEL AND IT IS THIS FUNCTION'S ANSWER. Not "the
  --     body mentions gem_unlocks" — the exact spliced expression, because a key
  --     projected inside `state`, or filled from a different source, is the
  --     shipped bug under a new name (tests/renown-projection.mjs R2's lesson).
  select p.prosrc into v_bad from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'hr_state_of';
  if position($q$'gem_unlocks', public.hr_gem_unlocks_of(p_user, v_st.slot)$q$ in v_bad) = 0 then
    raise exception 'GATE(b): hr_state_of does not project gem_unlocks from hr_gem_unlocks_of';
  end if;
  -- AND THE NEIGHBOURS SURVIVED. This body is 21 anchored edits deep; the way
  -- this file could hurt somebody is by dropping one of them.
  if position($q$'renown_high'$q$ in v_bad) = 0
     or position($q$'hero_slots'$q$ in v_bad) = 0
     or position($q$'traits'$q$ in v_bad) = 0
     or position($q$'inventory_complete'$q$ in v_bad) = 0 then
    raise exception 'GATE(b): a pre-existing hr_state_of projection was LOST by this splice';
  end if;

  -- (c) THE CLIENT SURFACE. The wrapper is callable by `authenticated`, the
  --     ungated twin and the predicate are callable by NOBODY, and the wrapper
  --     carries defaults so PostgREST can resolve a one-argument POST.
  if not has_function_privilege('authenticated', 'public.hr_buy_gem_unlock(text,int,uuid)', 'execute') then
    raise exception 'GATE(c): hr_buy_gem_unlock is not callable by authenticated — a dead button';
  end if;
  if has_function_privilege('authenticated', 'public.hr_buy_gem_unlock__ungated(text,int,uuid)', 'execute')
     or has_function_privilege('anon', 'public.hr_buy_gem_unlock__ungated(text,int,uuid)', 'execute')
     or has_function_privilege('service_role', 'public.hr_buy_gem_unlock__ungated(text,int,uuid)', 'execute') then
    raise exception 'GATE(c): the UNGATED verb is client-executable — the rate gate is bypassable';
  end if;
  if has_function_privilege('anon', 'public.hr_buy_gem_unlock(text,int,uuid)', 'execute') then
    raise exception 'GATE(c): anon may buy a cosmetic';
  end if;
  if has_function_privilege('authenticated', 'public.hr_gem_unlocks_of(uuid,int)', 'execute')
     or has_function_privilege('anon', 'public.hr_gem_unlocks_of(uuid,int)', 'execute') then
    raise exception 'GATE(c): hr_gem_unlocks_of is client-executable — it takes an ARBITRARY uuid';
  end if;
  select count(*) into v_n from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'hr_buy_gem_unlock' and p.pronargdefaults = 2;
  if v_n <> 1 then
    raise exception 'GATE(c): hr_buy_gem_unlock does not carry two argument defaults — PostgREST '
                    'would answer PGRST202 to a {p_unlock_id} post, a 404 nobody can tell from an '
                    'unapplied migration';
  end if;
  -- THE SEAM (tests/rejections-journal.mjs P6). Exactly one, in the wrapper.
  select (select count(*) from regexp_matches(p.prosrc, 'hr_note_rejection\(', 'g')) into v_n
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'hr_buy_gem_unlock';
  if v_n <> 1 then
    raise exception 'GATE(c): the wrapper carries % hr_note_rejection calls (need exactly 1) — a '
                    'refusal nothing records is a refusal nobody can see', v_n;
  end if;

  -- (d) THE CATALOGUE IS NOT REACHABLE FROM A BROWSER, restated here because the
  --     generated file and this one can be applied minutes apart and only this
  --     one hands out an EXECUTE.
  select coalesce(string_agg(distinct grantee, ', '), '') into v_bad
    from information_schema.role_table_grants
   where table_schema = 'public' and table_name = 'hr_gem_unlocks'
     and grantee in ('anon', 'authenticated', 'service_role', 'PUBLIC');
  if v_bad <> '' then raise exception 'GATE(d): hr_gem_unlocks is reachable by %', v_bad; end if;
  select count(*) into v_n from pg_policies
   where schemaname = 'public' and tablename = 'player_progress'
     and cmd in ('INSERT','UPDATE','DELETE','ALL');
  if v_n > 0 then
    raise exception 'GATE(d): player_progress has % client write policies — the entitlement this '
                    'verb sells could be written by the browser that buys it', v_n;
  end if;

  -- (e) EXECUTED, END TO END, on a synthetic account inside a discarded
  --     subtransaction. Everything above this is text and catalogue; this is the
  --     only part that proves gems actually move and only once.
  if to_regprocedure('public.hr_create_character(int)') is null then
    raise exception 'GATE(e) CANNOT RUN: hr_create_character missing';
  end if;
  select unlock_id, cost_gems into v_id, v_cost
    from public.hr_gem_unlocks where not free order by cost_gems limit 1;
  select unlock_id into v_free from public.hr_gem_unlocks where free order by unlock_id limit 1;
  if v_id is null or v_free is null then
    raise exception 'GATE(e) CANNOT RUN: the catalogue has no priced row and/or no free row (%/%)',
      v_id, v_free;
  end if;
  begin  -- ── SUBTRANSACTION ────────────────────────────────────────────────
    insert into auth.users (id) values (v_uid);
    perform set_config('request.jwt.claim.sub', v_uid::text, true);
    v_r := public.hr_create_character(0);
    if v_r->>'created' <> 'true' then
      raise exception 'GATE(e): no probe character: %', v_r; end if;

    -- (e1) THE FREE ROW IS ALREADY OWNED AND IS NOT FOR SALE. Both halves: a
    --      fresh character owns theme:default without paying, and asking to buy
    --      it is refused rather than sold for nothing.
    v_env := public.hr_state_of(v_uid, 0);
    if not ((v_env->'gem_unlocks') @> to_jsonb(v_free)) then
      raise exception 'GATE(e1): a fresh character does not own the FREE % — the starting theme '
                      'would be unequippable the moment the client reads ownership server-first',
                      v_free;
    end if;
    if (v_env->'gem_unlocks') @> to_jsonb(v_id) then
      raise exception 'GATE(e1): a fresh character already owns the PRICED % — the projection is '
                      'not reading ownership at all', v_id;
    end if;
    v_r := public.hr_buy_gem_unlock__ungated(v_free, 0, gen_random_uuid());
    if v_r->>'error' is distinct from 'not_for_sale' then
      raise exception 'GATE(e1): buying the free row answered % — it must be not_for_sale, or a '
                      '0-gem purchase path exists', v_r;
    end if;

    -- (e2) NO GEMS, NO PURCHASE. Run BEFORE any gems are granted, so the refusal
    --      is the shipped default rather than something this probe arranged.
    select coalesce(gems, 0) into v_gems0 from public.player_state
     where user_id = v_uid and slot = 0;
    if v_gems0 >= v_cost then
      raise exception 'GATE(e2) CANNOT RUN: a new character starts with % gems, which is enough '
                      'for the cheapest offer (%) — this probe proves nothing', v_gems0, v_cost;
    end if;
    v_r := public.hr_buy_gem_unlock__ungated(v_id, 0, gen_random_uuid());
    if v_r->>'error' is distinct from 'insufficient_gems' then
      raise exception 'GATE(e2): a broke character was answered % buying % — it must be '
                      'insufficient_gems', v_r, v_id;
    end if;
    if (public.hr_gem_unlocks_of(v_uid, 0)) @> to_jsonb(v_id) then
      raise exception 'GATE(e2): the REFUSED purchase granted the unlock anyway';
    end if;

    -- (e3) THE HAPPY PATH. Gems are placed on the row directly (this is a
    --      synthetic probe, not a player — no faucet is exercised), then the
    --      purchase must debit EXACTLY the catalogue price, grant the flag, and
    --      show up on the envelope.
    update public.player_state set gems = v_cost + 1
     where user_id = v_uid and slot = 0;
    v_r := public.hr_buy_gem_unlock__ungated(v_id, 0, '00000000-0000-4000-8000-0000b5460aa1');
    if coalesce(v_r->>'ok','false') <> 'true' then
      raise exception 'GATE(e3): a funded purchase of % was refused: %', v_id, v_r;
    end if;
    if (v_r->>'gems')::bigint <> 1 then
      raise exception 'GATE(e3): the debit left % gems, expected 1 (cost %) — the price charged is '
                      'not the catalogue price', v_r->>'gems', v_cost;
    end if;
    if not ((v_r->'gem_unlocks') @> to_jsonb(v_id)) then
      raise exception 'GATE(e3): the verb''s own answer does not carry the thing just bought';
    end if;
    if not exists (select 1 from public.player_progress
                    where user_id = v_uid and slot = 0 and kind = 'flag'
                      and key = v_id and period_key = '' and value > 0) then
      raise exception 'GATE(e3): no flag row was written — the gems went nowhere';
    end if;
    -- THE ENVELOPE AND THE VERDICT MUST AGREE. A projection the purchase path
    -- does not honour is worse than no projection: the player would see it owned
    -- and be refused on use (tests/renown-projection.mjs R3's rule).
    v_env := public.hr_state_of(v_uid, 0);
    if (v_env->'gem_unlocks') is distinct from (v_r->'gem_unlocks') then
      raise exception 'GATE(e3): hr_state_of (%) and the purchase verdict (%) disagree about the '
                      'owned set', v_env->'gem_unlocks', v_r->'gem_unlocks';
    end if;
    -- ONE journal row, carrying the SIGNED movement.
    select count(*) into v_n from public.player_ledger
     where user_id = v_uid and kind = 'gem_unlock';
    if v_n <> 1 then raise exception 'GATE(e3): % ledger rows for one purchase', v_n; end if;
    if (select (meta->>'gems')::bigint from public.player_ledger
         where user_id = v_uid and kind = 'gem_unlock' limit 1) <> -v_cost then
      raise exception 'GATE(e3): the journal does not record the signed gem movement';
    end if;

    -- (e4) THE REPLAY. The SAME idempotency key must answer the SAME envelope
    --      and debit nothing — this is the property a retrying client depends on
    --      and the one a double-tap would otherwise break.
    v_r := public.hr_buy_gem_unlock__ungated(v_id, 0, '00000000-0000-4000-8000-0000b5460aa1');
    if coalesce(v_r->>'replayed','false') <> 'true' then
      raise exception 'GATE(e4): the replayed key was not answered from the cache: %', v_r;
    end if;
    if (select gems from public.player_state where user_id = v_uid and slot = 0) <> 1 then
      raise exception 'GATE(e4): the replay MOVED GEMS — a retry charges twice';
    end if;

    -- (e5) AND A FRESH KEY ON AN OWNED UNLOCK IS already_owned, NOT a second
    --      sale. The idempotency cache is not what protects the balance here.
    v_r := public.hr_buy_gem_unlock__ungated(v_id, 0, gen_random_uuid());
    if v_r->>'error' is distinct from 'already_owned' then
      raise exception 'GATE(e5): re-buying an owned unlock with a fresh key answered % — it must '
                      'be already_owned', v_r;
    end if;
    if (select gems from public.player_state where user_id = v_uid and slot = 0) <> 1 then
      raise exception 'GATE(e5): re-buying an owned unlock CHARGED AGAIN';
    end if;

    -- (e6) A FORGED ID BUYS NOTHING AND COSTS NOTHING.
    v_r := public.hr_buy_gem_unlock__ungated('theme:free_money', 0, gen_random_uuid());
    if v_r->>'error' is distinct from 'unknown_unlock' then
      raise exception 'GATE(e6): an uncatalogued id answered %', v_r;
    end if;
    if (select gems from public.player_state where user_id = v_uid and slot = 0) <> 1 then
      raise exception 'GATE(e6): an uncatalogued id MOVED GEMS';
    end if;

    -- (e7) THE RULING, EXECUTED: OWNERSHIP IS PER ACCOUNT. A SECOND character of
    --      the same account must SEE the unlock slot 0 bought and must be
    --      REFUSED a second purchase of it — otherwise every multi-character
    --      player pays the premium price once per hero. The hero slot is granted
    --      through the real entitlement flag rather than by forging a row, so
    --      hr_create_character's own gate is exercised rather than bypassed.
    insert into public.player_progress
      (user_id, slot, kind, key, value, period_key, updated_at)
    values (v_uid, 0, 'flag', 'character_slot:1', 1, '', now())
    on conflict (user_id, slot, kind, key, period_key) do update set value = 1;
    v_r := public.hr_create_character(1);
    if v_r->>'created' <> 'true' then
      raise exception 'GATE(e7) CANNOT RUN: the second character was refused (%) — the account '
                      'entitlement flag did not take', v_r;
    end if;
    if not ((public.hr_gem_unlocks_of(v_uid, 1)) @> to_jsonb(v_id)) then
      raise exception 'GATE(e7): hero 2 does not own the % hero 1 bought (%) — ownership is per '
                      'ACCOUNT (game-designer ruling 2026-09-14) and this read is slot-scoped',
                      v_id, public.hr_gem_unlocks_of(v_uid, 1);
    end if;
    if not (((public.hr_state_of(v_uid, 1))->'gem_unlocks') @> to_jsonb(v_id)) then
      raise exception 'GATE(e7): hero 2''s ENVELOPE does not carry the account''s unlock';
    end if;
    update public.player_state set gems = 999999 where user_id = v_uid and slot = 1;
    v_r := public.hr_buy_gem_unlock__ungated(v_id, 1, gen_random_uuid());
    if v_r->>'error' is distinct from 'already_owned' then
      raise exception 'GATE(e7): hero 2 buying the account''s own % answered % — it must be '
                      'already_owned, or the premium price is charged once per character', v_id, v_r;
    end if;
    if (select gems from public.player_state where user_id = v_uid and slot = 1) <> 999999 then
      raise exception 'GATE(e7): hero 2 WAS CHARGED for an unlock the account already owns';
    end if;
    -- AND THE WRITE STAYED WHERE THE MONEY CAME FROM: exactly one flag row, on
    -- the purchasing slot, so the journal still says which wallet paid.
    if (select count(*) from public.player_progress
         where user_id = v_uid and kind = 'flag' and key = v_id) <> 1 then
      raise exception 'GATE(e7): the account-wide READ was implemented as a per-slot WRITE — the '
                      'flag was duplicated across characters';
    end if;
    if not exists (select 1 from public.player_progress
                    where user_id = v_uid and slot = 0 and kind = 'flag' and key = v_id) then
      raise exception 'GATE(e7): the flag is not on the PURCHASING slot';
    end if;

    raise exception using errcode = 'HR842',
      message = 'gem-unlock-buy §7 complete — rolling back';
  exception when sqlstate 'HR842' then null;
  end;

  perform set_config('request.jwt.claim.sub', '', true);

  -- ROLLBACK PROOF. Without this the file seeds a character into production as a
  -- side effect of verifying itself, which CLAUDE.md §2 forbids outright.
  -- TWO characters were created above (e7 buys a hero slot), so the kit tables
  -- are named here too: hr_create_character seeds inventory and equipment, and a
  -- leak check that does not look at them would pass while two starting kits sat
  -- in production.
  if exists (select 1 from public.player_state     where user_id = v_uid)
     or exists (select 1 from public.player_skills    where user_id = v_uid)
     or exists (select 1 from public.player_inventory where user_id = v_uid)
     or exists (select 1 from public.player_equipment where user_id = v_uid)
     or exists (select 1 from public.player_progress  where user_id = v_uid)
     or exists (select 1 from public.player_ledger    where user_id = v_uid)
     or exists (select 1 from public.player_intents   where user_id = v_uid)
     or exists (select 1 from auth.users             where id = v_uid) then
    raise exception 'GATE: §7 LEAKED a probe row';
  end if;

  raise notice 'gem-unlock-buy: the price comes only from hr_gem_unlocks, hr_state_of projects the '
               'owned set top-level beside its 21 neighbours, the ungated verb and the predicate '
               'are callable by nobody, the wrapper is gated + seamed + defaulted, and EXECUTED: '
               'the free theme is owned and unsellable, a broke character is refused, a funded one '
               'pays exactly the catalogue price once, the replay and the re-buy both charge '
               'nothing, a forged id buys nothing, and a SECOND character of the account both sees '
               'the unlock and is refused a second purchase of it while the flag stays on the '
               'purchasing slot — all green, net zero';
end $$;
