-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — THE BOUNTY MONSTER→TIER CATALOGUE  (GENERATED — DO NOT EDIT)
--
--   Generated by tools/gen-bounty-monsters.mjs from src/data/monsters.js.
--   Any hand edit is reverted by the next generation and FAILS
--   `node tools/gen-bounty-monsters.mjs --check` (a preflight in run-smoke).
--
--   monster digest: 98de10a724fb83672f75c5c6f33963dc4442896fd9f29f949a4f54e735b4becb
--   108 monsters
--
-- Read by hr_accept_bounty (2026-08-23-bounty.sql) to derive the bounty's tier
-- server-side. Ids + tier only — no game number beyond tier. Idempotent: a
-- truncate+insert inside the migration transaction, so a re-apply is a no-op.
-- ════════════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.hr_bounty_monsters') is null then
    create table public.hr_bounty_monsters (
      monster_id text primary key,
      tier       int  not null check (tier between 1 and 6),
      hp         int  not null default 1 check (hp >= 1)
    );
    alter table public.hr_bounty_monsters enable row level security;
  end if;
end $$;

-- ADDITIVE: databases that ran the pre-2026-08-30 catalogue have no hp column.
-- Add it before the truncate+insert so the re-seed below can fill it.
alter table public.hr_bounty_monsters add column if not exists hp int not null default 1;
do $$ begin
  alter table public.hr_bounty_monsters add constraint hr_bounty_monsters_hp_chk check (hp >= 1);
exception when duplicate_object then null; end $$;

-- Read-only catalogue: readable by everyone signed in, written by NO client.
drop policy if exists hr_bounty_monsters_sel on public.hr_bounty_monsters;
create policy hr_bounty_monsters_sel on public.hr_bounty_monsters for select using (true);
revoke all on public.hr_bounty_monsters from anon, authenticated, service_role;
grant select on public.hr_bounty_monsters to anon, authenticated, service_role;

truncate table public.hr_bounty_monsters;
insert into public.hr_bounty_monsters (monster_id, tier, hp) values
  ('adept', 4, 106),
  ('air_elemental', 2, 24),
  ('ancient_bear', 6, 460),
  ('archmage', 5, 215),
  ('ashwing', 6, 472),
  ('astrologer', 5, 196),
  ('bandit_lord', 5, 212),
  ('barrow_knight', 4, 148),
  ('bear', 4, 140),
  ('bog_vine', 3, 70),
  ('broodmother', 6, 402),
  ('carnivorous_plant', 4, 138),
  ('carrion_swarm', 5, 198),
  ('cave_wyrm', 4, 158),
  ('centipede', 3, 60),
  ('chained_demon', 5, 240),
  ('clay_golem', 3, 78),
  ('conjurer', 4, 110),
  ('cutpurse', 1, 11),
  ('cyclops', 5, 256),
  ('dark_wizard', 2, 28),
  ('death_knight', 5, 260),
  ('deserter', 3, 57),
  ('dire_wolf', 3, 62),
  ('draconia', 6, 484),
  ('dragon', 6, 520),
  ('drake', 5, 234),
  ('drowned_dead', 4, 130),
  ('dryad', 5, 222),
  ('earth_elemental', 3, 74),
  ('elder_cinder', 6, 440),
  ('elk_king', 6, 466),
  ('fire_devil', 3, 56),
  ('fire_elemental', 1, 12),
  ('frost_giant', 5, 248),
  ('fury', 5, 202),
  ('gargoyle', 5, 254),
  ('ghoul', 3, 52),
  ('giant_bat', 2, 24),
  ('giant_boar', 5, 252),
  ('giant_spider', 4, 118),
  ('gnoll', 2, 31),
  ('goblin', 1, 15),
  ('goblin_brute', 3, 68),
  ('goblin_warlord', 4, 125),
  ('grave_banshee', 5, 194),
  ('grim_reaper', 6, 388),
  ('hellhound', 4, 122),
  ('hive_wasp', 1, 8),
  ('hobgoblin', 2, 34),
  ('ice_elemental', 4, 128),
  ('imp', 1, 10),
  ('iron_colossus', 6, 518),
  ('kobold', 1, 12),
  ('lesser_demon', 4, 150),
  ('lich', 6, 350),
  ('locust_swarm', 2, 25),
  ('lynx', 3, 55),
  ('magma_elemental', 5, 226),
  ('mammoth', 5, 258),
  ('mandrake', 1, 11),
  ('minotaur', 4, 145),
  ('mountain_ram', 3, 66),
  ('mountain_troll', 4, 165),
  ('necromancer', 6, 356),
  ('nightmare', 2, 28),
  ('ogre', 4, 160),
  ('ooze', 2, 33),
  ('panther', 5, 205),
  ('plague_swarm', 4, 100),
  ('rat', 1, 9),
  ('revenant', 6, 448),
  ('rock_troll', 3, 72),
  ('salamander', 2, 27),
  ('scarecrow', 1, 16),
  ('shadow_creeper', 5, 190),
  ('shrieker', 2, 29),
  ('skeleton', 2, 35),
  ('slime', 1, 8),
  ('small_wolf', 1, 16),
  ('stag', 2, 26),
  ('starhusk', 5, 208),
  ('stone_golem', 2, 35),
  ('stonejaw', 6, 478),
  ('storm_elemental', 6, 392),
  ('the_silence', 6, 364),
  ('the_unlit', 6, 508),
  ('treant', 6, 512),
  ('vampire_bride', 6, 372),
  ('venom_spider', 3, 52),
  ('vharek', 6, 496),
  ('void_mote', 4, 104),
  ('void_parasite', 6, 340),
  ('war_king', 6, 420),
  ('warband_captain', 5, 230),
  ('warlock', 3, 58),
  ('watchknight', 4, 164),
  ('water_elemental', 2, 30),
  ('weak_skeleton', 1, 14),
  ('wight', 2, 30),
  ('wild_boar', 1, 13),
  ('winter_wolf', 4, 132),
  ('witchs_apprentice', 1, 10),
  ('wolf', 2, 30),
  ('wraith', 4, 112),
  ('wyrmling', 3, 61),
  ('wyvern', 4, 135),
  ('zombie', 3, 78);

do $$
declare v_n int;
begin
  select count(*) into v_n from public.hr_bounty_monsters;
  if v_n <> 108 then
    raise exception 'hr_bounty_monsters has % rows, expected 108', v_n;
  end if;
end $$;
