-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — hr_companion_grant HARDENING (Security conditions C1 · C2 · C3)
--   ✅ APPLIED TO PRODUCTION 2026-08-31 (dry-run begin/rollback 201 → commit
--     201 via the Management API; post-apply body pin 0d0c7310b9573968916d3254
--     cacd9df1, recorded in tests/live-hash-drift.baseline.json — the guard's
--     baseline, not this prose, is the deployment record). REVIEW-ONLY file:
--     nothing is applied by writing it; re-apply is safe (§0's already-hardened
--     fork).
--
--   Same-build follow-up to 2026-09-05-companion-unlock-catalogue-reseed.sql
--   (APPLIED to production 2026-08-30; hr_unlocks 82 total / 21 companion,
--   live-verified). The reseed ARMED an already-live client-callable RPC. These
--   are the three conditions Security attached to that arm, authored as ONE
--   migration and DELIBERATELY separate from the reseed so that a data seed and
--   a behaviour change are never reverted or re-applied as one unit.
--
-- ── THE THREE CONDITIONS ────────────────────────────────────────────────
-- C1  TRANSLATE THE STORAGE-GUARD REFUSAL INTO A MACHINE CODE.
--     hr_companion_grant had no exception handler. When a `companion:<id>` row
--     is missing from public.hr_unlocks — the b453 destruction class, and the
--     exact state production sat in from 2026-08-23 to 2026-08-30 — the BEFORE
--     INSERT trigger player_progress_unlock_guard raises
--       23514 / 'unknown_unlock: companion:<id>'
--     which PostgREST returns as a 500. A 500 is indistinguishable from "the
--     server is down": the client cannot tell a REFUSAL from an OUTAGE, cannot
--     journal it, and cannot show the player anything true. The verb's other
--     refusals are machine codes recorded in hr_rejections; this one was not.
--     Now: `{ok:false, error:'unknown_unlock:companion:<id>'}` + an
--     hr_rejections row, in TWO layers (see §1 THE SHAPE OF C1).
--
-- C2  THE `whelp` req_item WAS A FAKE CONTROL.
--     The body read player_inventory for dragon_egg, set v_egg true/false, and
--     then granted UNCONDITIONALLY either way. Security's ruling: "enforce it or
--     delete it — do not leave a fake control in place." It is ENFORCED, because
--     it is the ONLY server-verifiable precondition the feature has: without an
--     egg the call now returns `{ok:false, error:'missing_req_item',
--     item:'dragon_egg'}` and writes NO player value.
--
-- C3  THE JOURNAL CALLED A CLIENT CLAIM `source`.
--     player_ledger.meta carried the CLIENT-SUPPLIED p_source under the key
--     `source`, sitting beside the SERVER-DERIVED `catalogue_source` with equal
--     standing — so a forensic query over the ledger could not tell evidence
--     from assertion. The client key is renamed `claimed_source`;
--     `catalogue_source` (read from public.hr_companion_grants) is unchanged.
--     Renamed on BOTH surfaces the verb writes — the ledger row AND the
--     hr_rejections detail — because one value must not have two names across
--     rows written by the same RPC.
--
-- ── WHY A RESTATE AND NOT AN ANCHORED PATCH (measured, not assumed) ──────
-- This program's convention is to PATCH a live body rather than restate one,
-- because restating ~90 lines a file did not author is how the b484–b487 wave
-- silently reverted other migrations. That convention protects against an
-- UNMEASURED live body. This one is measured:
--
--   · production's hr_companion_grant prosrc, comment-stripped and
--     whitespace-collapsed, is md5 c48171cd71545c94792a39d02de68493 (3243 ch);
--   · a full repo replay of tests/schema-apply-order.json produces the SAME
--     normalised md5, c48171cd71545c94792a39d02de68493 (3243 ch).
--
-- They are the same function. (The RAW hashes differ — production's copy was
-- applied with its comments stripped, prosrc md5 0ebb0e3ea1c4c4489229a0bfa3286f88
-- / functiondef md5 8ad7195b4a3a8f720bade7e771f69681, against the repo replay's
-- prosrc md5 3db0c3ee357e14fc591eba71dbfa3dc2. A RAW hash therefore cannot be
-- the pin: it would pass on exactly one of the two databases this file has to
-- apply to. The NORMALISED hash is identical on both, robust to the comment
-- strip and to the PG17/PG18 skew between production and the PGlite replay, and
-- it is what §0 pins.)
--
-- There is exactly ONE prior author of this body — 2026-08-22-companion-grant.sql
-- §3 — and the measurement above proves production is running its output
-- unmodified. So a restate reverts nobody, and it is far more reviewable than an
-- anchored regexp that would have to WRAP four statements in a subtransaction.
-- §0 refuses to apply if that normalised hash has moved.
--
-- ── ⚠ DERIVATION CHAIN — THIS FILE IS NOW THE LAST TOUCHER ──────────────
-- supabase/migrations/2026-08-22-companion-grant.sql is GENERATED by
-- tools/gen-companion-grants.mjs from src/data/companions.js, and its §3 still
-- carries the PRE-hardening body. Nothing pins hr_companion_grant's body
-- (tests/schema-drift.baseline.json pins the SIGNATURE only; the function is not
-- in tests/live-hash-drift.baseline.json), so no guard breaks — but:
--
--   REGENERATING AND RE-APPLYING 2026-08-22-companion-grant.sql ALONE REVERTS
--   ALL THREE CONDITIONS, SILENTLY. Its §5/§6 self-checks all still pass on the
--   unhardened body, because they were written for it.
--
-- That is the b453 catalogue incident in FUNCTION form, and it is guarded the
-- same way: tests/companion-grant-hardening.mjs derives, from the manifest, the
-- list of files that (re)create hr_companion_grant and requires THIS file to be
-- last; and it replays the revert and proves re-applying this file repairs it.
-- The repair, written down: apply 2026-09-06-companion-grant-hardening.sql
-- immediately after any re-apply of 2026-08-22-companion-grant.sql.
--
-- ── PLAYER-FACING CONSEQUENCE OF C2, MEASURED (production, 2026-08-30) ───
-- Enforcing the req_item can only refuse a hatch the SERVER cannot see. So the
-- question is whether the server can ever hold a dragon_egg. Measured:
--   · public.hr_items has NO dragon_egg row                            (0)
--   · public.player_inventory has NO dragon_egg row, any character     (0)
--   · src/data/items.js has no `dragon_egg` among its 515 items, and no
--     drop table, recipe, shop or quest in src/data/** yields one
--   · public.player_progress has 0 `companion:%` unlock rows and
--     public.player_ledger 0 `companion_grant` rows — the verb has never
--     successfully run in production
-- dragon_egg is unobtainable CONTENT, not merely unmodelled server-side. The
-- client hatch path (src/features/companions.js wireDragonEggHatch) gates on
-- `G.inventory.dragon_egg > 0`, a value nothing in the game sets. So enforcing
-- the control refuses ZERO honest calls today and closes a free grant of
-- `whelp`. It is the cheapest moment this change will ever be made.
--
-- ⚠ FORWARD CONDITION, recorded because it will be forgotten otherwise: when
--   dragon_egg becomes obtainable it must become a SERVER-HELD item (an
--   hr_items row + a server-owned grant path) IN THE SAME BUILD. If the client
--   can hold an egg the server cannot see, every honest hatch answers
--   missing_req_item, the client's local ownedIds write is dropped by
--   accrue.js reconcileCompanions on the next reload, and the player loses a
--   companion. Enforcing a control over a value the server does not own is the
--   one way this change can hurt a player.
--
-- ── SEVERITY CLASSIFICATION, and the open question it leaves ────────────
-- Both new codes are recorded through public.hr_record_rejection, which grades
-- severity from ITS OWN arrays.
-- ✗ SUPERSEDED (2026-08-31, security C6 — 2026-09-07-companion-codes-severity
--   .sql, APPLIED): the paragraph that stood here argued BOTH codes should
--   stay 'normal' ("an incident would blame the player for our bug"). C6's
--   re-rule is the better case and now governs: `unknown_unlock` IS
--   c_incident — it is never player behaviour, one occurrence means the
--   catalogue was destroyed again, and a per-user threshold can never trip on
--   a server-wide defect; the alarm blames US, which is the point.
--   `missing_req_item` is c_escalating at the shared n=50 (one is a stale
--   client, fifty in a day is a signature an honest client cannot produce —
--   safe in both worlds once dragon_egg becomes honestly producible).
--   The client side is compatible BY GUARD, not by luck: the b499 ask-once
--   memo latches both codes to Infinity (companions.js _grantBlocked), so a
--   refused repeating trigger fires ONE rejection row ever — never a
--   per-harvest incident storm. Asserted in smoke-test.js's ask-once pair.
--   OPEN FOR SECURITY (C6): if sustained missing_req_item should escalate, the
--   one-line home is `c_escalating` in hr_record_rejection (50/day, the
--   rate_limited/own_listing/intent_mismatch profile) — NOT this file, because
--   that array is shared by every verb and changing it here would move the
--   severity of surfaces this migration has no business touching.
--
-- ── EXPLOIT-SURFACE DELTA ───────────────────────────────────────────────
-- Strictly NEGATIVE. Nothing becomes reachable that was not:
--   · the allowlist gate (hr_companion_grants) is byte-unchanged — a shop
--     companion and an unknown id are still refused 'not_grantable';
--   · the ACL is unchanged and ASSERTED byte-identical across the replace
--     (§0 captures proacl before, §3 compares after): authenticated only, never
--     anon / service_role / hr_engine / public;
--   · one FREE grant is REMOVED (`whelp`, previously mintable with no
--     precondition — server-priced perk value nil, since strB/crit are not in
--     the hr_perks_of channel, but a fake control is a fake control);
--   · the storage guard is NOT weakened. The handler catches SQLSTATE 23514
--     AND ONLY the message prefix 'unknown_unlock:'. unlock_wrong_kind,
--     unlock_over_ceiling, unlock_bad_rung, unlock_not_storable and
--     unlock_regressed all still PROPAGATE, and §4(i) proves it by flag-shaping
--     a catalogue row and requiring the call to raise.
--   · a refusal now consumes NOTHING: the req_item consume, the ownership row,
--     the version bump and the ledger row are ONE subtransaction, so the
--     TOCTOU race (the catalogue row deleted between the pre-check and the
--     insert — a live possibility while the wholesale-owner class is open)
--     rolls the egg back with the grant instead of eating it.
--
-- ── COST AT 100× PLAYERS ────────────────────────────────────────────────
-- Zero new tables, zero new indexes, zero new rows on the success path (the
-- ledger row per acquisition already existed; a companion is a bounded,
-- once-per-character-lifetime event, ≤17 rows per character, ever). Refusals
-- write to hr_rejections, which is (user_id, slot, day, code)-UPSERTED — one
-- row per player per day per code no matter how many calls, and the verb is
-- rate-gated at 60/hour. The added runtime cost per successful grant is one
-- extra index probe on hr_unlocks (PK lookup) and one subtransaction. Journal
-- rule 6 is untouched: nothing here logs per tick.
--
-- ── EDGE REDEPLOY ───────────────────────────────────────────────────────
-- NONE. No src/core, src/data or supabase/functions change. NO CLIENT CHANGE
-- EITHER: src/features/companions.js maybeServerGrant is fire-and-forget with a
-- .catch, and src/net/goal-claim.js grantCompanion returns the envelope
-- unexamined, so the two new machine codes are additive to a caller that
-- already ignores the body. (That is also the limitation: nothing yet SHOWS the
-- player a refused hatch. Client surfacing is the Systems Engineer's, and is
-- not smuggled in here.)
--
-- ── REVERSIBILITY ───────────────────────────────────────────────────────
-- Re-apply supabase/migrations/2026-08-22-companion-grant.sql, whose §3 is the
-- pre-hardening body verbatim. That restores the exact function measured above
-- (normalised md5 c48171cd71545c94792a39d02de68493) and nothing else — this
-- file writes no row, no policy, no grant and no catalogue entry. It is the
-- whole undo, and it is the SAME operation the derivation-chain warning above
-- calls a hazard, which is the point: the revert is one deliberate command, not
-- an accident.
--
-- ── APPLY AFTER ─────────────────────────────────────────────────────────
--   2026-08-22-companion-grant.sql                   (the function + allowlist)
--   2026-09-05-companion-unlock-catalogue-reseed.sql (the 17 storage rows)
-- and after ANY re-apply of either.
--
-- SAFE TO RE-RUN. Idempotent: create-or-replace of a fixed body plus asserts.
-- ⚠ APPLY IN ONE TRANSACTION. §0 hands the pre-state ACL to §3 through a
--   transaction-local GUC; §3 fails closed if it cannot read it.
-- ════════════════════════════════════════════════════════════════════════

-- ── 0. PRECONDITIONS — FAIL CLOSED ───────────────────────────────────────
do $$
declare
  v_p    oid;
  v_n    int;
  v_src  text;
  v_norm text;
  v_bad  text;
  -- The pre-hardening body, normalised (comments stripped with the
  -- NEWLINE-SENSITIVE flag, whitespace collapsed). Identical on production and
  -- on a full repo replay — see the header for both raw hashes and why a raw
  -- hash cannot be the pin.
  c_before constant text := 'c48171cd71545c94792a39d02de68493';
begin
  v_p := to_regprocedure('public.hr_companion_grant(int,text,text,uuid)');
  if v_p is null then
    raise exception 'hr_companion_grant(int,text,text,uuid) is absent — apply '
                    '2026-08-22-companion-grant.sql first. This file REPLACES that body; it does '
                    'not create the function, the allowlist, the grants or the baseline row.';
  end if;

  if to_regclass('public.hr_companion_grants') is null then
    raise exception 'public.hr_companion_grants is absent — apply 2026-08-22-companion-grant.sql first.';
  end if;
  if to_regclass('public.hr_unlocks') is null then
    raise exception 'public.hr_unlocks is absent — apply 2026-08-16-unlocks.generated.sql first.';
  end if;
  if to_regclass('public.hr_rejections') is null or to_regproc('public.hr_record_rejection') is null then
    raise exception 'the rejection journal is absent — apply 2026-08-11-player-state.sql first. '
                    'C1 and C2 both REQUIRE it: a refusal that is not journalled is invisible, and '
                    '"journalled the way the verb''s other refusals are" is the condition.';
  end if;

  -- THE STORAGE GUARD MUST STILL BE ATTACHED. C1 translates its refusal; it
  -- does not replace it. If the trigger were gone, this file's handler would be
  -- the ONLY defence — which is exactly what Security forbade.
  if not exists (select 1 from pg_trigger where tgrelid = 'public.player_progress'::regclass
                  and tgname = 'player_progress_unlock_guard' and not tgisinternal) then
    raise exception 'player_progress_unlock_guard is absent — apply '
                    '2026-08-16-artisan-progress-model.sql first. C1 TRANSLATES that trigger''s '
                    'refusal into a machine code; it is not a substitute for it, and installing the '
                    'translation over a missing guard would leave an uncatalogued unlock row '
                    'writable.';
  end if;

  -- ── THE RESEED IS APPLIED. Asserted BY VALUE and DERIVED, not as a table
  --    total: the reseed's own §2(d) refuses to pin 82 because pinning a
  --    whole-table count in a file that owns a handful of rows is precisely how
  --    the wholesale owner's "expected 62" passed after it had destroyed 20.
  --    This file owns NO hr_unlocks row at all, so it pins the only fact it
  --    actually depends on: every grantable companion has a correctly-shaped
  --    storage home, so C1's translation is the RARE path and not the normal one.
  select count(*) into v_n from public.hr_companion_grants;
  if v_n <> 17 then
    raise exception 'hr_companion_grants holds % rows, expected 17. The allowlist changed; the '
                    'hardening was reviewed against the seventeen.', v_n;
  end if;
  select string_agg('companion:' || g.companion_id, ', ' order by g.companion_id) into v_bad
    from public.hr_companion_grants g
    left join public.hr_unlocks u on u.unlock_id = 'companion:' || g.companion_id
   where u.unlock_id is null or u.namespace <> 'companion' or u.merge <> 'max'
      or u.progress_kind <> 'unlock' or u.max_value <> 1 or u.rungs <> array[1]::int[];
  if v_bad is not null then
    raise exception 'the reseed is NOT applied (or was destroyed again): % has no correctly-shaped '
                    'hr_unlocks row. Apply 2026-09-05-companion-unlock-catalogue-reseed.sql first. '
                    'Installing C1 over a missing catalogue would convert a player-visible data '
                    'loss into a tidy refusal and leave the loss in place.', v_bad;
  end if;
  select count(*) into v_n from public.hr_unlocks where namespace = 'companion';
  if v_n <> 21 then
    raise exception 'namespace=companion holds % hr_unlocks rows, expected 21 (17 grantable + 4 '
                    'shop). The reseed''s own close condition was 21.', v_n;
  end if;
  raise notice '§0: reseed confirmed — % hr_unlocks rows total, 21 in namespace=companion, all 17 '
               'grantable companions correctly shaped.',
               (select count(*) from public.hr_unlocks);

  -- ── THE BODY PIN. Normalised, so it holds across production's
  --    comment-stripped copy AND the repo replay AND the PG17/PG18 skew.
  select p.prosrc into v_src from pg_proc p where p.oid = v_p;
  v_norm := md5(btrim(regexp_replace(regexp_replace(v_src, '--.*', '', 'gn'), '[[:space:]]+', ' ', 'g')));
  if v_norm = c_before then
    raise notice '§0: pre-hardening body confirmed (normalised md5 %). Applying C1+C2+C3.', v_norm;
  elsif v_src like '%claimed_source%' and v_src like '%missing_req_item%'
        and v_src like '%unknown_unlock:%' then
    raise notice '§0: the body is ALREADY hardened (normalised md5 %, expected pre-image %). '
                 'Re-running: §1 rewrites it to this file''s exact text and §3/§4 re-prove it.',
                 v_norm, c_before;
  else
    raise exception 'hr_companion_grant''s body is NEITHER the reviewed pre-image NOR already '
                    'hardened.%  normalised md5 = %, expected %.%'
                    '  Somebody changed the function between the review and this apply. This file '
                    'RESTATES the whole body, so applying it now would silently revert that change '
                    '— the b484-b487 failure class. Re-measure the live body '
                    '(pg_get_functiondef), re-derive the diff, and re-review.',
                    chr(10), v_norm, c_before, chr(10);
  end if;

  -- The three defects, each asserted PRESENT by its own anchor, so a body that
  -- hashes right but has drifted in a way the normaliser cannot see still stops
  -- the file. (Skipped when already hardened.)
  if v_norm = c_before then
    if v_src not like '%v_egg := false;%' then
      raise exception '§0: C2''s anchor (the fake control''s `v_egg := false;` else-branch) is not '
                      'in the live body. The defect this file fixes is not there to fix.';
    end if;
    if v_src like '%exception%when%check_violation%' then
      raise exception '§0: the live body already has a check_violation handler. C1 would be '
                      'installing a second one over an unreviewed first.';
    end if;
    if v_src not like '%''source'', p_source%' then
      raise exception '§0: C3''s anchor (the ledger meta key `source`) is not in the live body.';
    end if;
    if v_src like '%claimed_source%' then
      raise exception '§0: the live body already writes claimed_source — C3 is already applied but '
                      'the hash says otherwise. Stop and re-measure.';
    end if;
  end if;

  -- ── HAND THE PRE-STATE ACL TO §3. `create or replace function` is documented
  --    to RETAIN privileges; this file re-states the revoke/grant block anyway
  --    (belt and braces, and so it is self-sufficient on a fresh chain), and §3
  --    proves the pair produced a BYTE-IDENTICAL ACL rather than trusting either.
  perform set_config('hearthrise.cgh_acl_before',
                     coalesce((select proacl::text from pg_proc where oid = v_p), 'NULL'), true);
  perform set_config('hearthrise.cgh_owner_before',
                     (select proowner::regrole::text from pg_proc where oid = v_p), true);
end $$;

-- ── 1. THE HARDENED BODY ─────────────────────────────────────────────────
-- Restated in full from the measured live body (see the header). EVERY line
-- outside the three marked blocks is that body verbatim; the comments are the
-- authoring file's, restored, because production's copy was applied stripped.
--
-- ── THE SHAPE OF C1: TWO LAYERS, AND WHY BOTH ────────────────────────────
--   LAYER A — a pre-check on public.hr_unlocks, placed AFTER the owned-once
--     short-circuit (so an already-owned companion whose catalogue row vanished
--     is still reported already_owned — no write is needed, so no refusal is
--     owed) and BEFORE the req_item read. It is the path that fires in the
--     named incident, it returns a deterministic refusal, and it reaches no
--     mutation at all.
--   LAYER B — a NARROW handler around the mutation block, for the TOCTOU race
--     Layer A cannot close: nothing locks public.hr_unlocks, and the b453 class
--     IS a concurrent wholesale `delete from public.hr_unlocks`, so the row can
--     vanish between the pre-check and the insert. The handler catches SQLSTATE
--     23514 and re-raises unless the message begins 'unknown_unlock:'. Because
--     the req_item consume is INSIDE that subtransaction, a raced refusal rolls
--     the egg back with the grant — the alternative (an exception block around
--     the insert alone) would leave the egg consumed and the companion not
--     granted, which is a player-value loss dressed as a fix.
--   The trigger remains the BACKSTOP: Layer A does not decide storability, and
--   Layer B translates exactly one message and propagates every other.
create or replace function public.hr_companion_grant(
  p_slot int default 0,
  p_companion text default null,
  p_source text default null,
  p_idem uuid default null)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_uid   uuid := auth.uid();
  v_st    public.player_state%rowtype;
  v_cat   public.hr_companion_grants%rowtype;
  v_key   text;
  v_prev  bigint;
  v_have  bigint;
  v_egg   boolean := null;
  v_raced boolean := false;
  -- Acquisitions are rare (a bounded lifetime of 17 non-shop pets); 60/hour
  -- is generous and cheap, and a rejected call still consumes budget (A9).
  c_rate constant int := 60;
begin
  if v_uid is null then return jsonb_build_object('ok', false, 'error', 'not_signed_in'); end if;

  -- ── RATE GATE (A9) — hr_companion_equip's exact shape, SAMPLED writes ─────
  if not public.hr_rate_ok(v_uid, 'companion_grant', c_rate, interval '1 hour') then
    if public.hr_rate_sample_weight(public.hr_rate_over(v_uid, 'companion_grant') - c_rate) > 0 then
      perform public.hr_record_rejection(v_uid, coalesce(p_slot, 0), 'companion_grant', 'rate_limited',
        jsonb_build_object('limit', c_rate, 'per', '1 hour'),
        public.hr_rate_sample_weight(public.hr_rate_over(v_uid, 'companion_grant') - c_rate));
    end if;
    return jsonb_build_object('ok', false, 'error', 'rate_limited');
  end if;

  if p_slot is null or p_slot < 0 or p_slot > 5 then
    return jsonb_build_object('ok', false, 'error', 'bad_slot');
  end if;
  if p_companion is null or p_companion = '' then
    return jsonb_build_object('ok', false, 'error', 'unknown_companion');
  end if;

  -- ── THE ALLOWLIST GATE — the mint refusal, BEFORE any lock. A shop companion
  --    (sold for gold by hr_unlock_buy) and an unknown/forged id are both ABSENT
  --    here and refused by name. A perk a client could mint for itself for free
  --    dies here.
  select * into v_cat from public.hr_companion_grants where companion_id = p_companion;
  if not found then
    -- C3: the client's claim is named as a CLAIM even in a refusal. One value,
    -- one name, on every row this verb writes.
    perform public.hr_record_rejection(v_uid, coalesce(p_slot, 0), 'companion_grant', 'not_grantable',
      jsonb_build_object('companion', p_companion, 'claimed_source', p_source));
    return jsonb_build_object('ok', false, 'error', 'not_grantable',
      'detail', jsonb_build_object('companion', p_companion));
  end if;

  -- Serialise this character — the SAME advisory key hr_apply / hr_companion_equip take.
  perform pg_advisory_xact_lock(hashtextextended(v_uid::text || ':' || p_slot::text, 0));

  select * into v_st from public.player_state where user_id = v_uid and slot = p_slot for update;
  if not found then return jsonb_build_object('ok', false, 'error', 'no_character'); end if;

  v_key := 'companion:' || p_companion;

  -- ── OWNED-ONCE IDEMPOTENCY. A companion is a boolean; owning it already is a
  --    success that consumes NO req_item, writes NO journal row and does NOT bump
  --    the version — a replay is harmless. (The ON CONFLICT below is the second,
  --    independent guard against a concurrent double-grant.)
  select value into v_prev from public.player_progress
   where user_id = v_uid and slot = p_slot and kind = 'unlock' and key = v_key and period_key = '';
  if coalesce(v_prev, 0) > 0 then
    return jsonb_build_object('ok', true, 'companion', p_companion, 'already_owned', true);
  end if;

  -- ══ C1, LAYER A — THE STORAGE HOME, CHECKED BEFORE ANYTHING IS SPENT ═════
  -- Without this row player_progress_unlock_guard raises 23514 and the caller
  -- gets a 500 it cannot tell from an outage. Placed after owned-once (an owner
  -- needs no write) and before the req_item read (a refusal must cost nothing).
  if not exists (select 1 from public.hr_unlocks where unlock_id = v_key) then
    perform public.hr_record_rejection(v_uid, p_slot, 'companion_grant', 'unknown_unlock',
      jsonb_build_object('companion', p_companion, 'unlock_id', v_key,
                         'claimed_source', p_source, 'catalogue_source', v_cat.source_kind,
                         'raced', false));
    return jsonb_build_object('ok', false, 'error', 'unknown_unlock:' || v_key,
      'detail', jsonb_build_object('companion', p_companion, 'unlock_id', v_key, 'raced', false));
  end if;

  -- ══ C2 — THE SERVER-VERIFIABLE PRECONDITION, ENFORCED ════════════════════
  -- (dragon_egg hatch -> whelp.) Previously this read the inventory, recorded
  -- the answer in v_egg, and granted either way: a control that measured but
  -- did not decide. It now REFUSES, and refuses before any write. The FOR
  -- UPDATE row lock is taken HERE, at the check, and held for the rest of the
  -- transaction, so the consume below cannot race a concurrent spend of the
  -- same egg.
  if v_cat.req_item is not null then
    select qty into v_have from public.player_inventory
     where user_id = v_uid and slot = p_slot and item_id = v_cat.req_item for update;
    if coalesce(v_have, 0) < 1 then
      perform public.hr_record_rejection(v_uid, p_slot, 'companion_grant', 'missing_req_item',
        jsonb_build_object('companion', p_companion, 'item', v_cat.req_item,
                           'held', coalesce(v_have, 0), 'claimed_source', p_source,
                           'catalogue_source', v_cat.source_kind));
      return jsonb_build_object('ok', false, 'error', 'missing_req_item',
        'item', v_cat.req_item, 'companion', p_companion);
    end if;
  end if;

  -- ══ THE MUTATION — ONE SUBTRANSACTION (C1, LAYER B) ══════════════════════
  -- Consume + grant + version bump + journal are ATOMIC against the guard's
  -- refusal, so a raced unknown_unlock rolls the req_item back too.
  begin
    if v_cat.req_item is not null then
      if v_have = 1 then
        delete from public.player_inventory
         where user_id = v_uid and slot = p_slot and item_id = v_cat.req_item;
      else
        update public.player_inventory set qty = v_have - 1
         where user_id = v_uid and slot = p_slot and item_id = v_cat.req_item;
      end if;
      v_egg := true;
    end if;

    -- ── THE GRANT. A single-rung [1] unlock row. ON CONFLICT DO NOTHING makes a
    --    concurrent double-grant a no-op; hr_unlock_guard independently refuses any
    --    value off the companion:<id> ladder.
    insert into public.player_progress (user_id, slot, kind, key, period_key, value)
      values (v_uid, p_slot, 'unlock', v_key, '', 1)
    on conflict (user_id, slot, kind, key, period_key) do nothing;

    -- Version bump so an in-flight client re-reads the owned set (reconcileCompanions
    -- reads it from the envelope). accrued_to is UNTOUCHED — a grant does not reprice
    -- an in-flight accrual (the passive bonus is priced off the EQUIPPED id, which a
    -- grant does not change), so no collect-first guard and no confiscation.
    update public.player_state
       set version = version + 1, updated_at = now()
     where user_id = v_uid and slot = p_slot;

    -- ── THE JOURNAL. ONE row per acquisition (a rare event, bounded lifetime —
    --    journal rule 6 is about per-tick logging, which this is not).
    --    C3: `claimed_source` is what the CLIENT said; `catalogue_source` is what
    --    the SERVER's own allowlist says. They are no longer peers by name.
    insert into public.player_ledger (user_id, slot, kind, intent, meta)
      values (v_uid, p_slot, 'admin', 'companion_grant',
              jsonb_build_object('companion', p_companion, 'claimed_source', p_source,
                                 'catalogue_source', v_cat.source_kind,
                                 'req_item', v_cat.req_item, 'egg_consumed', v_egg,
                                 'idem', p_idem));
  exception when check_violation then
    -- NARROW BY MESSAGE, NOT BY SQLSTATE ALONE. hr_unlock_guard raises 23514 for
    -- unknown_unlock, unlock_wrong_kind, unlock_over_ceiling, unlock_bad_rung,
    -- unlock_not_storable and unlock_regressed, and every table here can raise
    -- 23514 from a check constraint. Only the FIRST is a refusal this verb owns;
    -- the rest are model violations that must stay loud. `raise;` re-raises the
    -- original, so the trigger's protection is intact.
    if sqlerrm not like 'unknown_unlock:%' then raise; end if;
    v_raced := true;
  end;

  if v_raced then
    -- The catalogue row was deleted between Layer A and the insert. Same machine
    -- code, flagged `raced` so the ledger can tell "it was already gone" from
    -- "it vanished mid-transaction" — the difference between a stale deploy and
    -- an active wholesale delete.
    perform public.hr_record_rejection(v_uid, p_slot, 'companion_grant', 'unknown_unlock',
      jsonb_build_object('companion', p_companion, 'unlock_id', v_key,
                         'claimed_source', p_source, 'catalogue_source', v_cat.source_kind,
                         'raced', true));
    return jsonb_build_object('ok', false, 'error', 'unknown_unlock:' || v_key,
      'detail', jsonb_build_object('companion', p_companion, 'unlock_id', v_key, 'raced', true));
  end if;

  return jsonb_build_object('ok', true, 'companion', p_companion, 'egg_consumed', v_egg);
end $$;

-- ── 2. GRANTS — REVOKE BEFORE GRANT ──────────────────────────────────────
-- `create or replace function` retains privileges, so this is belt-and-braces
-- (and makes the file self-sufficient if it is ever the first thing to install
-- the body on a fresh chain). §3 proves the pair left the ACL byte-identical.
revoke execute on function public.hr_companion_grant(int, text, text, uuid)
  from public, anon, service_role, hr_engine;
grant execute on function public.hr_companion_grant(int, text, text, uuid) to authenticated;

-- ── 3. STRUCTURAL ASSERTIONS ─────────────────────────────────────────────
do $$
declare
  v_p     oid;
  v_n     int;
  v_r     text;
  v_before text;
  v_owner  text;
  v_src   text;
begin
  v_p := to_regprocedure('public.hr_companion_grant(int,text,text,uuid)');
  if v_p is null then raise exception '§3: hr_companion_grant did not install'; end if;

  -- (a) EXACTLY ONE definition — a replace, never a new overload. An overload
  --     would leave the OLD body reachable under a different argument list.
  select count(*) into v_n from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'hr_companion_grant';
  if v_n <> 1 then
    raise exception '§3(a): % definitions of hr_companion_grant exist. This file REPLACES one body; '
                    'an overload means the pre-hardening function is still callable.', v_n;
  end if;

  -- (b) THE ACL IS BYTE-IDENTICAL ACROSS THE REPLACE. Fails closed if §0's
  --     hand-off is unreadable, which means the file was not applied in one
  --     transaction and this assertion would otherwise be silently vacuous.
  v_before := current_setting('hearthrise.cgh_acl_before', true);
  if v_before is null or v_before = '' then
    raise exception '§3(b): the pre-state ACL recorded by §0 is unreadable. Apply this file in ONE '
                    'transaction (begin; ... commit;) — §0 hands it over through a transaction-local '
                    'GUC, and an unverifiable ACL on a SECURITY DEFINER function is not an assertion.';
  end if;
  v_r := coalesce((select proacl::text from pg_proc where oid = v_p), 'NULL');
  if v_r is distinct from v_before then
    raise exception '§3(b): the ACL MOVED across the replace: % -> %. A SECURITY DEFINER grant is '
                    'the whole game; this file is not permitted to change one.', v_before, v_r;
  end if;
  v_owner := current_setting('hearthrise.cgh_owner_before', true);
  if v_owner is distinct from (select proowner::regrole::text from pg_proc where oid = v_p) then
    raise exception '§3(b): the function OWNER moved (% -> %). On a SECURITY DEFINER function the '
                    'owner IS the authority it runs as.',
                    v_owner, (select proowner::regrole::text from pg_proc where oid = v_p);
  end if;

  -- (c) …and the ACL is the RIGHT one, stated independently of (b) so that
  --     "unchanged" can never mean "unchanged and wrong".
  if not has_function_privilege('authenticated', v_p, 'execute') then
    raise exception '§3(c): hr_companion_grant is not executable by authenticated — the client '
                    'cannot grant a companion it legitimately acquired.';
  end if;
  foreach v_r in array array['public','anon','service_role','hr_engine'] loop
    if has_function_privilege(v_r, v_p, 'execute') then
      raise exception '§3(c): hr_companion_grant is executable by % — it must be authenticated-only. '
                      'hr_engine especially: the accrual engine proposes deltas an RPC re-validates; '
                      'it must never grant a companion for somebody.', v_r;
    end if;
  end loop;

  -- (d) SECURITY DEFINER + a pinned search_path. Both were true before; a
  --     restate is exactly where they get lost.
  if (select prosecdef from pg_proc where oid = v_p) is not true then
    raise exception '§3(d): hr_companion_grant is no longer SECURITY DEFINER';
  end if;
  if not exists (select 1 from pg_proc where oid = v_p
                  and 'search_path=public' = any (coalesce(proconfig, array[]::text[]))) then
    raise exception '§3(d): hr_companion_grant lost its pinned search_path — a SECURITY DEFINER '
                    'function without one is resolvable by the caller''s search_path. proconfig = %',
                    (select proconfig from pg_proc where oid = v_p);
  end if;

  -- (e) THE THREE CONDITIONS ARE STRUCTURALLY PRESENT in the installed body.
  --     Text anchors, so §4's behavioural proofs cannot be the only evidence
  --     (a behavioural test can be satisfied by the wrong mechanism).
  select prosrc into v_src from pg_proc where oid = v_p;
  if v_src not like '%unknown_unlock:%' or v_src not like '%check_violation%' then
    raise exception '§3(e) C1: the installed body has no unknown_unlock translation';
  end if;
  if v_src not like '%missing_req_item%' then
    raise exception '§3(e) C2: the installed body has no missing_req_item refusal';
  end if;
  if v_src like '%v_egg := false;%' then
    raise exception '§3(e) C2: the fake control''s `v_egg := false;` fall-through is STILL in the '
                    'body — the precondition measures without deciding.';
  end if;
  if v_src not like '%claimed_source%' then
    raise exception '§3(e) C3: the installed body does not write claimed_source';
  end if;
  if v_src like '%''source'', p_source%' then
    raise exception '§3(e) C3: the installed body still writes the bare client key `source`';
  end if;
  -- The narrowness of the catch, asserted as TEXT as well as behaviour (§4(i)),
  -- in BOTH of its halves. `when others` would swallow every model violation the
  -- storage guard raises; and even under `when check_violation`, DROPPING THE
  -- MESSAGE TEST would swallow unlock_wrong_kind / unlock_over_ceiling /
  -- unlock_bad_rung / unlock_not_storable / unlock_regressed and report them as
  -- a tidy unknown_unlock. The re-raise is the backstop; it is anchored here so
  -- its removal cannot be a silent one-line edit.
  if v_src like '%exception when others%' then
    raise exception '§3(e) C1: the handler catches `when others`. It must catch check_violation and '
                    're-raise anything whose message is not unknown_unlock:, or the trigger''s '
                    'protection is gone.';
  end if;
  if v_src not like '%then raise; end if;%' then
    raise exception '§3(e) C1: the handler no longer RE-RAISES. Catching 23514 without testing the '
                    'message turns every storage-guard model violation into a false unknown_unlock '
                    'and silently disarms the trigger this translation sits on top of.';
  end if;

  -- (f) THE CLIENT-RPC BASELINE row still stands (this file does not change who
  --     may call the verb, and the hygiene detector reads this table).
  if not exists (select 1 from public.hr_client_rpc_baseline b
                  where b.proname = 'hr_companion_grant' and b.grantee = 'authenticated') then
    raise exception '§3(f): the hr_client_rpc_baseline row for hr_companion_grant is gone — the '
                    'grant-hygiene detector would report this verb as an unreviewed client surface.';
  end if;

  -- (g) THE ALLOWLIST IS UNTOUCHED. This file changes behaviour, never content.
  select count(*) into v_n from public.hr_companion_grants;
  if v_n <> 17 then raise exception '§3(g): hr_companion_grants moved to % rows', v_n; end if;
  select count(*) into v_n from public.hr_unlocks where namespace = 'companion';
  if v_n <> 21 then raise exception '§3(g): namespace=companion moved to % rows', v_n; end if;

  raise notice '§3 PASSED: one definition; ACL and owner byte-identical across the replace '
               '(%); authenticated-only, never anon/service_role/hr_engine; SECURITY DEFINER with '
               'search_path=public; C1+C2+C3 present by anchor; baseline row intact; catalogue '
               'untouched (17 grantable / 21 companion). New normalised body md5 = %.',
               v_before,
               md5(btrim(regexp_replace(regexp_replace(v_src, '--.*', '', 'gn'), '[[:space:]]+', ' ', 'g')));
end $$;

-- ── 4. BEHAVIOUR — driven through the REAL RPC, rolled back (HRG28) ───────
-- Every probe below runs inside ONE subtransaction that is deliberately
-- aborted. Any assertion that fires raises a NON-HRG28 error, which the handler
-- does not catch, so it aborts the whole migration — a half-applied gate is
-- impossible, and so is a leaked probe row or a mutated catalogue.
do $$
declare
  v_uid   uuid := '00000000-0000-4000-8000-0000c0a91a70'::uuid;
  v_r     jsonb;
  v_env   jsonb;
  v_meta  jsonb;
  v_ver   bigint;
  v_led   bigint;
  v_state text;
  v_msg   text;
begin
  if to_regprocedure('public.hr_create_character(int)') is null then
    raise exception '§4 CANNOT RUN: hr_create_character is missing — apply '
                    '2026-08-14-character-bootstrap.sql first. A skipped check is not a passed one.';
  end if;

  begin  -- ── subtransaction, rolled back ────────────────────────────────────
    insert into auth.users (id) values (v_uid);
    perform set_config('request.jwt.claim.sub', v_uid::text, true);
    perform public.hr_create_character(0);

    -- ── (a) THE CONTROL: an ordinary grant is UNCHANGED. Row, version bump,
    --        owned projection, and still equippable. If this fails, everything
    --        below is measuring a broken verb rather than the hardening.
    select version into v_ver from public.player_state where user_id = v_uid and slot = 0;
    v_r := public.hr_companion_grant(0, 'badger', 'boss:i_said_so', gen_random_uuid());
    if coalesce(v_r->>'ok', 'false') <> 'true' then
      raise exception '§4(a) CONTROL FAILED: a legitimate badger grant was refused (%)', v_r;
    end if;
    if not exists (select 1 from public.player_progress where user_id = v_uid and slot = 0
                    and kind = 'unlock' and key = 'companion:badger' and value = 1) then
      raise exception '§4(a): the ownership row was not written';
    end if;
    if (select version from public.player_state where user_id = v_uid and slot = 0) <> v_ver + 1 then
      raise exception '§4(a): the grant did not bump the version';
    end if;
    v_env := public.hr_state_of(v_uid, 0);
    if not (v_env->'companions'->'owned' @> ('["badger"]')::jsonb) then
      raise exception '§4(a): hr_state_of does not project badger in owned: %',
        v_env->'companions'->'owned';
    end if;
    if coalesce((public.hr_companion_equip(0, 'badger', false))->>'ok', 'false') <> 'true' then
      raise exception '§4(a): a granted companion could not be equipped';
    end if;

    -- ── (b) C3 — THE LEDGER IS HONEST ABOUT WHICH FIELD IS EVIDENCE.
    --        The claim above ('boss:i_said_so') deliberately CONTRADICTS the
    --        catalogue ('drop'), so the two fields cannot be confused for one
    --        another and a fixture built from the wrong one cannot pass.
    select meta into v_meta from public.player_ledger
     where user_id = v_uid and slot = 0 and intent = 'companion_grant'
     order by id desc limit 1;
    if v_meta is null then raise exception '§4(b): the grant wrote no ledger row'; end if;
    if not (v_meta ? 'claimed_source') then
      raise exception '§4(b) C3: the ledger meta carries no claimed_source: %', v_meta;
    end if;
    if v_meta ? 'source' then
      raise exception '§4(b) C3: the ledger meta STILL carries the bare client key `source` beside '
                      'the server-derived catalogue_source: %', v_meta;
    end if;
    if v_meta->>'claimed_source' is distinct from 'boss:i_said_so' then
      raise exception '§4(b) C3: claimed_source is % — it must be the CLIENT''s string verbatim, '
                      'or the ledger is not recording what was claimed', v_meta->>'claimed_source';
    end if;
    if v_meta->>'catalogue_source' is distinct from 'drop' then
      raise exception '§4(b) C3: catalogue_source is % — it must be the SERVER''s own allowlist '
                      'value (badger = drop), unaffected by the client''s claim',
                      v_meta->>'catalogue_source';
    end if;

    -- ── (c) REPLAY is already_owned: no second row, no second ledger row, no
    --        second version bump. (Unchanged behaviour, re-proved.)
    select version into v_ver from public.player_state where user_id = v_uid and slot = 0;
    select count(*) into v_led from public.player_ledger
     where user_id = v_uid and intent = 'companion_grant';
    v_r := public.hr_companion_grant(0, 'badger', 'drop:again', gen_random_uuid());
    if coalesce(v_r->>'already_owned', 'false') <> 'true' then
      raise exception '§4(c): a replay was not reported already_owned (%)', v_r;
    end if;
    if (select version from public.player_state where user_id = v_uid and slot = 0) <> v_ver
       or (select count(*) from public.player_ledger
            where user_id = v_uid and intent = 'companion_grant') <> v_led then
      raise exception '§4(c): a replay wrote state';
    end if;

    -- ── (d) THE MINT GATE IS UNCHANGED: an unknown id and a SHOP companion are
    --        both still refused not_grantable.
    v_r := public.hr_companion_grant(0, 'any_op_companion', 'drop:x', gen_random_uuid());
    if v_r->>'error' is distinct from 'not_grantable' then
      raise exception '§4(d): an unknown id answered % (expected not_grantable)', v_r;
    end if;
    v_r := public.hr_companion_grant(0, 'sparrow', 'shop', gen_random_uuid());
    if v_r->>'error' is distinct from 'not_grantable' then
      raise exception '§4(d): the shop companion sparrow answered % (expected not_grantable — a '
                      'free shop pet is exactly the mint this gate refuses)', v_r;
    end if;

    -- ══ (e) C2 — WITHOUT THE EGG, NOTHING HAPPENS ════════════════════════════
    select version into v_ver from public.player_state where user_id = v_uid and slot = 0;
    select count(*) into v_led from public.player_ledger
     where user_id = v_uid and intent = 'companion_grant';
    v_r := public.hr_companion_grant(0, 'whelp', 'hatch:dragon_egg', gen_random_uuid());
    if coalesce(v_r->>'ok', 'true') <> 'false' or v_r->>'error' is distinct from 'missing_req_item' then
      raise exception '§4(e) C2: whelp was granted WITHOUT its req_item (%). The control still '
                      'measures and does not decide — it is still fake.', v_r;
    end if;
    if v_r->>'item' is distinct from 'dragon_egg' then
      raise exception '§4(e) C2: the refusal does not name the item it wants (%)', v_r;
    end if;
    if exists (select 1 from public.player_progress where user_id = v_uid and slot = 0
                and kind = 'unlock' and key = 'companion:whelp') then
      raise exception '§4(e) C2: refused, but the ownership row was written anyway';
    end if;
    if (select version from public.player_state where user_id = v_uid and slot = 0) <> v_ver then
      raise exception '§4(e) C2: a refused grant bumped the version';
    end if;
    if (select count(*) from public.player_ledger
         where user_id = v_uid and intent = 'companion_grant') <> v_led then
      raise exception '§4(e) C2: a refused grant wrote a ledger row';
    end if;
    if not exists (select 1 from public.hr_rejections where user_id = v_uid
                    and intent = 'companion_grant' and code = 'missing_req_item') then
      raise exception '§4(e) C2: the refusal was not journalled. "Journalled the way the verb''s '
                      'other refusals are" is the condition, not a nicety — an unjournalled refusal '
                      'is an invisible one.';
    end if;

    -- ══ (f) C1 — THE MISSING CATALOGUE ROW IS A MACHINE CODE, AND IT COSTS
    --        THE PLAYER NOTHING. Run on the ONE companion with a req_item, so
    --        the same probe proves both properties at once.
    --
    --   ⚠ IN ITS OWN NESTED SUBTRANSACTION (HRG29), and the catalogue row is
    --     restored BY THAT ROLLBACK rather than by an INSERT. Two reasons, and
    --     the second is not cosmetic:
    --       · a restore statement can be wrong, or be edited out; a rollback
    --         cannot. The deletion is structurally incapable of escaping.
    --       · this file must not contain an INSERT statement against
    --         public.hr_unlocks — not even a commented one.
    --         tests/unlock-catalogue-ownership.mjs derives the catalogue's
    --         repair list by scanning every manifest file's TEXT for exactly
    --         that statement, and a file that only touches hr_unlocks inside a
    --         rolled-back probe would be mis-classified as a seeder that must be
    --         re-applied after a wholesale wipe. It is not one. (Measured: the
    --         first draft used a restore INSERT and turned that guard red.)
    insert into public.player_inventory (user_id, slot, item_id, qty)
      values (v_uid, 0, 'dragon_egg', 2)
      on conflict (user_id, slot, item_id) do update set qty = excluded.qty;
    begin
      delete from public.hr_unlocks where unlock_id = 'companion:whelp';
      begin
        v_r := public.hr_companion_grant(0, 'whelp', 'hatch:dragon_egg', gen_random_uuid());
      exception when others then
        raise exception '§4(f) C1: with companion:whelp absent from hr_unlocks the RPC still RAISES '
                        '(% / %) instead of returning a machine code. That raise is the PostgREST 500 '
                        'a client cannot tell from an outage — the whole condition.', sqlstate, sqlerrm;
      end;
      if v_r->>'error' is distinct from 'unknown_unlock:companion:whelp' then
        raise exception '§4(f) C1: expected error unknown_unlock:companion:whelp, got %', v_r;
      end if;
      if coalesce(v_r->>'ok', 'true') <> 'false' then
        raise exception '§4(f) C1: the refusal reported ok (%)', v_r;
      end if;
      if coalesce((v_r->'detail'->>'raced')::boolean, true) <> false then
        raise exception '§4(f) C1: the refusal should be marked raced=false — Layer A answered '
                        'before anything was locked or spent (%)', v_r;
      end if;
      if (select qty from public.player_inventory
           where user_id = v_uid and slot = 0 and item_id = 'dragon_egg') <> 2 then
        raise exception '§4(f) C1: the refusal CONSUMED the req_item. A refusal that eats the '
                        'player''s egg and grants nothing is worse than the 500 it replaced.';
      end if;
      if exists (select 1 from public.player_progress where user_id = v_uid and slot = 0
                  and kind = 'unlock' and key = 'companion:whelp') then
        raise exception '§4(f) C1: refused, but the ownership row was written';
      end if;
      if not exists (select 1 from public.hr_rejections where user_id = v_uid
                      and intent = 'companion_grant' and code = 'unknown_unlock') then
        raise exception '§4(f) C1: the refusal was not journalled';
      end if;
      raise exception using errcode = 'HRG29', message = '§4(f) done — restoring companion:whelp';
    exception when sqlstate 'HRG29' then
      null;   -- the catalogue row is back, by rollback
    end;
    if not exists (select 1 from public.hr_unlocks where unlock_id = 'companion:whelp'
                    and progress_kind = 'unlock' and merge = 'max' and max_value = 1
                    and rungs = array[1]::int[]) then
      raise exception '§4(f): the nested rollback did NOT restore companion:whelp. Every catalogue '
                      'mutation in this gate depends on that rollback; if it does not happen the '
                      'database is left missing a storage home.';
    end if;

    -- ══ (g) C2, THE POSITIVE CONTROL. (e) and (f) are both REFUSALS; a pair of
    --        refusals proves nothing unless the same call SUCCEEDS when its
    --        precondition is met. With 2 eggs held and the catalogue row back,
    --        whelp grants and EXACTLY ONE egg is consumed.
    v_r := public.hr_companion_grant(0, 'whelp', 'hatch:dragon_egg', gen_random_uuid());
    if coalesce(v_r->>'ok', 'false') <> 'true' then
      raise exception '§4(g) CONTROL FAILED: whelp refused with the egg held and the catalogue row '
                      'present (%). C2 would then be refusing everything, not enforcing anything.', v_r;
    end if;
    if coalesce(v_r->>'egg_consumed', 'false') <> 'true' then
      raise exception '§4(g): the egg was not reported consumed (%)', v_r;
    end if;
    if (select qty from public.player_inventory
         where user_id = v_uid and slot = 0 and item_id = 'dragon_egg') <> 1 then
      raise exception '§4(g): the egg qty was not decremented by exactly one';
    end if;
    if not exists (select 1 from public.player_progress where user_id = v_uid and slot = 0
                    and kind = 'unlock' and key = 'companion:whelp' and value = 1) then
      raise exception '§4(g): whelp was reported granted but no ownership row exists';
    end if;

    -- ══ (h) C1 on the COMMON shape — 16 of the 17 grantable companions have no
    --        req_item, so prove the translation there too, with its own control.
    --        Same nested-rollback restore as (f), same two reasons.
    begin
      delete from public.hr_unlocks where unlock_id = 'companion:hawk';
      begin
        v_r := public.hr_companion_grant(0, 'hawk', 'drop:cliffside', gen_random_uuid());
      exception when others then
        raise exception '§4(h) C1: a missing catalogue row on a no-req_item companion still RAISES '
                        '(% / %)', sqlstate, sqlerrm;
      end;
      if v_r->>'error' is distinct from 'unknown_unlock:companion:hawk' then
        raise exception '§4(h) C1: expected unknown_unlock:companion:hawk, got %', v_r;
      end if;
      raise exception using errcode = 'HRG30', message = '§4(h) done — restoring companion:hawk';
    exception when sqlstate 'HRG30' then
      null;
    end;
    v_r := public.hr_companion_grant(0, 'hawk', 'drop:cliffside', gen_random_uuid());
    if coalesce(v_r->>'ok', 'false') <> 'true' then
      raise exception '§4(h) CONTROL FAILED: hawk refused once its catalogue row is back (%). '
                      'Either the nested rollback did not restore it, or the refusal in the arm '
                      'above was not caused by the missing row at all.', v_r;
    end if;

    -- ══ (i) THE NARROWNESS CONTROL — the storage guard is STILL the backstop.
    --        Flag-shape a catalogue row so the guard raises unlock_wrong_kind
    --        (23514, the SAME sqlstate C1 catches). It MUST propagate: a
    --        `when others` handler, or a handler that keyed on sqlstate alone,
    --        would swallow a model violation and report a tidy refusal while
    --        writing nothing and telling nobody.
    v_state := 'NO_RAISE'; v_msg := '';
    begin
      update public.hr_unlocks set progress_kind = 'flag' where unlock_id = 'companion:heron';
      begin
        v_r := public.hr_companion_grant(0, 'heron', 'skill:fishing', gen_random_uuid());
      exception when others then
        v_state := sqlstate; v_msg := sqlerrm;
      end;
      -- v_state / v_msg are PL/pgSQL variables: they survive the rollback below,
      -- which is why the assertions can sit outside it.
      raise exception using errcode = 'HRG31', message = '§4(i) done — restoring companion:heron';
    exception when sqlstate 'HRG31' then
      null;
    end;
    if (select progress_kind from public.hr_unlocks where unlock_id = 'companion:heron') <> 'unlock' then
      raise exception '§4(i): the nested rollback did NOT restore companion:heron''s shape';
    end if;
    if v_state = 'NO_RAISE' then
      raise exception '§4(i) NARROWNESS CONTROL FAILED: a flag-shaped catalogue row produced NO '
                      'raise — the handler swallowed a model violation (unlock_wrong_kind) and '
                      'answered %. The trigger''s protection is only real if this file re-raises '
                      'everything it does not own.', v_r;
    end if;
    if v_state <> '23514' or v_msg not like 'unlock_wrong_kind%' then
      raise exception '§4(i): expected the guard''s unlock_wrong_kind (23514) to propagate, got % / %',
                      v_state, v_msg;
    end if;

    -- ══ (j) THE GUARD ITSELF IS UNCHANGED. C1 translates a refusal; it must not
    --        have made the trigger optional. A direct uncatalogued unlock write
    --        is still refused by name.
    v_state := 'INSERTED'; v_msg := '';
    begin
      insert into public.player_progress (user_id, slot, kind, key, period_key, value)
        values (v_uid, 0, 'unlock', 'companion:__not_a_companion__', '', 1);
    exception when others then v_state := sqlstate; v_msg := sqlerrm;
    end;
    if v_state <> '23514' or v_msg not like 'unknown_unlock%' then
      raise exception '§4(j): player_progress_unlock_guard no longer refuses an uncatalogued unlock '
                      'row (% / %). The translation must sit ON TOP of the guard, never instead of it.',
                      v_state, v_msg;
    end if;

    raise exception using errcode = 'HRG28', message = '§4 complete — rolling back';
  exception when sqlstate 'HRG28' then
    null;
  end;

  -- Zero residue, in BOTH directions: no probe row survives, and the catalogue
  -- rows §4 deleted/mutated inside the subtransaction are all back.
  if exists (select 1 from public.player_state where user_id = v_uid)
     or exists (select 1 from public.player_progress where user_id = v_uid)
     or exists (select 1 from public.player_inventory where user_id = v_uid)
     or exists (select 1 from public.player_ledger where user_id = v_uid)
     or exists (select 1 from public.hr_rejections where user_id = v_uid)
     or exists (select 1 from auth.users where id = v_uid) then
    raise exception '§4 LEAKED a probe row';
  end if;
  if (select count(*) from public.hr_unlocks where namespace = 'companion') <> 21 then
    raise exception '§4 LEAKED a catalogue mutation: namespace=companion holds % rows, expected 21. '
                    '§4 deletes and re-shapes catalogue rows inside its rolled-back subtransaction; '
                    'if that rollback did not happen the database is now missing storage homes.',
                    (select count(*) from public.hr_unlocks where namespace = 'companion');
  end if;
  if exists (select 1 from public.hr_companion_grants g
              left join public.hr_unlocks u on u.unlock_id = 'companion:' || g.companion_id
             where u.unlock_id is null or u.progress_kind <> 'unlock' or u.merge <> 'max'
                or u.max_value <> 1 or u.rungs <> array[1]::int[]) then
    raise exception '§4 LEAKED a catalogue mutation: a grantable companion is missing or mis-shaped '
                    'in hr_unlocks after the rollback';
  end if;

  raise notice 'COMPANION-GRANT HARDENING OK — an ordinary grant is unchanged (row, version bump, '
               'owned projection, equippable) and a replay is still already_owned; unknown and shop '
               'ids are still not_grantable; C3: the ledger records claimed_source (the client''s '
               'contradicting claim, verbatim) separately from catalogue_source (the server''s own '
               'value) and no longer writes a bare `source`; C2: whelp without its egg answers '
               'missing_req_item and writes NOTHING, and grants + consumes exactly one egg when it '
               'is held; C1: a missing companion:<id> catalogue row answers '
               'unknown_unlock:companion:<id> instead of raising 23514, consumes no req_item and '
               'writes no row, on both the req_item and the no-req_item shapes; and the storage '
               'guard is untouched — a flag-shaped row still propagates unlock_wrong_kind and an '
               'uncatalogued unlock row is still refused. Zero residue.';
end $$;

do $$
begin
  raise notice 'companion-grant hardening INSTALLED — C1 (unknown_unlock machine code, two layers, '
               'narrow catch) + C2 (req_item ENFORCED) + C3 (claimed_source). '
               '⚠ This file is now the LAST TOUCHER of public.hr_companion_grant: re-applying '
               '2026-08-22-companion-grant.sql reverts all three, silently. Re-apply this file '
               'immediately after if you ever do.';
end $$;
