-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — THE SERVER FARM-GATE CATALOGUES  (GENERATED — DO NOT EDIT)
--
--   Generated by tools/gen-farm-catalogues.mjs from src/core/farm.js,
--   src/data/gathering.js, src/data/perks.js, src/core/perks.js and
--   src/data/companions.js. Any hand edit is reverted by the next generation
--   and FAILS `node tools/gen-farm-catalogues.mjs --check` (a preflight in
--   tests/run-smoke.mjs).
--
--   farm-catalogue digest: 9ecf382fe29a014be55a52f56a339566507c365e161d29822f450cf35262d768
--   9 crops (2 finite perennials) · 9 crop plot-tiers · 5 plot levels · 8 yield perks
--
-- Read by hr_farm_plant / hr_farm_harvest / hr_farm_water / hr_farm_upgrade_plot
-- (2026-08-22-server-farming-complete.sql). Numbers only; no client value
-- crosses. Idempotent: truncate+insert / update inside the migration
-- transaction. Apply BEFORE the RPC migration (which asserts every regrowing
-- crop carries a finite regrow_limit).
-- ════════════════════════════════════════════════════════════════════════

-- ── hr_crops.regrow_limit — the finite-perennial cap ─────────────────────
-- The column lives on the generated master catalogue (hr_crops); this ALTER
-- makes it exist on a database built by an older generator, and the UPDATE
-- fills the ONE farm-owned value from REGROW_LIMITS. 0 = non-regrow / legacy
-- infinite sentinel (unreachable on a regrowing crop — the assertion forbids it).
do $$
begin
  if to_regclass('public.hr_crops') is null then
    raise exception 'hr_crops absent — apply the master catalogue (gen-catalogues) first';
  end if;
end $$;
alter table public.hr_crops add column if not exists regrow_limit int not null default 0;

update public.hr_crops as k set regrow_limit = v.lim
  from (values
  ('carrot', 0),
  ('emberfruit', 4),
  ('goldenroot', 0),
  ('moonbloom', 0),
  ('potato', 0),
  ('pumpkin', 0),
  ('tomato', 4),
  ('turnip', 0),
  ('wheat', 0)
  ) as v(crop_id, lim)
 where k.crop_id = v.crop_id and k.regrow_limit is distinct from v.lim;

-- ── the three farm-gate catalogues ───────────────────────────────────────
do $$
begin
  if to_regclass('public.hr_crop_plot_tier') is null then
    create table public.hr_crop_plot_tier (
      crop_id   text primary key,
      plot_tier int  not null check (plot_tier between 1 and 5)
    );
    alter table public.hr_crop_plot_tier enable row level security;
  end if;
  if to_regclass('public.hr_plot_tier') is null then
    create table public.hr_plot_tier (
      plot_level int primary key check (plot_level between 1 and 5),
      deed_cost  int not null check (deed_cost >= 0)
    );
    alter table public.hr_plot_tier enable row level security;
  end if;
  if to_regclass('public.hr_farm_yield_perk') is null then
    create table public.hr_farm_yield_perk (
      perk_key   text primary key,
      farm_yield int  not null check (farm_yield >= 0)
    );
    alter table public.hr_farm_yield_perk enable row level security;
  end if;
end $$;

-- Read-only catalogues: readable by everyone signed in, written by NO client.
do $$
declare t text;
begin
  foreach t in array array['hr_crop_plot_tier','hr_plot_tier','hr_farm_yield_perk'] loop
    execute format('revoke all on public.%I from public, anon, authenticated, service_role', t);
    execute format('grant select on public.%I to anon, authenticated, service_role', t);
    execute format('drop policy if exists %I on public.%I', t || '_sel', t);
    execute format('create policy %I on public.%I for select using (true)', t || '_sel', t);
  end loop;
end $$;

truncate table public.hr_crop_plot_tier;
insert into public.hr_crop_plot_tier (crop_id, plot_tier) values
  ('carrot', 2),
  ('emberfruit', 5),
  ('goldenroot', 4),
  ('moonbloom', 5),
  ('potato', 3),
  ('pumpkin', 4),
  ('tomato', 3),
  ('turnip', 1),
  ('wheat', 2);

truncate table public.hr_plot_tier;
insert into public.hr_plot_tier (plot_level, deed_cost) values
  (1, 0),
  (2, 1),
  (3, 3),
  (4, 5),
  (5, 8);

truncate table public.hr_farm_yield_perk;
insert into public.hr_farm_yield_perk (perk_key, farm_yield) values
  ('garden:1', 1),
  ('garden:2', 2),
  ('garden:3', 4),
  ('garden:4', 6),
  ('garden:5', 8),
  ('scarecrow', 1),
  ('companion:bunny', 1),
  ('companion:squirrel', 1);

-- ── Self-verification ────────────────────────────────────────────────────
do $$
declare v_n int; v_bad int;
begin
  select count(*) into v_n from public.hr_crop_plot_tier;
  if v_n <> 9 then raise exception 'hr_crop_plot_tier has % rows, expected 9', v_n; end if;
  select count(*) into v_n from public.hr_plot_tier;
  if v_n <> 5 then raise exception 'hr_plot_tier has % rows, expected 5', v_n; end if;
  select count(*) into v_n from public.hr_farm_yield_perk;
  if v_n <> 8 then raise exception 'hr_farm_yield_perk has % rows, expected 8', v_n; end if;

  -- Every regrowing crop MUST carry a finite (>0) regrow_limit (no infinite
  -- perennial — arming the harvest RPC otherwise reverts the b420/b428 ruling).
  select count(*) into v_bad from public.hr_crops where regrows and regrow_limit <= 0;
  if v_bad > 0 then raise exception '% regrowing crop(s) have no finite regrow_limit', v_bad; end if;

  -- Every gated crop must be a real hr_crops row (the plant RPC joins them).
  select count(*) into v_bad from public.hr_crop_plot_tier c
    where not exists (select 1 from public.hr_crops k where k.crop_id = c.crop_id);
  if v_bad > 0 then raise exception '% plot-tier crops are absent from hr_crops', v_bad; end if;

  -- Level 1 must be free; no client write policy may exist on a catalogue.
  if (select deed_cost from public.hr_plot_tier where plot_level = 1) <> 0 then
    raise exception 'plot level 1 must cost 0 deeds';
  end if;
  select count(*) into v_bad from pg_policies
    where schemaname = 'public'
      and tablename in ('hr_crop_plot_tier','hr_plot_tier','hr_farm_yield_perk')
      and cmd in ('INSERT','UPDATE','DELETE','ALL');
  if v_bad > 0 then raise exception '% write policies on the farm catalogues', v_bad; end if;
end $$;
