-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — THE UNLOCK CATALOGUE  (GENERATED — DO NOT EDIT BY HAND)
--
--   Generated by tools/gen-unlocks.mjs from src/data/{shops,recipes,items,
--   perks}.js. Any hand edit here is reverted by the next generation and FAILS
--   `node tools/gen-unlocks.mjs --check`, a preflight in tests/run-smoke.mjs.
--
--   unlock digest: 82af81354e4d270a2830160ae387d149fd6229a5fdc2e34baae5dda19dba8341
--   62 unlock ids · bounty=5 · character_slot=4 · companion=4 · cosmetic=4 · dungeon_run=6 · entitlement=3 · farm_plot_tier=1 · plot=4 · property=5 · recipe=9 · room=8 · theme=6 · trait=2 · worker=1
--
-- ── WHAT THIS TABLE IS ──────────────────────────────────────────────────
-- BOOKKEEPING ONLY. For every unlock the game can grant: how two writes to it
-- COMBINE, which player_progress.kind stores it (i.e. WHO MAY WRITE IT), its
-- ceiling, and the rung ladder the shop actually sells. There is not one game
-- NUMBER in this file — no bonus magnitude, no price. `room:kitchen` is "a
-- level, rungs {1,2,3,4,5}"; the 0.25 noBurn lives in src/data/perks.js and is
-- read by src/core/perks.js on BOTH sides. Copying game data into SQL is the
-- failure src/main.js `unifyObject` was written about.
--
-- ── THE MERGE RULES, AS DECLARED ────────────────────────────────────────
--   bounty          merge=flag  kind=flag  
--                   Boolean bounty-board upgrades.
--   character_slot  merge=flag  kind=flag  
--                   Boolean per slot id.
--   companion       merge=flag  kind=flag  
--                   Owned or not.
--   cosmetic        merge=flag  kind=flag  
--                   Owned or not.
--   dungeon_run     merge=none  kind=null  
--                   A ONE-SHOT ACTION bought with a key item, with no persistent home.
--                   Filed as a stored unlock, a player banks dungeon_run:voidbringer =
--                   50 and nothing ever spends it. The intent that consumes it owns
--                   it.
--   entitlement     merge=flag  kind=flag  
--                   Owned or not.
--   farm_plot_tier  merge=max   kind=unlock
--                   A tier ladder with no colon in its id — the id IS the namespace.
--   plot            merge=count kind=stat  
--                   REPEATABLE. getBonus pays per INSTANCE owned, so the row holds a
--                   count and additive merge is correct. Two Scarecrows are +2
--                   farmYield.
--   property        merge=max   kind=unlock
--                   The homestead tier ladder; the capstone fires at tier 5.
--   recipe          merge=flag  kind=flag  
--                   THE ARTISAN GATE. Boolean, and it must be writable by the accrual
--                   engine through hr_apply when the engine's own drop roll yields the
--                   scroll — which is exactly what kind=flag buys. Additive is
--                   harmless: two scrolls read the same as one.
--   room            merge=max   kind=unlock
--                   A rung ladder. hr_apply must not be able to climb it additively.
--   theme           merge=flag  kind=flag  
--                   Owned or not.
--   trait           merge=flag  kind=flag  
--                   trait:auto_eat, and hr_set_auto_eat (applied, live) already reads
--                   kind='flag' and value > 0. Untouched by this catalogue.
--   worker          merge=count kind=stat  
--                   Repeatable hire, one id, no colon. Additive is correct.
--
-- CONSUMED BY: 2026-08-16-artisan-progress-model.sql — hr_unlock_guard (the
-- storage guard) and hr_unlock_levels (the perk seam) both read it, and both
-- FAIL CLOSED if it is absent or empty.
--
-- SAFE TO RE-RUN. The table is created if absent and refilled wholesale.
-- ════════════════════════════════════════════════════════════════════════

create table if not exists public.hr_unlocks (
  unlock_id     text primary key,
  namespace     text not null,
  merge         text not null check (merge in ('max','count','flag','none')),
  -- NULL iff merge='none'. A grant with no persistent home has no kind.
  progress_kind text check (progress_kind in ('flag','stat','unlock')),
  max_value     bigint,
  rungs         int[],
  check ((merge = 'none') = (progress_kind is null))
);

-- World-readable, like every other hr_* catalogue: it holds no player data and
-- the guard trigger reads it as an ordinary (non-DEFINER) function.
alter table public.hr_unlocks enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies
                  where schemaname='public' and tablename='hr_unlocks'
                    and policyname='hr_unlocks readable') then
    create policy "hr_unlocks readable" on public.hr_unlocks for select using (true);
  end if;
end $$;
-- IMPORTANT: "revoke all", NOT "revoke insert, update, delete" (Security C1,
-- 2026-08-16). Supabase's default ACL on public also grants TRUNCATE,
-- REFERENCES and TRIGGER, and a three-verb revoke leaves all three behind — on
-- a CATALOGUE, where TRUNCATE would empty the table every unlock decision is
-- read from, and TRUNCATE bypasses row-level security entirely so the
-- read-only policy above is not a backstop for it. PUBLIC is included because
-- a grant to PUBLIC is held by every role that exists.
revoke all on public.hr_unlocks from public, anon, authenticated, service_role;

-- Refilled wholesale, inside the migration's transaction.
delete from public.hr_unlocks;
insert into public.hr_unlocks
  (unlock_id, namespace, merge, progress_kind, max_value, rungs)
values
  ('bounty:auto_bounty_1', 'bounty', 'flag', 'flag', null, null),
  ('bounty:cosmetic_cape', 'bounty', 'flag', 'flag', null, null),
  ('bounty:free_reroll_2', 'bounty', 'flag', 'flag', null, null),
  ('bounty:mark_pouch', 'bounty', 'flag', 'flag', null, null),
  ('bounty:reroll_token', 'bounty', 'flag', 'flag', null, null),
  ('character_slot:1', 'character_slot', 'flag', 'flag', null, null),
  ('character_slot:2', 'character_slot', 'flag', 'flag', null, null),
  ('character_slot:3', 'character_slot', 'flag', 'flag', null, null),
  ('character_slot:4', 'character_slot', 'flag', 'flag', null, null),
  ('companion:honeybee', 'companion', 'flag', 'flag', null, null),
  ('companion:owl', 'companion', 'flag', 'flag', null, null),
  ('companion:raccoon', 'companion', 'flag', 'flag', null, null),
  ('companion:sparrow', 'companion', 'flag', 'flag', null, null),
  ('cosmetic:avatar_dragon', 'cosmetic', 'flag', 'flag', null, null),
  ('cosmetic:emote_pack', 'cosmetic', 'flag', 'flag', null, null),
  ('cosmetic:name_gold', 'cosmetic', 'flag', 'flag', null, null),
  ('cosmetic:pet_phoenix', 'cosmetic', 'flag', 'flag', null, null),
  ('dungeon_run:ancient_wyrm', 'dungeon_run', 'none', null, null, null),
  ('dungeon_run:crypt_of_bones', 'dungeon_run', 'none', null, null, null),
  ('dungeon_run:goblin_warcamp', 'dungeon_run', 'none', null, null, null),
  ('dungeon_run:haunted_archive', 'dungeon_run', 'none', null, null, null),
  ('dungeon_run:obsidian_keep', 'dungeon_run', 'none', null, null, null),
  ('dungeon_run:voidbringer', 'dungeon_run', 'none', null, null, null),
  ('entitlement:hearthHall', 'entitlement', 'flag', 'flag', null, null),
  ('entitlement:noAds', 'entitlement', 'flag', 'flag', null, null),
  ('entitlement:offlinePlus', 'entitlement', 'flag', 'flag', null, null),
  ('farm_plot_tier', 'farm_plot_tier', 'max', 'unlock', 5, array[2,3,4,5]::int[]),
  ('plot:farm_plot', 'plot', 'count', 'stat', 12, null),
  ('plot:scarecrow', 'plot', 'count', 'stat', 2, null),
  ('plot:toolshed', 'plot', 'count', 'stat', 1, null),
  ('plot:watchtower', 'plot', 'count', 'stat', 1, null),
  ('property:castle', 'property', 'max', 'unlock', 5, array[5]::int[]),
  ('property:farmstead', 'property', 'max', 'unlock', 2, array[2]::int[]),
  ('property:homestead', 'property', 'max', 'unlock', 1, array[1]::int[]),
  ('property:keep', 'property', 'max', 'unlock', 4, array[4]::int[]),
  ('property:manor', 'property', 'max', 'unlock', 3, array[3]::int[]),
  ('recipe:alpha_pattern', 'recipe', 'flag', 'flag', null, null),
  ('recipe:captain_recipe', 'recipe', 'flag', 'flag', null, null),
  ('recipe:chief_blade_recipe', 'recipe', 'flag', 'flag', null, null),
  ('recipe:dragon_marrow_recipe', 'recipe', 'flag', 'flag', null, null),
  ('recipe:field_cookbook', 'recipe', 'flag', 'flag', null, null),
  ('recipe:gemcutter_note', 'recipe', 'flag', 'flag', null, null),
  ('recipe:marrow_cookbook', 'recipe', 'flag', 'flag', null, null),
  ('recipe:soul_recipe', 'recipe', 'flag', 'flag', null, null),
  ('recipe:spellstone_diagram', 'recipe', 'flag', 'flag', null, null),
  ('room:cellar', 'room', 'max', 'unlock', 5, array[1,2,3,4,5]::int[]),
  ('room:forge', 'room', 'max', 'unlock', 5, array[1,2,3,4,5]::int[]),
  ('room:garden', 'room', 'max', 'unlock', 5, array[1,2,3,4,5]::int[]),
  ('room:kitchen', 'room', 'max', 'unlock', 5, array[1,2,3,4,5]::int[]),
  ('room:library', 'room', 'max', 'unlock', 5, array[1,2,3,4,5]::int[]),
  ('room:shrine', 'room', 'max', 'unlock', 5, array[1,2,3,4,5]::int[]),
  ('room:trophy', 'room', 'max', 'unlock', 5, array[1,2,3,4,5]::int[]),
  ('room:workshop', 'room', 'max', 'unlock', 5, array[1,2,3,4,5]::int[]),
  ('theme:default', 'theme', 'flag', 'flag', null, null),
  ('theme:desert', 'theme', 'flag', 'flag', null, null),
  ('theme:fairy', 'theme', 'flag', 'flag', null, null),
  ('theme:forest', 'theme', 'flag', 'flag', null, null),
  ('theme:volcanic', 'theme', 'flag', 'flag', null, null),
  ('theme:winter', 'theme', 'flag', 'flag', null, null),
  ('trait:auto_eat', 'trait', 'flag', 'flag', null, null),
  ('trait:auto_eat_2', 'trait', 'flag', 'flag', null, null),
  ('worker', 'worker', 'count', 'stat', 1, null);

-- ── SELF-CHECK ───────────────────────────────────────────────────────────
do $$
declare v_n int; v_bad text;
begin
  select count(*) into v_n from public.hr_unlocks;
  if v_n <> 62 then
    raise exception 'hr_unlocks holds % rows, expected 62 — the insert was partial', v_n;
  end if;

  -- Every level has a ladder, every ladder is inside its ceiling, and no ladder
  -- contains 0. That last one is load-bearing: the storage guard proves "a value
  -- off the ladder is refused" with an INSERT at 0, and if 0 were ON some ladder
  -- that probe would assert nothing.
  select string_agg(unlock_id, ', ') into v_bad from public.hr_unlocks
   where merge = 'max'
     and (rungs is null or array_length(rungs,1) is null
          or max_value is null or max_value <> rungs[array_length(rungs,1)]
          or 0 = any (rungs));
  if v_bad is not null then
    raise exception 'level unlocks with a broken ladder: %', v_bad;
  end if;

  -- merge='none' really has no home, and nothing else is missing one.
  select string_agg(unlock_id, ', ') into v_bad from public.hr_unlocks
   where (merge = 'none') <> (progress_kind is null);
  if v_bad is not null then raise exception 'merge/kind disagree on: %', v_bad; end if;

  -- THE ARTISAN GATE IS PRESENT AND WRITABLE BY THE ENGINE. If recipe unlocks
  -- were not kind='flag', hr_apply could not grant a scroll the engine rolled
  -- and every gated recipe would be permanently unreachable server-side.
  select count(*) into v_n from public.hr_unlocks
   where namespace = 'recipe' and progress_kind = 'flag' and merge = 'flag';
  if v_n < 9 then
    raise exception 'the recipe namespace lost its flag storage — % of 9 rows', v_n;
  end if;

  raise notice 'hr_unlocks OK — % ids, bounty=5 · character_slot=4 · companion=4 · cosmetic=4 · dungeon_run=6 · entitlement=3 · farm_plot_tier=1 · plot=4 · property=5 · recipe=9 · room=8 · theme=6 · trait=2 · worker=1', 62;
end $$;
