-- ════════════════════════════════════════════════════════════════════════
-- Hearthrise — THE SERVER RAID-CHEST REWARD CATALOGUE  (GENERATED — DO NOT EDIT)
--
--   Generated by tools/gen-raid-boss-rewards.mjs from src/data/raid-bosses.js.
--   Any hand edit is reverted by the next generation and FAILS
--   `node tools/gen-raid-boss-rewards.mjs --check` (a preflight in
--   tests/run-smoke.mjs).
--
--   raid-boss-reward digest: ed3601a1d1e5bdeb1798617557bfcf77e41e62a6411bf80c88af018171ce1569
--   6 raid bosses · ordinal = RAID_BOSSES array index (solo rotation) ·
--   material_ids in reward.items key order (solo slices the first two)
--
-- Read by raid_claim (2026-08-22-raid-chest-items.sql) to mint chest materials +
-- signature into player_inventory. Numbers/ids only; no client value crosses.
-- Idempotent: truncate+insert inside the migration transaction. Apply BEFORE the
-- raid_claim body migration (which asserts every boss row exists + sig parity).
-- ════════════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.hr_hunt_boss_reward') is null then
    create table public.hr_hunt_boss_reward (
      boss_id      text primary key,
      ordinal      int  not null,
      sig_item     text not null,
      material_ids text[] not null check (array_length(material_ids, 1) >= 1)
    );
    alter table public.hr_hunt_boss_reward enable row level security;
  end if;
end $$;

-- Read-only catalogue: readable by everyone signed in, written by NO client.
do $$
begin
  revoke all on public.hr_hunt_boss_reward from public, anon, authenticated, service_role;
  grant select on public.hr_hunt_boss_reward to anon, authenticated, service_role;
  drop policy if exists hr_hunt_boss_reward_sel on public.hr_hunt_boss_reward;
  create policy hr_hunt_boss_reward_sel on public.hr_hunt_boss_reward for select using (true);
end $$;

truncate table public.hr_hunt_boss_reward;
insert into public.hr_hunt_boss_reward (boss_id, ordinal, sig_item, material_ids) values
  ('emberclad_tyrant', 0, 'slagheart_core', array['mithril_bar', 'hell_ember']::text[]),
  ('hollow_regent', 1, 'hollow_sigil', array['ancient_rune', 'grave_dust']::text[]),
  ('maw_below', 2, 'abyssal_pearl', array['dragon_scale', 'silk_thread']::text[]),
  ('sunken_choir', 3, 'choirbone', array['void_chitin', 'ancient_rune', 'shadow_thread']::text[]),
  ('warden_long_dark', 4, 'warden_seal', array['death_steel', 'void_chitin', 'ruby']::text[]),
  ('crownless_wyrm', 5, 'wyrm_gilding', array['dragon_scale', 'dragon_bones', 'hell_ember']::text[]);

-- ── Self-verification ────────────────────────────────────────────────────
do $$
declare v_n int; v_bad int;
begin
  select count(*) into v_n from public.hr_hunt_boss_reward;
  if v_n <> 6 then raise exception 'hr_hunt_boss_reward has % rows, expected 6', v_n; end if;

  -- Dense 0..n-1 ordinals (the solo rotation indexes modulo the row count).
  select count(*) into v_bad from public.hr_hunt_boss_reward
    where ordinal not between 0 and 5;
  if v_bad > 0 then raise exception '% boss reward rows have an out-of-range ordinal', v_bad; end if;
  if (select count(distinct ordinal) from public.hr_hunt_boss_reward) <> 6 then
    raise exception 'boss reward ordinals are not distinct 0..5';
  end if;

  -- No write policy may exist on the catalogue.
  select count(*) into v_bad from pg_policies
    where schemaname = 'public' and tablename = 'hr_hunt_boss_reward'
      and cmd in ('INSERT','UPDATE','DELETE','ALL');
  if v_bad > 0 then raise exception '% write policies on hr_hunt_boss_reward', v_bad; end if;

  -- SIG PARITY: every boss's signature here must equal hr_hunt_bosses.sig_item
  -- (the catalogue already used by the claim payout), so the two never diverge.
  if to_regclass('public.hr_hunt_bosses') is not null then
    select count(*) into v_bad from public.hr_hunt_boss_reward r
      join public.hr_hunt_bosses b on b.boss_id = r.boss_id
     where b.sig_item is distinct from r.sig_item;
    if v_bad > 0 then raise exception '% boss reward rows disagree with hr_hunt_bosses.sig_item', v_bad; end if;
  end if;
end $$;
