-- ════════════════════════════════════════════════════════════════════════
-- 2026-09-10-dungeon-settle.sql — hr_dungeon_settle: THE SERVER WRITER FOR
--                                 DUNGEON SCRIP + RUN LOOT.
--                                 (§2 of docs/design/dungeon-settlement.md)
--
-- ⚠⚠⚠ REVIEW ONLY — NOT AUTO-APPLIED. The Coordinator applies this by hand
--     (execute_sql wrapped in begin/commit, or a Supabase branch apply) AFTER
--     the security review. It is a PROGRESSION surface: it credits the
--     server-owned Dungeon Scrip currency and run loot, and consumes the entry
--     key from inventory. Security review required before authority moves.
--
--   Reads:   2026-09-10-dungeon-catalogue.generated.sql (hr_dungeons /
--            hr_dungeon_loot) and player_state.dungeon_scrip
--            (2026-09-10-dungeon-scrip.sql). FAILS CLOSED without either.
--   Edge:    supabase/functions/hr-accrue/dungeon-settle.js (the ONLY caller)
--   Client:  src/dungeons.js / src/dungeon-scavenger.js (send the intent,
--            reconcile scrip + loot from the returned envelope)
--   Test:    tests/dungeon-settle.mjs (PGlite replay + mutation proof)
--
-- ⚠ AFTER APPLYING: this file re-derives hr_assert_grant_hygiene (§5, the
--   ⟦DERIVED⟧ block, generated by tools/derive-grant-hygiene.mjs) to admit the
--   ONE new engine grant. It becomes the CURRENT LAST TOUCHER of
--   hr_assert_grant_hygiene — LINKS[6] / HR_GRANT_HYGIENE_CHAIN's seventh link.
--   The detector is ALSO a live-hash-tracked body; re-seed the baseline with
--   `node tests/live-hash-drift.mjs --live --write` after the apply. It TAKES
--   OVER NO OTHER last-toucher role — hr_state_of is patched by the sibling
--   2026-09-10-dungeon-scrip.sql, not here.
--
-- ── WHAT THIS DOES, AND WHY ─────────────────────────────────────────────────
-- Dungeon scrip + run loot are minted CLIENT-side today (awardDungeonScrip /
-- awardLoot → window.addItem / G.inventory) with NO server write, so BLOB_RETIRED
-- wipes them on reload — the reported "dungeon scrip goes to 0" P1
-- (dungeon-settlement.md §0). This RPC settles a run ONCE, in ONE transaction:
--   · consumes the entry KEY from player_inventory (a run costs a real
--     server-held key — the b501 key drops folded into combat drops made keys
--     server-settled, which is the hard prerequisite for this);
--   · rolls each loot row with the SEEDED server PRNG (hr_seed) from the
--     generated catalogue and credits survivors into player_inventory;
--   · credits round(scrip_base * clamp(p_quality,0,1)) into
--     player_state.dungeon_scrip;
--   · bumps version, journals ONE kind='dungeon' row, and returns the hr_state_of
--     envelope + a `settled` receipt.
-- The template is hr_unlock_buy (2026-08-16-unlock-buy.sql): engine-only, one
-- protected block that raises through hr_reject → HR000 → rollback, idempotency
-- on player_intents via hr_intent_replay, per-day clamp from the append-only
-- ledger, self-verifying commit gate.
--
-- ── ANTI-FORGERY (why a forged client value mints nothing across a boundary) ─
-- The ONLY client-authored number is p_quality, and it is CLAMPED server-side to
-- [0,1] and scales SELF-ONLY scrip — never loot. Loot is a pure server-RNG roll
-- of the generated catalogue (rates + ids the client cannot name or price),
-- salted with the 256-bit server secret via hr_seed, so the next roll is not
-- computable in devtools. The entry key is debited from the caller's OWN
-- inventory. The cooldown and the per-day scrip cap read now() and the ledger.
-- The catalogues are client-UNREADABLE. So: a forged p_quality gains at most the
-- top of a fixed band on the caller's OWN scrip; a forged p_dungeon_id →
-- unknown_dungeon; a forged p_mode → bad_mode. Scrip is self-only (never traded),
-- so CLAUDE.md's target property — "a forged client value cannot cross into
-- ANOTHER player's economy or ranking" — holds: there is no cross-player surface.
--
--   ⚠ FLAGGED FOR THE GAME DESIGNER + SECURITY (a deliberate change, not a bug):
--     · LOOT NO LONGER SCALES WITH THE CLEAR. The client scaled manual/scavenger
--       loot qty by clear fraction (0.4x–2x) and added a BoP-chance bonus; this
--       RPC pays the FLAT catalogue roll regardless of mode/quality. That removes
--       the client's arithmetic lever over loot entirely (the server-authority
--       win) but IS a payout change the Designer should sign off. If a
--       clear-scaled loot multiplier is wanted, it belongs in the catalogue /
--       server, keyed off a SERVER-verifiable clear signal, not p_quality.
--     · Most dungeon loot is ORDINARY TRADEABLE material (26 of 33 ids); only 7
--       signature spoils are BoP. That is fine — loot is server-authored exactly
--       like a combat drop and gated by real server-held keys — but it means the
--       reward set is NOT "BoP-only". The bop flag is carried in the catalogue +
--       the journal so a future BoP-only policy has the fact to assert against.
--     · TWO BLAST-RADIUS FUSES, not balance (the clan_deposit posture; Designer
--       ruling 2026-09-05): c_daily_scrip_cap = 5,000 GROSS-EARNED scrip/UTC-day
--       (positive settle rows only — a Quartermaster spend never reduces it, or a
--       spend→earn→spend loop would launder the ceiling) and c_daily_count_cap =
--       250 SETTLES/UTC-day (anti-replay insurance; counts meta.op='settle' only,
--       so QM spend rows do not touch it). Over either → daily_cap, with a `dim`
--       of 'scrip' | 'count'. Tune as Designer numbers; both are far above honest
--       play and far below "grind the whole shop in a day".
--
-- ── WHAT IT DELIBERATELY DOES NOT DO ────────────────────────────────────────
--   · It does NOT stamp accrued_to. A run is not an activity change, so the
--     unpaid accrual window survives it (hr_unlock_buy's rule).
--   · It does NOT re-grant keys. Keys are ordinary server-rolled combat drops
--     (b501); this RPC only CONSUMES one as the entry gate.
--   · It does NOT consult hr_day_budget_check. That ceiling is on GROSS INFLOW;
--     the reward is a fixed server-owned grant kept OUT of the accrual budget
--     (qty_in/gold_in/xp_in = 0 explicit), like the muster credit.
--
-- ── REVERSIBILITY ───────────────────────────────────────────────────────────
--   drop function public.hr_dungeon_settle(uuid,int,bigint,uuid,text,text,numeric);
--   -- re-apply 2026-09-10-attended-loot-credit.sql (link 7, the base this body
--   --   was rebased onto for b504) to restore hr_assert_grant_hygiene WITHOUT the
--   --   dungeon_settle allowlist entry but WITH the hr_attended_kills entry — NOT
--   --   2026-08-20-live-progress-engine-allow.sql, which would also revert link 7.
--   The scrip / loot / ledger rows it wrote are ordinary player rows and survive.
--   The dungeon catalogues are dropped by re-running their own generated file's
--   revert; nothing here alters them.
--
-- SAFE TO RE-RUN. Every step is guarded and §6's probes roll themselves back.
-- ════════════════════════════════════════════════════════════════════════

-- ── 0. PRECONDITIONS — FAIL CLOSED ─────────────────────────────────────────
do $$
begin
  if to_regclass('public.player_state')     is null then raise exception 'player_state missing — apply 2026-08-11-player-state.sql first'; end if;
  if to_regclass('public.player_inventory') is null then raise exception 'player_inventory missing'; end if;
  if to_regclass('public.player_ledger')    is null then raise exception 'player_ledger missing'; end if;
  if to_regclass('public.player_intents')   is null then raise exception 'player_intents missing'; end if;
  if to_regclass('public.player_skills')    is null then raise exception 'player_skills missing'; end if;

  -- The scrip column this verb credits (§1's sibling migration). Without it the
  -- whole currency arm is unreachable.
  if (select count(*) from information_schema.columns
       where table_schema='public' and table_name='player_state' and column_name='dungeon_scrip') <> 1 then
    raise exception 'player_state.dungeon_scrip is absent — apply 2026-09-10-dungeon-scrip.sql first';
  end if;

  -- The generated catalogues this verb reads. Present-and-empty is as fatal as
  -- absent: it would refuse every dungeon (unknown_dungeon) or roll no loot.
  if to_regclass('public.hr_dungeons') is null or to_regclass('public.hr_dungeon_loot') is null then
    raise exception 'hr_dungeons / hr_dungeon_loot are absent — apply '
                    '2026-09-10-dungeon-catalogue.generated.sql first';
  end if;
  if (select count(*) from public.hr_dungeons) = 0 then
    raise exception 'hr_dungeons is empty — regenerate (node tools/gen-dungeon-catalogue.mjs). '
                    'Installed against an empty catalogue this verb would answer unknown_dungeon '
                    'to every run in the game.';
  end if;
  if (select count(*) from public.hr_dungeon_loot) = 0 then
    raise exception 'hr_dungeon_loot is empty — regenerate. A run would credit no loot.';
  end if;

  -- The primitives this verb copies from hr_unlock_buy statement for statement.
  if to_regprocedure('public.hr_reject(text,jsonb)') is null
     or to_regprocedure('public.hr_record_rejection(uuid,int,text,text,jsonb,bigint)') is null then
    raise exception 'hr_reject / hr_record_rejection are missing — apply the apply-engine chain first';
  end if;
  if to_regprocedure('public.hr_seed(uuid,int,text)') is null then
    raise exception 'hr_seed is missing — apply 2026-08-11-player-state.sql first. Math.random() is '
                    'banned server-side; loot must roll from the seeded server PRNG.';
  end if;
  if to_regprocedure('public.hr_utc_day_key(timestamptz)') is null then
    raise exception 'hr_utc_day_key is missing — apply 2026-08-08-clan-seat.sql first';
  end if;
  if to_regprocedure('public.hr_intent_replay(uuid,int,uuid,text)') is null then
    raise exception 'hr_intent_replay is absent — apply 2026-09-03-intent-mismatch-class.sql first. '
                    'This verb reads the shared player_intents namespace and must compare the stored '
                    'intent and slot, not merely the key.';
  end if;
  if to_regprocedure('public.hr_lb_combat_level(int,int,int,int,int,int,int)') is null
     or to_regprocedure('public.hr_level_from_xp(bigint)') is null then
    raise exception 'hr_lb_combat_level / hr_level_from_xp are missing — apply the leaderboard-source '
                    'chain first. The req_lv gate derives combat level from player_skills with the '
                    'SAME formula, never a client level.';
  end if;
  if to_regprocedure('public.hr_rate_ok(uuid,text,int,interval)') is null then
    raise exception 'hr_rate_ok is missing — apply the rate chain first';
  end if;
  if to_regclass('public.hr_server_secrets') is null then
    raise exception 'hr_server_secrets is missing — hr_seed has no secret to salt with';
  end if;
end $$;

-- ── 1. player_ledger.kind must admit 'dungeon' — PROGRAMMATIC, ADDITIVE ────
-- Inserted at an anchor rather than restating the array (the 2026-09-08-hero-slot
-- precedent), so it removes nothing and cannot silently delete a kind a later
-- file added if it is re-applied out of order.
do $$
declare v_def text; v_new text;
begin
  select pg_get_constraintdef(oid) into v_def from pg_constraint
   where conrelid = 'public.player_ledger'::regclass and conname = 'player_ledger_kind_check';
  if v_def is null then
    raise exception 'player_ledger_kind_check is absent — this verb''s journal row would be '
                    'unconstrained, and every other writer assumes the constraint exists';
  end if;
  if position('''dungeon''' in v_def) > 0 then
    raise notice 'player_ledger.kind already admits ''dungeon'' — widen skipped';
    return;
  end if;
  if position('''accrue''::text' in v_def) = 0 then
    raise exception 'player_ledger_kind_check has no ''accrue''::text anchor (%) — refusing to '
                    'rewrite a constraint whose shape this file cannot account for', v_def;
  end if;
  v_new := replace(v_def, '''accrue''::text', '''dungeon''::text, ''accrue''::text');
  execute 'alter table public.player_ledger drop constraint player_ledger_kind_check';
  execute 'alter table public.player_ledger add constraint player_ledger_kind_check ' || v_new;
  raise notice 'player_ledger.kind widened to admit ''dungeon'' (insertion, nothing removed)';
end $$;

-- ── 2. hr_dungeon_settle ───────────────────────────────────────────────────
-- The sequence is hr_unlock_buy's, deliberately: identity seam → catalogue (no
-- lock) → rate → advisory lock → idempotency → protected block (row lock,
-- version, gates, key debit, loot roll, scrip credit, journal) → record the
-- decision.
create or replace function public.hr_dungeon_settle(
  p_user uuid, p_slot int, p_version bigint, p_intent_id uuid,
  p_dungeon_id text, p_mode text, p_quality numeric)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  -- BLAST RADIUS, not balance (the clan_deposit / hr_unlock_buy rule). Far above
  -- honest play (each run yields <= 57 scrip and costs a real server-held key),
  -- far below "grind the whole Quartermaster in a day". Designer-tunable fuses
  -- (ruling 2026-09-05): 5,000 GROSS-EARNED scrip/UTC-day and 250 settles/UTC-day.
  c_daily_scrip_cap constant bigint := 5000;
  -- Per-day settle COUNT fuse (anti-replay insurance): 250 settles/UTC-day, all
  -- dungeons + modes combined. NOT 25 — 250 is the ruling.
  c_daily_count_cap constant int := 250;

  v_uid    uuid;
  v_role   text;
  v_slot   int := coalesce(p_slot, 0);
  v_dun    public.hr_dungeons%rowtype;
  v_st     public.player_state%rowtype;
  v_cached jsonb;
  v_intent text;
  v_out    jsonb;
  v_settled jsonb;
  v_msg text; v_det text; v_sqlstate text;
  v_clv    int;
  v_q      numeric;
  v_scrip  bigint;
  v_today  bigint;
  v_count_today int;
  v_last_auto timestamptz;
  v_key    text;
  v_have   bigint;
  v_items  jsonb := '{}'::jsonb;
  v_qty_total bigint := 0;
  v_day    text;
  r        record;
  v_rc     numeric; v_rq numeric; v_qty bigint;
begin
  -- ── (0) IDENTITY SEAM. hr_unlock_buy's, verbatim in effect: the engine may
  --        act for a user it has already verified; nobody else may name a user.
  --        current_user is the OWNER inside a definer function, so the ROLE GUC
  --        is what is read.
  v_role := coalesce(nullif(current_setting('role', true), 'none'), session_user);
  if v_role = 'hr_engine' then
    v_uid := coalesce(p_user, auth.uid());
  else
    v_uid := auth.uid();
    if p_user is not null and p_user is distinct from v_uid then
      perform public.hr_record_rejection(v_uid, v_slot, 'dungeon_settle', 'forbidden_impersonation',
        jsonb_build_object('claimed_user', p_user, 'role', v_role));
      return jsonb_build_object('ok', false, 'error', 'forbidden_impersonation');
    end if;
  end if;
  if v_uid is null then return jsonb_build_object('ok', false, 'error', 'not_signed_in'); end if;
  if p_intent_id is null then return jsonb_build_object('ok', false, 'error', 'missing_intent_id'); end if;

  -- ── (1) SHAPE + CATALOGUE, BEFORE ANY LOCK. A refusal that is a fact about
  --        the request or the catalogue needs no character and no lock, so a
  --        client looping on a bad id cannot contend on a real player's row.
  if p_mode is null or p_mode not in ('auto', 'manual', 'scavenger') then
    return jsonb_build_object('ok', false, 'error', 'bad_mode', 'mode', p_mode);
  end if;
  if p_dungeon_id is null then
    return jsonb_build_object('ok', false, 'error', 'unknown_dungeon');
  end if;
  select * into v_dun from public.hr_dungeons where dungeon_id = p_dungeon_id;
  if v_dun.dungeon_id is null then
    return jsonb_build_object('ok', false, 'error', 'unknown_dungeon',
      'detail', jsonb_build_object('dungeon', p_dungeon_id));
  end if;
  -- The name carries the dungeon AND the mode, because intent_mismatch compares
  -- exactly this string and the mode changes what the write does (auto pays a
  -- cooldown, manual/scavenger do not).
  v_intent := 'dungeon_settle:' || v_dun.dungeon_id || ':' || p_mode;

  -- ── (2) RATE. The `apply` budget, NOT a new namespace (hr_unlock_buy's rule:
  --        a second writer with its own allowance doubles a compromised engine's
  --        reachable write rate). Outside the protected block, sampled.
  if not public.hr_rate_ok(v_uid, 'apply', 240, interval '1 minute') then
    if public.hr_rate_sample_weight(public.hr_rate_over(v_uid, 'apply') - 240) > 0 then
      perform public.hr_record_rejection(v_uid, v_slot, 'dungeon_settle', 'rate_limited',
        jsonb_build_object('limit', 240, 'per', '1 minute'),
        public.hr_rate_sample_weight(public.hr_rate_over(v_uid, 'apply') - 240));
    end if;
    return jsonb_build_object('ok', false, 'error', 'rate_limited');
  end if;

  -- ── (3) SERIALISE THIS CHARACTER — the SAME advisory key hr_apply takes, so a
  --        settle cannot race an accrual on one character.
  perform pg_advisory_xact_lock(hashtextextended(v_uid::text || ':' || v_slot::text, 0));

  -- ── (4) IDEMPOTENCY, per (KEY, INTENT, SLOT). player_intents is ONE namespace
  --        for every verb, so a key claimed for another intent/slot is REFUSED,
  --        not answered with that intent's decision. ONLY SUCCESSES ARE CACHED
  --        (see §(5)); a matching success replays with FRESH state + the original
  --        settled receipt + replayed:true (the hr_unlock_buy replay shape).
  select public.hr_intent_replay(v_uid, v_slot, p_intent_id, v_intent) into v_cached;
  if v_cached ->> 'error' = 'intent_mismatch' then return v_cached; end if;
  if v_cached is not null then
    return public.hr_state_of(v_uid, v_slot) || v_cached || jsonb_build_object('replayed', true);
  end if;

  -- ══ THE PROTECTED BLOCK ═══════════════════════════════════════════════════
  -- All-or-nothing. Every rejection raises through hr_reject (HR000) and the
  -- handler undoes the whole block, so there is no state in which the key left
  -- and the reward did not arrive (or vice versa).
  begin
    select * into v_st from public.player_state
      where user_id = v_uid and slot = v_slot for update;
    if v_st.user_id is null then perform public.hr_reject('no_character'); end if;

    -- (a) OPTIMISTIC CONCURRENCY — MANDATORY. A missing version IS a conflict.
    if p_version is null or p_version <> v_st.version then
      perform public.hr_reject('version_conflict', jsonb_build_object('version', v_st.version));
    end if;

    -- (b) COMBAT LEVEL >= req_lv — derived from player_skills with the SAME
    --     formula the leaderboard uses (hr_lb_combat_level), never a client
    --     level. Unlevelled skills coalesce to level 1, matching src/core/xp.js.
    select public.hr_lb_combat_level(
      coalesce(max(public.hr_level_from_xp(xp)) filter (where skill_id = 'attack'),    1),
      coalesce(max(public.hr_level_from_xp(xp)) filter (where skill_id = 'strength'),  1),
      coalesce(max(public.hr_level_from_xp(xp)) filter (where skill_id = 'defense'),   1),
      coalesce(max(public.hr_level_from_xp(xp)) filter (where skill_id = 'hitpoints'), 1),
      coalesce(max(public.hr_level_from_xp(xp)) filter (where skill_id = 'prayer'),    1),
      coalesce(max(public.hr_level_from_xp(xp)) filter (where skill_id = 'ranged'),    1),
      coalesce(max(public.hr_level_from_xp(xp)) filter (where skill_id = 'magic'),     1))
      into v_clv
      from public.player_skills where user_id = v_uid and slot = v_slot;
    v_clv := coalesce(v_clv, 1);
    if v_clv < v_dun.req_lv then
      perform public.hr_reject('level_locked',
        jsonb_build_object('have', v_clv, 'need', v_dun.req_lv));
    end if;

    -- (c) COOLDOWN — auto mode only, read from now() + the append-only ledger
    --     (never a stored counter a client can reset: the b288 lesson). Manual
    --     and scavenger deliberately have no cooldown; their limiter is the key
    --     debit + the per-day scrip cap.
    if p_mode = 'auto' and v_dun.cooldown_s > 0 then
      select max(at) into v_last_auto from public.player_ledger
       where user_id = v_uid and slot = v_slot and kind = 'dungeon'
         and meta->>'dungeon' = v_dun.dungeon_id and meta->>'mode' = 'auto';
      if v_last_auto is not null
         and now() < v_last_auto + make_interval(secs => v_dun.cooldown_s) then
        perform public.hr_reject('on_cooldown',
          jsonb_build_object('ready_at', v_last_auto + make_interval(secs => v_dun.cooldown_s)));
      end if;
    end if;

    -- (d) SCRIP. Clamp the ONE client value to [0,1], SELF-ONLY, and apply it to
    --     the server-owned base. round(base * clamp) — the awardDungeonScrip
    --     formula, now server-owned.
    v_q := least(greatest(coalesce(p_quality, 1), 0), 1);
    v_scrip := round(v_dun.scrip_base * v_q)::bigint;

    -- (e) PER-DAY SCRIP EARN CAP (blast radius) — summed from the append-only
    --     ledger for this character-day, the clan_deposit pattern. Checked BEFORE
    --     the key is debited, so a capped-out run costs no key.
    --     ⚠ POSITIVE-SCRIP ROWS ONLY (Designer ruling 2026-09-05, Condition-3):
    --     the sum GROSS-EARNS. A Quartermaster spend (kind='dungeon',
    --     meta.op='qm_buy', meta.scrip < 0 — 2026-09-11-quartermaster-buy.sql)
    --     must NOT reduce the cap's used total, or a spend→earn→spend loop would
    --     launder the daily earn ceiling. The `(meta->>'scrip')::bigint > 0` filter
    --     is EXPLICIT (not "sum every dungeon row") precisely so a future QM-row
    --     shape change can never fold a spend back into the earn sum.
    v_day := public.hr_utc_day_key(now());
    select coalesce(sum((meta->>'scrip')::bigint), 0) into v_today
      from public.player_ledger
     where user_id = v_uid and slot = v_slot and kind = 'dungeon'
       and (meta->>'scrip')::bigint > 0
       and public.hr_utc_day_key(at) = v_day;
    if v_today + v_scrip > c_daily_scrip_cap then
      perform public.hr_reject('daily_cap',
        jsonb_build_object('dim', 'scrip', 'used', v_today, 'add', v_scrip,
                           'limit', c_daily_scrip_cap, 'day', v_day));
    end if;

    -- (e2) PER-DAY SETTLE COUNT CAP (anti-replay insurance, Designer ruling
    --      2026-09-05): at most 250 SETTLES/UTC-day, all dungeons + modes combined.
    --      Counts SETTLE rows only (meta.op='settle'); a Quartermaster spend
    --      (meta.op='qm_buy') is not a settle and is deliberately excluded, so the
    --      count fuse cannot be inflated or evaded by QM traffic. Checked BEFORE
    --      the key debit too, so a count-capped run costs no key.
    select count(*) into v_count_today
      from public.player_ledger
     where user_id = v_uid and slot = v_slot and kind = 'dungeon'
       and meta->>'op' = 'settle'
       and public.hr_utc_day_key(at) = v_day;
    if v_count_today >= c_daily_count_cap then
      perform public.hr_reject('daily_cap',
        jsonb_build_object('dim', 'count', 'used', v_count_today,
                           'limit', c_daily_count_cap, 'day', v_day));
    end if;

    -- (f) THE KEY — present + consumed under the row lock. THE load-bearing gate:
    --     a run costs a real server-held key (b501 folded key drops into combat
    --     drops, so keys live in player_inventory). Without a key the settle
    --     refuses; keys are never re-granted here.
    v_key := v_dun.cost_key;
    select qty into v_have from public.player_inventory
     where user_id = v_uid and slot = v_slot and item_id = v_key for update;
    v_have := coalesce(v_have, 0);
    if v_have < 1 then
      perform public.hr_reject('insufficient_item',
        jsonb_build_object('item_id', v_key, 'have', v_have, 'need', 1));
    end if;
    if v_have = 1 then
      delete from public.player_inventory
       where user_id = v_uid and slot = v_slot and item_id = v_key;
    else
      update public.player_inventory set qty = v_have - 1
       where user_id = v_uid and slot = v_slot and item_id = v_key;
    end if;

    -- (g) LOOT — SERVER-ROLLED from the generated catalogue with the SEEDED
    --     PRNG, and NOT scaled by any client value (p_quality touches scrip
    --     only), so a forged quality cannot inflate loot. Each row salts hr_seed
    --     with the dungeon, the run key (p_intent_id) and the ordinal, so the
    --     roll is deterministic and replayable from the ledger yet unpredictable
    --     (the 256-bit secret). Additive upsert (the muster-chest idiom).
    for r in select ord, item_id, qty_min, qty_max, chance
               from public.hr_dungeon_loot
              where dungeon_id = v_dun.dungeon_id order by ord loop
      v_rc := (public.hr_seed(v_uid, v_slot,
                 'dungeon:' || v_dun.dungeon_id || ':' || p_intent_id::text || ':' || r.ord || ':c')
               & 4294967295)::numeric / 4294967296.0;
      if v_rc < r.chance then
        v_rq := (public.hr_seed(v_uid, v_slot,
                   'dungeon:' || v_dun.dungeon_id || ':' || p_intent_id::text || ':' || r.ord || ':q')
                 & 4294967295)::numeric / 4294967296.0;
        v_qty := r.qty_min + floor(v_rq * (r.qty_max - r.qty_min + 1))::bigint;
        insert into public.player_inventory as pi (user_id, slot, item_id, qty)
          values (v_uid, v_slot, r.item_id, v_qty)
          on conflict (user_id, slot, item_id) do update set qty = pi.qty + excluded.qty;
        v_items := v_items || jsonb_build_object(r.item_id, v_qty);
        v_qty_total := v_qty_total + v_qty;
      end if;
    end loop;

    -- (h) SCRIP CREDIT + version bump. accrued_to UNTOUCHED (a run is not an
    --     activity change — stamping it would confiscate the elapsed accrual
    --     window, hr_unlock_buy's rule).
    update public.player_state
       set dungeon_scrip = dungeon_scrip + v_scrip,
           version = version + 1,
           updated_at = now()
     where user_id = v_uid and slot = v_slot;

    -- (i) THE JOURNAL. ONE row, kind='dungeon'. qty_in/gold_in/xp_in = 0 explicit
    --     (a fixed server-owned reward, kept OUT of the accrual daily inflow
    --     budget, like the muster credit). The scrip movement is meta->>'scrip';
    --     meta.dungeon + meta.mode are read by the cooldown query above.
    --     ⚠ meta.op='settle' is the EXPLICIT row-kind discriminator (Designer
    --     ruling 2026-09-05): the earn-cap (e) sums positive scrip and the count-
    --     cap (e2) counts op='settle', so a Quartermaster spend row (op='qm_buy',
    --     negative scrip — 2026-09-11-quartermaster-buy.sql) can never fold into
    --     either fuse. A settle ALWAYS earns >= 0 scrip and carries op='settle'.
    insert into public.player_ledger
      (user_id, slot, kind, intent, gold, gold_in, xp_in, qty_in, gems_in, meta)
    values
      (v_uid, v_slot, 'dungeon', v_intent, 0, 0, 0, 0, 0,
       jsonb_build_object('op', 'settle',
                          'dungeon', v_dun.dungeon_id, 'mode', p_mode, 'quality', v_q,
                          'key_spent', v_key, 'scrip', v_scrip,
                          'items', v_items, 'item_qty', v_qty_total, 'idem', p_intent_id));

    -- (j) THE RECEIPT + THE ENVELOPE, STATED BY THE SERVER. hr_state_of verbatim
    --     (the client renders it and computes nothing) plus what was settled.
    v_settled := jsonb_build_object('dungeon', v_dun.dungeon_id, 'mode', p_mode,
                                    'scrip', v_scrip, 'items', v_items, 'key_spent', v_key);
    v_out := public.hr_state_of(v_uid, v_slot)
             || jsonb_build_object('ok', true, 'settled', v_settled);

  exception
    when sqlstate 'HR000' then
      get stacked diagnostics v_msg = message_text, v_det = pg_exception_detail;
      v_out := jsonb_build_object('ok', false, 'error', v_msg)
               || coalesce(nullif(v_det, '')::jsonb, '{}'::jsonb);
    when invalid_text_representation or numeric_value_out_of_range
      or check_violation or not_null_violation or foreign_key_violation
      or unique_violation or datatype_mismatch then
      get stacked diagnostics v_sqlstate = returned_sqlstate, v_msg = message_text;
      v_out := jsonb_build_object('ok', false, 'error', 'bad_dungeon_write',
                                  'sqlstate', v_sqlstate, 'detail', v_msg);
  end;

  -- ── (5) CACHE THE DECISION — SUCCESS ONLY. A refusal (on_cooldown, daily_cap,
  --        level_locked, insufficient_item) stays retryable; a version_conflict
  --        is not cached either, so a re-read retry can succeed — no key-release
  --        dance is needed because nothing failing is ever stored. The cached
  --        value is the {ok, settled} receipt; the replay branch §(4) reunites it
  --        with FRESH state.
  if coalesce(v_out->>'ok', 'false') = 'true' then
    insert into public.player_intents (user_id, intent_id, slot, intent, result, at)
      values (v_uid, p_intent_id, v_slot, v_intent,
              jsonb_build_object('ok', true, 'settled', v_out->'settled'), now())
      on conflict (user_id, intent_id) do nothing;
  else
    perform public.hr_record_rejection(v_uid, v_slot, v_intent, v_out->>'error',
                                       v_out - 'ok' - 'error');
  end if;

  return v_out;
end $$;

-- ── 3. GRANTS — revoke from PUBLIC first, then grant to hr_engine ONLY ──────
-- ⚠ IF THE BROWSER COULD CALL THIS, THE BROWSER COULD SETTLE A RUN FOR ITSELF
--   with p_user its own id and mint scrip + loot without the Edge Function in
--   the way. Engine-only, exactly like hr_unlock_buy: the client sends an INTENT
--   to the Edge Function (POST /hr-accrue), which is the only caller.
revoke execute on function public.hr_dungeon_settle(uuid, int, bigint, uuid, text, text, numeric) from public;
revoke execute on function public.hr_dungeon_settle(uuid, int, bigint, uuid, text, text, numeric)
  from anon, authenticated, service_role;
grant  execute on function public.hr_dungeon_settle(uuid, int, bigint, uuid, text, text, numeric) to hr_engine;

-- ── 4. STRUCTURAL ASSERTIONS ───────────────────────────────────────────────
do $$
declare v_p oid; v_bad text;
begin
  v_p := to_regprocedure('public.hr_dungeon_settle(uuid,int,bigint,uuid,text,text,numeric)');
  if v_p is null then raise exception 'hr_dungeon_settle did not install'; end if;

  -- (a) THE ACL, enumerated (not summarised): no client role may execute it.
  foreach v_bad in array array['public','anon','authenticated','service_role'] loop
    if has_function_privilege(v_bad, v_p, 'execute') then
      raise exception 'hr_dungeon_settle is EXECUTABLE BY % — a client that can call it can settle a '
                      'run for itself with no Edge Function in the way', v_bad;
    end if;
  end loop;
  if not has_function_privilege('hr_engine', v_p, 'execute') then
    raise exception 'hr_dungeon_settle is not executable by hr_engine — the only legitimate caller '
                    'cannot call it, so every settle would 42883 and the verb is inert';
  end if;
  if (select prosecdef from pg_proc where oid = v_p) is not true then
    raise exception 'hr_dungeon_settle is not SECURITY DEFINER — hr_engine holds no table grants';
  end if;
  if not exists (select 1 from unnest(coalesce((select proconfig from pg_proc where oid = v_p),
                                               array[]::text[])) c where c like 'search_path=%') then
    raise exception 'hr_dungeon_settle has no pinned search_path — a definer function without one is '
                    'a search_path hijack';
  end if;
  if (select provolatile from pg_proc where oid = v_p) <> 'v' then
    raise exception 'hr_dungeon_settle is not VOLATILE — it writes; a STABLE declaration would let '
                    'PostgREST run it read-only and every settle would fail';
  end if;

  -- (b) NO NEW CLIENT WRITE SURFACE on the four tables this verb owns.
  select string_agg(table_name || ':' || privilege_type, ', ') into v_bad
    from information_schema.role_table_grants
   where table_schema = 'public'
     and table_name in ('player_state','player_inventory','player_ledger','player_intents')
     and grantee in ('anon','authenticated','service_role','PUBLIC','hr_engine')
     and privilege_type <> 'SELECT';
  if v_bad is not null then
    raise exception 'client/engine write grants on the tables this verb owns: %', v_bad;
  end if;

  -- (c) THE ENGINE STILL HOLDS NO TABLE PRIVILEGE — this file grants it a
  --     FUNCTION; the capability pin is that it holds nothing else.
  select string_agg(table_name || ':' || privilege_type, ', ') into v_bad
    from information_schema.role_table_grants
   where grantee = 'hr_engine' and table_schema = 'public';
  if v_bad is not null then
    raise exception 'hr_engine gained table privileges (%) — the capability pin is broken', v_bad;
  end if;

  -- (d) THE CATALOGUES ARE NOT CLIENT-WRITABLE (and not even client-readable).
  if exists (select 1 from information_schema.role_table_grants
              where table_schema = 'public' and table_name in ('hr_dungeons','hr_dungeon_loot')
                and grantee in ('anon','authenticated','service_role','PUBLIC')) then
    raise exception 'a client grant exists on the dungeon catalogue';
  end if;

  raise notice 'dungeon-settle §4 PASSED: engine-only ACL, SECURITY DEFINER + pinned search_path + '
               'VOLATILE, no client write surface on the four tables it owns, engine capability pin, '
               'client-unreadable catalogues.';
end $$;

-- ── 5. hr_assert_grant_hygiene — admit the ONE new engine grant ─────────────
-- GENERATED by tools/derive-grant-hygiene.mjs (LINKS[7]) from
-- 2026-09-10-attended-loot-credit.sql's committed body, INSERTIONS ONLY
-- (one entry at the head of c_engine_allow). ⚠ REBASED for b504: increment 2 was
-- cut against b501 and derived this from 2026-08-20-live-progress-engine-allow.sql
-- (then link 6); b504 landed the attended kill ledger as link 7, so this now
-- derives from it — the body below therefore ALSO carries the hr_attended_kills
-- allowlist entry, and this file MUST APPLY AFTER attended-loot-credit. Do NOT
-- hand-edit; `--check` is a preflight in tests/run-smoke.mjs and PART 1f-ii walks
-- this as the chain's EIGHTH link. This file is the CURRENT LAST TOUCHER of the
-- detector.
-- ⟦DERIVED hr_assert_grant_hygiene — tools/derive-grant-hygiene.mjs, do not hand-edit⟧
create or replace function public.hr_assert_grant_hygiene(p_strict boolean default true)
returns jsonb language plpgsql stable security definer set search_path = public, pg_catalog as $$
declare
  v_public_exec   jsonb;   -- D1 + D3: PUBLIC holds EXECUTE (functions AND procedures)
  v_unapproved    jsonb;   -- D2: client-executable but not in the baseline
  v_lost          jsonb;   -- baseline rows whose function is gone (reported)
  v_client_trunc  jsonb;   -- TRUNCATE/REFERENCES/TRIGGER on any relation
  v_defacl_open   jsonb;   -- D4: owners with no fail-closed GLOBAL default ACL
  v_platform      jsonb;   -- residual, reported only
  v_engine_extra  jsonb;   -- S9: hr_engine EXECUTE outside its allowlist
  v_engine_tables jsonb;   -- S9: hr_engine holding any table privilege
  v_ungated       jsonb;   -- A9: client-callable SECURITY DEFINER with no rate gate
  v_report jsonb;

  -- ══════════════════════════════════════════════════════════════════════
  -- S9 — THE hr_engine CAPABILITY PIN, MOVED HERE (Security, 2026-08-11)
  -- ──────────────────────────────────────────────────────────────────────
  -- It used to live in 2026-08-11-market-v2.sql §9(i), which is three defects
  -- at once and the reason it is now here:
  --
  --   1. IT DOES NOT RUN. market-v2 is UNAPPLIED and cannot be applied until
  --      the server owns gold and inventory. A pin inside an unapplied
  --      migration is a comment. hr_assert_grant_hygiene runs at every apply
  --      AND nightly via pg_cron, and its failures surface as maintenance_alerts.
  --   2. IT MATCHED ON `proname`. `p.proname <> all (array[...])` accepts ANY
  --      overload of an approved name — `hr_seed(text)` added next to
  --      `hr_seed(uuid,int,text)` would pass silently. Keyed on
  --      `p.oid::regprocedure::text` an overload is a different string and is
  --      therefore a finding, which is the correct answer.
  --   3. IT FILTERED `prokind = 'f'`. A PROCEDURE was invisible to it — exactly
  --      defect D1 that this file's own rewrite was written to fix, reproduced
  --      one section later.
  --
  -- ⚠ EVERY ENTRY CARRIES A ONE-LINE JUSTIFICATION. In the old list only entry
  --   8 did, which meant the first seven were "bounded and fine" by tradition.
  --   Adding an entry is a CLAIM: read-only or self-validating, and it accepts
  --   no target the caller is not already authorised for. Re-derive that for
  --   the whole list every time it changes.
  c_engine_allow constant text[] := array[
    -- ── ADDED 2026-09-10 — THE DUNGEON SETTLE WRITER ───────────────────
    -- At the HEAD again, an INSERTION, for the same reason as links 1/2/5/6: it
    -- removes nothing, so PART 1f-ii grades this link with an EMPTY
    -- declared-removals list. Position carries no meaning — check (7) tests
    -- membership with `<> all (...)`.
    --
    -- ⚠ NOT READ-ONLY, and the claim rests on SELF-VALIDATING, re-derived. Its
    -- whole caller-supplied surface is: a character slot, a version, an
    -- idempotency uuid, a DUNGEON ID (a primary key in the generated,
    -- client-unwritable hr_dungeons), a MODE (auto|manual|scavenger), and a
    -- p_quality CLAMPED server-side to [0,1] that scales SELF-ONLY scrip and
    -- touches NO loot. No item, no qty, no chance, no price and no timestamp
    -- cross. Every number it writes comes from hr_dungeons / hr_dungeon_loot or
    -- the character's OWN row read under the SAME advisory lock hr_apply takes;
    -- loot is rolled by the server hr_seed PRNG (never a client value); the entry
    -- KEY is debited from the caller's own player_inventory (the load-bearing
    -- gate); the cooldown and the per-day scrip cap read now() and the
    -- append-only ledger. NO NEW TARGET: p_user is the parameter the engine
    -- already passes to hr_apply and hr_state_of. WHY THE ENGINE NEEDS IT:
    -- dungeon scrip + run loot are server-of-record (dungeon-settlement.md
    -- §1/§2) and NO other RPC writes player_state.dungeon_scrip, so without this
    -- the only writer of the currency is the client.
    'hr_dungeon_settle(uuid,integer,bigint,uuid,text,text,numeric)',
    -- ── ADDED 2026-09-10 — THE ATTENDED KILL LEDGER PROJECTION ──────────
    -- At the HEAD again, an INSERTION, for the same reason as links 1, 2, 5 and
    -- 6: it removes nothing, so PART 1f-ii grades this link with an EMPTY
    -- declared-removals list. Position carries no meaning — check (7) tests
    -- membership with `<> all (...)`.
    --
    -- READ-ONLY: `language sql`, `stable` — three CTEs over hr_kill_credit_log
    -- and player_state and a jsonb_build_object. No PL/pgSQL body through which a
    -- later edit could smuggle a write without the language keyword changing,
    -- which is the same strongest-available shape the three link-6 projections
    -- carry. The authoring migration's GATE(b) asserts that shape rather than
    -- describing it.
    -- SELF-VALIDATING: fixed output, its own per-target and per-key ceilings, and
    -- it sums `credit` (what hr_bounty_kill_cap allowed) and never `claimed`
    -- (what the client sent). GATE(e2) executes that distinction.
    -- NO NEW TARGET: (p_user, p_slot) — the exact pair the engine already hands
    -- hr_apply and hr_state_of. The holder of hr_apply can already WRITE any
    -- character it names; this lets it READ one integer per monster for one of
    -- them, out of a table hr_engine holds no privilege on (GATE(c)). The third
    -- argument, p_upto, is the engine's own hr_state_of now() and is CLAMPED with
    -- least(p_upto, now()), so it can only ever SHRINK the projected window —
    -- Security condition C6, executed by that migration's GATE(e6).
    -- WHY THE ENGINE NEEDS IT: the settle is the ONE writer of loot and gold, and
    -- it priced attended windows by re-simulating them as unattended — measured
    -- 9 kills against 15 the server had already accepted, i.e. 38% of a session's
    -- drops confiscated. See docs/design/attended-loot-credit.md.
    'hr_attended_kills(uuid,integer,timestamp with time zone)',
    -- ── ADDED 2026-08-20 — THE THREE LIVE-PROGRESS READ PROJECTIONS ─────
    -- At the HEAD again, an INSERTION, for the same reason as links 1, 2 and 5:
    -- it removes nothing, so PART 1f-ii grades this link with an EMPTY
    -- declared-removals list. Position carries no meaning — check (7) tests
    -- membership with `<> all (...)`.
    --
    -- All three are READ-ONLY (`stable sql`) dedicated projections for ONE
    -- character, added by 2026-08-20-bestiary.sql / 2026-08-21-collection.sql /
    -- 2026-08-20-renown.sql. hr_state_of stopped serving the ev:kill_monster:%
    -- and ev:loot:% populations (2026-08-21-streak-state.sql) because together
    -- they approach its 1000-row envelope cap, so the engine reads them through
    -- these instead. SELF-VALIDATING and NO NEW TARGET, the same claim
    -- hr_state_of / hr_perks_of make: each takes (p_user, p_slot) — the exact
    -- pair the engine already passes to hr_apply and hr_state_of — reads a
    -- STRICT SUBSET of what hr_state_of's envelope used to carry, writes nothing,
    -- calls nothing that writes, and exposes no target the holder of hr_apply
    -- could not already reach.
    'hr_bestiary_of(uuid,integer)',
    'hr_collection_of(uuid,integer)',
    'hr_renown_of(uuid,integer)',
    -- ── ADDED 2026-08-17 — THE THREE MARKET WRITERS ─────────────────────
    -- At the HEAD, an insertion, for the same reason as links 1 and 2: it
    -- removes nothing, so PART 1f-ii grades this link with an EMPTY
    -- declared-removals list. Position carries no meaning — check (7) tests
    -- membership with `<> all (...)`.
    --
    -- ⚠ THE LARGEST SINGLE WIDENING SINCE hr_apply: three writers at once, and
    -- ONE OF THEM MOVES VALUE BETWEEN TWO PLAYERS. The c_engine_allow claim is
    -- "read-only or SELF-VALIDATING, and it accepts no target the caller is not
    -- already authorised for". None of these is read-only, so the whole claim
    -- rests on the other two clauses, re-derived rather than asserted:
    --
    --   SELF-VALIDATING. The entire caller-supplied surface of the three is a
    --   character slot, an idempotency uuid, a version, and then: an ITEM ID +
    --   COUNT + ASK (list), a LISTING ID (cancel), a LISTING ID + COUNT (buy).
    --   No price crosses on a buy — ask_each is read off the listing row under
    --   its own lock — no timestamp, no name, no fee rate, no counterparty. The
    --   item must be `tradeable` in the generated, client-unwritable hr_items;
    --   the tax rate and every ceiling come from hr_market_config; the seller
    --   name is derived from profiles; every clock is now(). Each function
    --   re-reads its listing FOR UPDATE and re-validates under hr_apply's own
    --   advisory lock, refuses a stale version, and is clamped per call (a gross
    --   ceiling) AND per DAY (list churn; gold sent; gold received) from the
    --   append-only ledger — the dimension a rate limit does not bound.
    --
    --   THE TARGET CLAUSE, STATED HONESTLY (Security M2). The earlier draft
    --   claimed "the engine cannot select a victim". That is FALSE and is the
    --   correction: the engine holds hr_market_list(p_user, …) for ANY user, so a
    --   compromised engine can open a listing FOR a victim it names and then
    --   settle it to itself with hr_market_buy — it can choose both sides of a
    --   trade. What admits these three is therefore NOT "no victim" but BOUNDED
    --   BLAST RADIUS: every path is a CONSERVED transfer of TRADEABLE items
    --   (buyer -gross, seller +net, tax burned — nothing minted, nothing an
    --   honest player did not already own), the item must be `tradeable` in the
    --   client-unwritable hr_items, BOTH SIDES ARE JOURNALLED (transfer +
    --   self_trade in meta), and the flows are CLAMPED PER DAY off the
    --   append-only ledger on three dimensions the engine cannot widen: escrowed
    --   item quantity (list), gold sent (buy) and gold received (buy).
    --   ⚠ THOSE CLAMPS ARE THE MARKET'S OWN, NOT hr_day_budget_check. A market
    --   transfer is conserved, so it is deliberately absent from the mint
    --   budget's qty dimension — charging a sale to the seller's daily inflow
    --   would let a stranger drain their accrual (the griefing vector in
    --   hr_market_buy's header). So the item-drain and gold-move ceilings live
    --   here and only here. p_user is the parameter the engine already passes to
    --   hr_apply.
    --
    --   WHY THE ENGINE NEEDS THEM: hr_apply is single-character by construction
    --   — one lock, one version, one journal target — so a delta shape that
    --   could move a second player's gold would be the most dangerous key in the
    --   engine's vocabulary. Without these three, the only writer of a
    --   cross-player transfer is the client, which is the hole this whole
    --   program was opened to close.
    'hr_market_list(uuid,integer,bigint,uuid,text,bigint,bigint)',
    'hr_market_cancel(uuid,integer,bigint,uuid,uuid)',
    'hr_market_buy(uuid,integer,bigint,uuid,uuid,bigint)',
    -- ── ADDED 2026-08-16 — THE FIRST WRITER ADDED SINCE hr_apply ────────
    -- At the HEAD again, and for the same reason as the link above: an
    -- insertion removes nothing, so PART 1f-ii grades this link with an EMPTY
    -- declared-removals list. Position carries no meaning — check (7) tests
    -- membership with `<> all (...)`.
    --
    -- ⚠ NOT READ-ONLY, and the claim is made on the OTHER clause. It writes
    -- one player_progress unlock row, one player_state gold/version update and
    -- one player_ledger row. SELF-VALIDATING is what admits it, and concretely:
    -- its whole caller-supplied surface is ONE OFFER ID (a primary key in the
    -- generated, client-unwritable hr_unlock_offers) — no price, no quantity,
    -- no item, no rung, no timestamp; every number it writes comes from that
    -- table or from the character's own row read under the SAME advisory lock
    -- hr_apply takes; the row it writes is independently policed by the
    -- player_progress_unlock_guard trigger, which refuses an off-ladder rung, a
    -- regression and a mis-filed kind whatever this function proposes; and it
    -- is clamped per call (one rung) and per DAY (20 unlocks, counted from the
    -- append-only ledger), which is the dimension a rate limit does not bound.
    -- NO NEW TARGET: p_user is the parameter the engine already passes to
    -- hr_apply and hr_state_of. WHY THE ENGINE NEEDS IT: hr_apply structurally
    -- cannot write a level ('unlock' is deliberately absent from its delta
    -- allowlist), so without this the only writer of a permanent capability is
    -- the client.
    'hr_unlock_buy(uuid,integer,bigint,uuid,text)',
    -- ── ADDED 2026-08-16 — TWO REVIEWED ENGINE READS ────────────────────
    -- At the HEAD, not appended: this array is DERIVED from
    -- 2026-08-11-grant-hygiene.sql by tools/derive-grant-hygiene.mjs, and an
    -- append would have to rewrite the previous last entry to add a comma —
    -- a MODIFIED line. An insertion removes nothing, which is why this chain's
    -- declared-removals list in PART 1f-ii is empty. Position carries no
    -- meaning here: check (7) tests membership with `<> all (...)`.
    --
    -- read-only (STABLE, and 2026-08-16-claim-reward.sql §4 asserts the
    -- declaration rather than trusting it) claim lookup for ONE character.
    -- SELF-VALIDATING in the dimension that matters: the period keys it reads
    -- are the server's own hr_utc_day_key(now()), never an argument, so the
    -- row set is structurally bounded to '' + today + yesterday and no call
    -- can widen it into a history scan. It adds NO TARGET the engine could
    -- not already reach — the engine already holds hr_apply(uuid,…) and
    -- hr_state_of(uuid,int), both of which take the same p_user — so this is
    -- strictly a narrower read of data hr_state_of's envelope is the peer of.
    'hr_claim_lookup(uuid,integer,text,text)',
    -- read-only permanent-capability read for one character: rooms, plots,
    -- property tier and unlocked recipes. Writes nothing and calls nothing
    -- that writes. On the list for the same reason hr_offline_cap_ms is —
    -- a perk multiplies a whole night's grant, so the engine must be TOLD its
    -- capabilities rather than compute them. Same target argument as above:
    -- p_user is a parameter the engine already passes to hr_apply.
    'hr_perks_of(uuid,integer)',
    -- the only writer; bounded by its own re-validation, which is the design
    'hr_apply(uuid,integer,bigint,uuid,jsonb)',
    -- returns the post-write envelope for one character the engine was told to act for
    'hr_state_of(uuid,integer)',
    -- the accrual PRNG seed; returns a hash, never the 256-bit server secret
    'hr_seed(uuid,integer,text)',
    -- derived leaderboard value; read-only, one character
    'hr_total_level(uuid,integer)',
    -- pure function of its argument
    'hr_level_from_xp(bigint)',
    -- pure function of its argument
    'hr_xp_for_level(integer)',
    -- read-only, one integer, bounded at 24h by its own ceiling; on the list because
    -- capMs multiplies a whole night's grant, so the engine must not own its own cap
    'hr_offline_cap_ms(uuid,integer)',
    -- writes one UNLOGGED counter row for the user it was handed; on the list because
    -- the alternative, granting hr_rate_ok, lets the caller name its own limit
    'hr_rate_gate(uuid,integer,text)'
  ];
begin
  -- (1) PUBLIC=EXECUTE, asked directly.
  --     `proacl is null` is NOT "no grants" — it means the ACL is the hardwired
  --     acldefault('f', owner), which contains PUBLIC=X. That is the exact
  --     state a `create function` with no revoke lands in, so it is the single
  --     most important row of this whole function.
  select coalesce(jsonb_agg(format('%s(%s)', p.proname,
                                   pg_get_function_identity_arguments(p.oid))
                            order by p.proname), '[]'::jsonb)
    into v_public_exec
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.prokind in ('f','p')
     and (p.proacl is null or p.proacl::text ~ '(\{|,)=[a-zA-Z*]*X');

  -- (2) Client-executable and NOT approved. Covers anon and authenticated, and
  --     covers procedures, and covers a new overload of an approved name.
  select coalesce(jsonb_agg(format('%s(%s) → %s', x.proname, x.identity_args, x.grantee)
                            order by x.proname, x.grantee), '[]'::jsonb)
    into v_unapproved
    from (
      select p.proname, pg_get_function_identity_arguments(p.oid) as identity_args, g.grantee
        from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        cross join (values ('anon'),('authenticated')) g(grantee)
       where n.nspname = 'public' and p.prokind in ('f','p')
         and has_function_privilege(g.grantee, p.oid, 'execute')
    ) x
   where not exists (select 1 from public.hr_client_rpc_baseline b
                      where b.proname = x.proname and b.identity_args = x.identity_args
                        and b.grantee = x.grantee);

  -- (3) An approved RPC that is no longer reachable. Not a security failure —
  --     a BROKEN FEATURE — so it is reported, loudly, and never fatal.
  select coalesce(jsonb_agg(format('%s(%s) → %s', b.proname, b.identity_args, b.grantee)
                            order by b.proname), '[]'::jsonb)
    into v_lost
    from public.hr_client_rpc_baseline b
   where not exists (
     select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'public' and p.proname = b.proname
        and pg_get_function_identity_arguments(p.oid) = b.identity_args
        and has_function_privilege(b.grantee, p.oid, 'execute'));

  -- (4) TRUNCATE bypasses row-level security entirely, so RLS is not a backstop
  --     for it. No client ever needs TRUNCATE, REFERENCES or TRIGGER.
  --     b354 (Security C3) — WIDENED, and the second half is the interesting
  --     one. A client WRITE grant on a table that has RLS ON and NO WRITE
  --     POLICY AT ALL is a grant nothing intends to use: the only thing between
  --     it and the table is row-level security, and one `create policy` — or
  --     one `alter table ... disable row level security` typed during an
  --     incident — turns it into a client-writable table. Security found six of
  --     them live (hr_castle_*, hr_hunt_*): pure content catalogues carrying
  --     anon/authenticated INSERT/UPDATE/DELETE.
  --     WHY IT IS A BASELINE AND NOT A BAN: 21 further tables were in this class
  --     when the check was written (clan_*, world_event_*, raid_*, maintenance_*,
  --     display_names, leaderboard_meta) — all written only by SECURITY DEFINER
  --     RPCs, all dead grants, and none of them safe to sweep in the same change
  --     that introduced the detector. They are RECORDED in
  --     hr_client_write_baseline, which makes each one a claim somebody has to
  --     justify, and makes anything NEW fatal.
  --     service_role is deliberately NOT in the grantee list: Supabase's platform
  --     default grants it every privilege on every table in public, so including
  --     it would report all 40-odd tables and the check could never be strict.
  --     That is a platform posture and a separate program; stated here so its
  --     absence is a decision rather than an oversight.
  --     b350 (Security batch 5) — THE DETECTOR TAKEOVER. This query no longer
  --     reads information_schema.role_table_grants, which reports SQL-standard
  --     privileges ONLY: it cannot see MAINTAIN (the PG17 VACUUM/ANALYZE/CLUSTER/
  --     REINDEX/REFRESH privilege) and it OMITS materialized views entirely. Both
  --     are exactly where dead client write grants hid — 28 MAINTAIN pairs and the
  --     leaderboard_ranked matview were invisible to every nightly run.
  --     has_table_privilege over pg_class sees the full PG17 vocabulary AND every
  --     relkind. Two arms, the same meaning check (4) has always had:
  --       ARM 1 — a verb NO CLIENT EVER NEEDS, on ANY relation (table, partition
  --               or MATVIEW): TRUNCATE, REFERENCES, TRIGGER, and now MAINTAIN. A
  --               write policy is no defence against any of these, so the grant is
  --               a finding wherever it lives.
  --       ARM 2 — INSERT/UPDATE/DELETE on a table with RLS ON and NO write policy,
  --               minus hr_client_write_baseline. Unchanged. Matviews carry no RLS
  --               and cannot be written through any path, so an i/u/d bit on one is
  --               inert and deliberately NOT arm 2's business.
  --     PUBLIC is not enumerated separately: a grant to PUBLIC makes
  --     has_table_privilege true for anon AND authenticated, so it surfaces under
  --     both without a third grantee.
  select coalesce(jsonb_agg(distinct x.g order by x.g), '[]'::jsonb) into v_client_trunc from (
    select c.relname || ':' || gg || ':' || pv as g
      from pg_class c
      cross join unnest(array['anon','authenticated']) gg
      cross join unnest(array['TRUNCATE','REFERENCES','TRIGGER','MAINTAIN']) pv
     where c.relnamespace = 'public'::regnamespace and c.relkind in ('r','p','m')
       and has_table_privilege(gg, c.oid, pv)
    union all
    select c.relname || ':' || gg || ':' || pv
      from pg_class c
      cross join unnest(array['anon','authenticated']) gg
      cross join unnest(array['INSERT','UPDATE','DELETE']) pv
     where c.relnamespace = 'public'::regnamespace and c.relkind in ('r','p')
       and c.relrowsecurity
       and has_table_privilege(gg, c.oid, pv)
       and not exists (select 1 from pg_policies pp
                        where pp.schemaname = 'public' and pp.tablename = c.relname
                          and pp.cmd in ('INSERT','UPDATE','DELETE','ALL'))
       and not exists (select 1 from public.hr_client_write_baseline bl
                        where bl.table_name = c.relname and bl.grantee = gg)
  ) x;

  -- (5) D4 — THE POSITIVE ASSERTION. For every role that owns a function in
  --     public there must be a GLOBAL default-ACL row (defaclnamespace = 0)
  --     for functions, and it must grant EXECUTE to none of PUBLIC / anon /
  --     authenticated. Only a GLOBAL row replaces acldefault(); a schema-scoped
  --     one can only ADD to it, which is why the 2026-08-10 attempt at this
  --     changed nothing. Absence of the row IS the finding.
  select coalesce(jsonb_agg(r.rolname order by r.rolname), '[]'::jsonb)
    into v_defacl_open
    from (select distinct p.proowner from pg_proc p
            join pg_namespace n on n.oid = p.pronamespace
           where n.nspname = 'public' and p.prokind in ('f','p')) o
    join pg_roles r on r.oid = o.proowner
   where not exists (
     select 1 from pg_default_acl d
      where d.defaclrole = o.proowner
        and d.defaclnamespace = 0
        and d.defaclobjtype = 'f'
        and not exists (
          select 1 from aclexplode(d.defaclacl) a
          left join pg_roles rr on rr.oid = a.grantee   -- grantee 0 = PUBLIC
           where a.privilege_type = 'EXECUTE'
             and (a.grantee = 0 or rr.rolname in ('anon','authenticated'))));

  -- (6) Residual: platform-owned SCHEMA default ACLs we genuinely cannot edit
  --     (supabase_admin). Reported so the residual stays visible. This is the
  --     check revision 1 mistook for the real one — kept, demoted, labelled.
  select coalesce(jsonb_agg(d.defaclrole::regrole::text || ':' || n.nspname
                            order by d.defaclrole::regrole::text), '[]'::jsonb)
    into v_platform
    from pg_default_acl d join pg_namespace n on n.oid = d.defaclnamespace
   where n.nspname = 'public' and d.defaclobjtype = 'f'
     and d.defaclacl::text ~ '(anon|authenticated)=[a-zA-Z*]*X';

  -- (7) S9 — hr_engine's EXECUTE surface, keyed on the FULL SIGNATURE and with
  --     no prokind filter, so an overload and a procedure are both visible.
  --     Skipped silently if the role does not exist: this file must stand alone
  --     on a database that has not had the server-authority bundle applied.
  if exists (select 1 from pg_roles where rolname = 'hr_engine') then
    select coalesce(jsonb_agg(p.oid::regprocedure::text order by p.oid::regprocedure::text), '[]'::jsonb)
      into v_engine_extra
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prokind in ('f','p')
       and has_function_privilege('hr_engine', p.oid, 'execute')
       and p.oid::regprocedure::text <> all (c_engine_allow);
    -- "Zero table privileges" is the other half of the capability claim, and
    -- column grants are invisible to role_table_grants, so both are asked.
    select coalesce(jsonb_agg(x.g order by x.g), '[]'::jsonb) into v_engine_tables from (
      select table_name || ':' || privilege_type as g
        from information_schema.role_table_grants
       where table_schema = 'public' and grantee = 'hr_engine'
      union all
      select table_name || '.' || column_name || ':' || privilege_type
        from information_schema.role_column_grants
       where table_schema = 'public' and grantee = 'hr_engine') x;
  else
    v_engine_extra  := '[]'::jsonb;
    v_engine_tables := '[]'::jsonb;
  end if;

  -- (8) A9 — every client-callable SECURITY DEFINER function must reference a
  --     rate gate. This is the RUNTIME twin of the static lint in
  --     tests/run-sql-tests.mjs, and it exists for one specific reason: the A9
  --     retrofit in 2026-08-11-authenticated-surface-lockdown.sql installs thin
  --     wrappers over renamed `__ungated` bodies, so RE-APPLYING an older
  --     migration that `create or replace`s a wrapped name would silently
  --     replace the wrapper with the ungated body and delete the gate. A repo
  --     lint cannot see that; this can, within a day.
  --     Matching on prosrc is deliberately crude — it proves the gate is
  --     MENTIONED, not that it is reached. It catches the whole class this is
  --     written for (a body that has never heard of a gate) and nothing subtler.
  select coalesce(jsonb_agg(p.oid::regprocedure::text order by p.oid::regprocedure::text), '[]'::jsonb)
    into v_ungated
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.prokind in ('f','p') and p.prosecdef
     and (has_function_privilege('anon', p.oid, 'execute')
       or has_function_privilege('authenticated', p.oid, 'execute'))
     and p.prosrc !~ 'hr_rpc_gate|hr_rate_gate|hr_rate_ok';

  v_report := jsonb_build_object(
    'public_execute_functions',        v_public_exec,
    'unapproved_client_rpcs',          v_unapproved,
    'baseline_rows_no_longer_live',    v_lost,
    'client_truncate_grants',          v_client_trunc,
    'owners_without_failclosed_defacl',v_defacl_open,
    'platform_schema_defacls_open',    v_platform,
    'engine_execute_outside_allowlist',v_engine_extra,
    'engine_table_privileges',         v_engine_tables,
    'ungated_client_rpcs',             v_ungated);

  if jsonb_array_length(v_lost) > 0 then
    raise warning 'GRANT HYGIENE: % approved client RPC(s) are no longer reachable — %',
      jsonb_array_length(v_lost), v_lost::text;
  end if;

  if p_strict and (jsonb_array_length(v_public_exec) > 0
                or jsonb_array_length(v_unapproved) > 0
                or jsonb_array_length(v_client_trunc) > 0
                or jsonb_array_length(v_defacl_open) > 0
                or jsonb_array_length(v_engine_extra) > 0
                or jsonb_array_length(v_engine_tables) > 0
                or jsonb_array_length(v_ungated) > 0) then
    raise exception 'GRANT HYGIENE FAILED: %', v_report::text;
  end if;
  return v_report;
end $$;
-- ⟦/DERIVED hr_assert_grant_hygiene⟧
-- `create or replace` PRESERVES the existing ACL, so on a database that already
-- ran grant-hygiene this is belt-and-braces. Restated anyway (the lesson of every
-- restated body in this tree): a detector that arrives PUBLIC-executable for one
-- migration is a detector an attacker can read the allowlist out of. No `grant`
-- line — this adds no capability to anybody; it only records the reviewed
-- engine-only grant hr_dungeon_settle already carries.
revoke execute on function public.hr_assert_grant_hygiene(boolean)
  from public, anon, authenticated, service_role;

-- ── 6. SELF-VERIFYING COMMIT GATE ──────────────────────────────────────────
-- Proves the load-bearing properties by EXECUTING them. Apply is atomic, so a
-- raise reverts everything above. The row-writing probe lives in a subtransaction
-- discarded by a sentinel raise (HR819) so this block is net-zero on production.
do $$
declare
  v      jsonb; v_st jsonb;
  v_uid  constant uuid := '000000d6-0000-0000-0000-0000000000d6';
  v_slot constant int := 0;
  v_dun  text; v_key text; v_reqlv int; v_base int;
  v_i1 uuid; v_i2 uuid; v_i3 uuid;
  v_v    bigint; v_scrip0 bigint; v_scrip1 bigint; v_keyq bigint;
  v_led  int; v_hyg jsonb; v_extra jsonb;
begin
  -- Pick the LOWEST-req dungeon so the probe character only needs a modest
  -- combat level, and read its key + base from the catalogue (never hard-coded).
  select dungeon_id, cost_key, req_lv, scrip_base
    into v_dun, v_key, v_reqlv, v_base
    from public.hr_dungeons order by req_lv asc, dungeon_id asc limit 1;
  if v_dun is null then raise exception 'GATE: no dungeon in the catalogue to probe'; end if;

  begin
    perform set_config('request.jwt.claim.sub', v_uid::text, true);
    insert into auth.users (id) values (v_uid) on conflict (id) do nothing;
    insert into public.player_state (user_id, slot, gold, gems, dungeon_scrip, version)
      values (v_uid, v_slot, 0, 0, 0, 1)
      on conflict (user_id, slot) do update set dungeon_scrip = 0, version = 1;
    -- Enough combat to clear req_lv: seven combat skills at a high level.
    insert into public.player_skills (user_id, slot, skill_id, xp)
      select v_uid, v_slot, s, public.hr_xp_for_level(99)
        from unnest(array['attack','strength','defense','hitpoints','prayer','ranged','magic']) s
      on conflict (user_id, slot, skill_id) do update set xp = excluded.xp;
    -- Two entry keys, so a second run has one to consume.
    insert into public.player_inventory (user_id, slot, item_id, qty)
      values (v_uid, v_slot, v_key, 2)
      on conflict (user_id, slot, item_id) do update set qty = 2;

    -- ── LEVEL_LOCKED: a fresh (level-1) DIFFERENT probe cannot run a req>1 dungeon.
    --    Prove it by dropping the combat skills to nothing and asking.
    if v_reqlv > 1 then
      delete from public.player_skills where user_id = v_uid and slot = v_slot;
      v_i1 := gen_random_uuid();
      v := public.hr_dungeon_settle(v_uid, v_slot, 1, v_i1, v_dun, 'auto', 1);
      if v->>'error' <> 'level_locked' then
        raise exception 'GATE: an underlevelled character was not level_locked: %', v; end if;
      -- restore the skills for the rest of the probe.
      insert into public.player_skills (user_id, slot, skill_id, xp)
        select v_uid, v_slot, s, public.hr_xp_for_level(99)
          from unnest(array['attack','strength','defense','hitpoints','prayer','ranged','magic']) s
        on conflict (user_id, slot, skill_id) do update set xp = excluded.xp;
    end if;

    -- ── HAPPY PATH: scrip credited, key consumed, projected by hr_state_of.
    select dungeon_scrip, version into v_scrip0, v_v from public.player_state
      where user_id = v_uid and slot = v_slot;
    v_i1 := gen_random_uuid();
    v := public.hr_dungeon_settle(v_uid, v_slot, v_v, v_i1, v_dun, 'auto', 1);
    if coalesce(v->>'ok','') <> 'true' then raise exception 'GATE: happy-path settle failed: %', v; end if;
    if (v->'settled'->>'scrip')::bigint <> v_base then
      raise exception 'GATE: quality=1 scrip = % (expected base %)', v->'settled'->>'scrip', v_base; end if;
    -- scrip is on player_state AND projected by hr_state_of (the actual bug: it
    -- must SURVIVE a reload, which is exactly "hr_state_of returns it").
    select dungeon_scrip into v_scrip1 from public.player_state where user_id = v_uid and slot = v_slot;
    if v_scrip1 <> v_scrip0 + v_base then
      raise exception 'GATE: player_state.dungeon_scrip not credited (% -> %, +% expected)',
        v_scrip0, v_scrip1, v_base; end if;
    v_st := public.hr_state_of(v_uid, v_slot);
    if (v_st->'state'->>'dungeon_scrip')::bigint <> v_scrip1 then
      raise exception 'GATE: hr_state_of does not project the credited scrip (envelope=% row=%)',
        v_st->'state'->>'dungeon_scrip', v_scrip1; end if;
    -- the entry key was consumed (2 -> 1).
    select coalesce(qty,0) into v_keyq from public.player_inventory
      where user_id = v_uid and slot = v_slot and item_id = v_key;
    if v_keyq <> 1 then raise exception 'GATE: entry key not consumed (qty=% expected 1)', v_keyq; end if;

    -- ── IDEMPOTENT REPLAY: same key re-credits NOTHING, returns replayed:true.
    v := public.hr_dungeon_settle(v_uid, v_slot, v_v, v_i1, v_dun, 'auto', 1);
    if coalesce((v->>'replayed')::boolean, false) is not true then
      raise exception 'GATE: replay not marked replayed: %', v; end if;
    select dungeon_scrip into v_scrip0 from public.player_state where user_id = v_uid and slot = v_slot;
    if v_scrip0 <> v_scrip1 then raise exception 'GATE: replay RE-CREDITED scrip (% -> %)', v_scrip1, v_scrip0; end if;
    select coalesce(qty,0) into v_keyq from public.player_inventory
      where user_id = v_uid and slot = v_slot and item_id = v_key;
    if v_keyq <> 1 then raise exception 'GATE: replay consumed a second key (qty=%)', v_keyq; end if;

    -- ── VERSION CONFLICT: a stale version is refused, nothing moves.
    v_i2 := gen_random_uuid();
    v := public.hr_dungeon_settle(v_uid, v_slot, 999999, v_i2, v_dun, 'auto', 1);
    if v->>'error' <> 'version_conflict' then raise exception 'GATE: stale version not refused: %', v; end if;

    -- ── FORGED QUALITY CANNOT INFLATE SCRIP beyond the base band. Clear the
    --    auto cooldown (manual mode has none), and settle with p_quality = 999 —
    --    it must clamp to 1, crediting at most scrip_base.
    select version into v_v from public.player_state where user_id = v_uid and slot = v_slot;
    select dungeon_scrip into v_scrip0 from public.player_state where user_id = v_uid and slot = v_slot;
    v_i3 := gen_random_uuid();
    v := public.hr_dungeon_settle(v_uid, v_slot, v_v, v_i3, v_dun, 'manual', 999);
    if coalesce(v->>'ok','') <> 'true' then raise exception 'GATE: manual settle failed: %', v; end if;
    if (v->'settled'->>'scrip')::bigint > v_base then
      raise exception 'GATE: a forged p_quality=999 minted % scrip, more than base % — the clamp is broken',
        v->'settled'->>'scrip', v_base; end if;

    -- ── ONE ledger row per run (two ran: auto + manual).
    select count(*) into v_led from public.player_ledger where user_id = v_uid and kind = 'dungeon';
    if v_led <> 2 then raise exception 'GATE: expected 2 dungeon ledger rows, found %', v_led; end if;

    raise exception using errcode = 'HR819', message = 'dungeon-settle §6 complete — rolling back';
  exception when sqlstate 'HR819' then null;
  end;

  perform set_config('request.jwt.claim.sub', '', true);
  if exists (select 1 from public.player_state where user_id=v_uid)
     or exists (select 1 from public.player_ledger where user_id=v_uid)
     or exists (select 1 from public.player_intents where user_id=v_uid)
     or exists (select 1 from public.player_inventory where user_id=v_uid)
     or exists (select 1 from public.player_skills where user_id=v_uid)
     or exists (select 1 from auth.users where id=v_uid) then
    raise exception 'GATE: §6 LEAKED a probe row'; end if;

  -- (k) THE ENGINE ALLOWLIST ADMITS hr_dungeon_settle (the detector no longer
  --     raises engine_execute_outside_allowlist on it).
  if to_regprocedure('public.hr_assert_grant_hygiene(boolean)') is not null then
    v_hyg := public.hr_assert_grant_hygiene(false);
    v_extra := coalesce(v_hyg->'engine_execute_outside_allowlist', v_hyg->'engine_extra', '[]'::jsonb);
    if v_extra @> to_jsonb('hr_dungeon_settle(uuid,integer,bigint,uuid,text,text,numeric)'::text) then
      raise exception 'GATE: hr_dungeon_settle is an UNALLOWLISTED engine grant — §5 did not admit it';
    end if;
  end if;

  raise notice 'dungeon-settle: scrip credited + projected + survives (hr_state_of), idempotent replay, '
               'version_conflict refused, forged p_quality clamped, key consumed, per-run journal, '
               'engine allowlist admits the verb — all green';
end $$;
